feat: custom event `clickMoreEventsBtn`
nhn/tui.calendar pull request #1003
Opened 2022-01-21 01:22 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- add custom event `clickMoreEventsBtn`
- add 3 popup slots in floating layer
- split popup slice and dispatchers each type

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-01-21 01:51 UTC, adhrinae requested changes
리뷰 완료합니다.

2022-01-21 01:51 UTC, adhrinae commented on apps/calendar/src/components/popup/seeMoreEventsPopup.tsx
> +  const isHide = isNil(floatingLayerContainer) || isNil(date) || isNil(popupPosition);
`isHidden`

2022-01-21 01:51 UTC, adhrinae commented on apps/calendar/src/components/dayGridMonth/gridCell.tsx
> +      showSeeMorePopup({
타입별로 액션 분리한게 훨씬 나아보이네요 👍

2022-01-21 01:51 UTC, adhrinae commented on apps/calendar/src/components/popup/eventDetailPopup.tsx
> +    floatingLayerContainer;
실제로 쿼리셀렉터가 의도대로 동작하지 않는 경우가 있어서 `??` 처리를 했나요? 아마 TS 컴파일러에서 `null` 일 수 있으니까 처리한 것 같은데 이 경우에는 타입 캐스팅 직접 해도 무관할 것 같아요.

그리고 종합적인 결과물을 보니까, 아예 쿼리셀렉터를 쓸 필요 없이 `FloatingLayerProvider` 쪽에서 각각의 슬롯에 맞는 DOM을 뭉친 객체로 만들어서 `useFloatingLayerContainer('detail-popup')` 이런식으로 원하는 녀석만 꺼내쓸 수 있게 만드는건 어떨까요? 이름에서 Container도 빼야할거같군요.

```jsx
function FloatingLayerProvider({children}) {
  const [containerRef, containerRefCallback] = useDOMNode();
  const [popupSlotRef, popupSlotRefCallback] = useDOMNode();
  // ...

  // 여기서는 useMemo 생략
  const floatingLayers = {
    container: containerRef,
    popup: popupSlotRef,
    // ...
  };

  return (
    <FloatingLayerContext.Provider value={floatingLayers}>
      {/* ... */}
    </FloatingLayerContext.Provider>
  );
}
```

2022-01-21 01:51 UTC, adhrinae commented on apps/calendar/src/components/popup/seeMoreEventsPopup.tsx
> +      <div className={classNames.seeMore} style={{ ...moreView, padding: MONTH_MORE_VIEW_PADDING }}>
패딩값 정도는 CSS로 바로 지정해볼까요? 별로 지장 없을 것 같네요.

2022-01-21 01:51 UTC, adhrinae commented on apps/calendar/src/slices/popup.ts
> +    [PopupType.detail]: PopupParamMap[PopupType.detail] | null;
전에도 비슷한 코드 보고 잠깐 신경쓰였던건데 `PopupType` 이 `enum` 이면 보통 `enum` 의 키 값은 PascalCase나 MARCO_CASE를 쓰거든요. 전체 갈아치우는건 나중에 한다 하더라도 요건 바뀌었으면 좋겠네요.

2022-01-21 01:51 UTC, adhrinae commented on apps/calendar/src/slices/popup.ts
> +          if (!isFlat) {
어제 이야기를 해서 의도는 알겠는데 `isFlat` 이라는 변수가 정의하고자 하는 의미를 한글로 다시 표현해보시겠어요? 더 나은 변수명이 필요해보여요.

2022-01-24 01:30 UTC, lja1018 commented on apps/calendar/src/components/popup/seeMoreEventsPopup.tsx
> +      <div className={classNames.seeMore} style={{ ...moreView, padding: MONTH_MORE_VIEW_PADDING }}>
변경해보니 똑같아서 CSS파일로 옮겼습니다!

2022-01-24 01:33 UTC, lja1018 commented on apps/calendar/src/slices/popup.ts
> +          if (!isFlat) {
수정했습니다.

2022-01-24 02:55 UTC, adhrinae commented on apps/calendar/src/contexts/floatingLayer.tsx
> +export const useFloatingLayer = () => {
`useFloatingLayer('container')`
`useFloatingLayer('popup')`

이런식으로 호출해서 원하는 ref만 바로 뽑아쓸 수 있게 바뀌면 좋겠어요.

2022-01-24 03:00 UTC, lja1018 commented on apps/calendar/src/contexts/floatingLayer.tsx
> +export const useFloatingLayer = () => {
이해했습니다! 수정하겠습니다

2022-01-24 03:21 UTC, adhrinae commented on apps/calendar/src/contexts/floatingLayer.tsx
> +  return ref?.[floatingLayerType] ?? null;
`ref` 라는 변수명도 이젠 용도가 바뀌었으니 `layers` 같은 이름으로 바뀌어야겠네요.

2022-01-24 03:26 UTC, lja1018 commented on apps/calendar/src/contexts/floatingLayer.tsx
> +  return ref?.[floatingLayerType] ?? null;
넵 바꾸는 김에 안바뀐 변수랑 타입이 있길래 같이 변경했습니다!

2022-01-24 03:34 UTC, adhrinae approved these changes

2022-01-24 04:52 UTC, merged