feat: implement `getElement`, `hideMoreView`, `toggleEvents`
nhn/tui.calendar pull request #1050
Opened 2022-03-22 06:20 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- implement `getElement`, `hideMoreView`, `toggleEvents` methods
- organize type definition file

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-03-22 08:46 UTC, dotaitch reviewed
리뷰 완료합니다. 어색한 함수/변수명이 있어서 리뷰 남겼는데, 이 부분은 캘린더 회의 때 얘기 나눠보면 좋을 것 같아요.

2022-03-22 08:46 UTC, dotaitch commented on apps/calendar/index.d.ts
> +  public getViewName(): ViewType;
`changeView` 함수에 맞춰서 `getView`로 이름 바꾸는 건 어떨까요? 메이저 업데이트 하는 김에 이런 함수명도 통일시키면 좋겠네요.

2022-03-22 08:46 UTC, dotaitch commented on apps/calendar/index.d.ts
> +  public changeView(viewName: ViewType): void;
파라미터를 `viewName`에서 `view`로 바꾸는 건 어떨까요?
개인적으로는 파라미터 이름이 `viewName`인데 `viewType` 이라는 타입이 들어가는게 조금 어색해보이고, 함수명도 `changeView`라서 `view`가 더 적절해보여요.

2022-03-22 08:46 UTC, dotaitch commented on apps/calendar/index.d.ts
> +  public toggleEvents(calendarId: string, toHide: boolean): void;
이 함수는 `toggleCalendar`로 이름 바꾸는 건 어떤가요? 일정을 보이게 / 보이지 않게 하는거라서 `toggleEvents`도 틀렸다고 할 수는 없지만, `calendarId`를 넘기는 데다가 해당 캘린더의 모든 일정을 토글하는 거라서 "캘린더를 토글한다"가 더 맞는 것 같아서요.

2022-03-22 08:46 UTC, dotaitch commented on apps/calendar/src/factory/calendarControl.tsx
> +   * window.addEventListener('resize', () => {
:+1:

2022-03-22 08:46 UTC, dotaitch commented on apps/calendar/src/factory/calendarControl.spec.tsx
> +    return <Layout>mock</Layout>; // popup component is rendered in Layout component;
엄청 사소한 것이지만... 주석에 세미콜론이 붙었네요ㅎㅎ

2022-03-22 08:46 UTC, dotaitch commented on apps/calendar/index.d.ts
> +  public toggleEvents(calendarId: string, toHide: boolean): void;
그리고 "toggle"인데 `toHide` 값으로 show/hide를 정하는게 이상하네요. toggle이면 파라미터 값 없이 이전 상태의 반대값으로 바꿔줘야 할 것 같아요.

show나 hide 기능이 필요하다면 toggle과 별개로 show/hide함수를 제공하는 게 나을 것 같아요.

2022-03-23 03:21 UTC, adhrinae requested changes
리뷰 완료합니다.
이벤트 필터링하는 과정에 대해 다시금 생각해볼 필요가 있겠어요.

2022-03-23 03:21 UTC, adhrinae commented on apps/calendar/src/factory/calendarControl.tsx
> +  protected getStoreState(): CalendarState;
이게 `protected` 로 바뀌게 된 경위가 궁금하네요. 테스트를 위해서인가요?
이게 만약 이렇게 된다면 인스턴스 외부 API에 노출이 되게 될텐데요.

어차피 타입스크립트의 `private` 는 키워드에 불과하니까 그렇다 쳐도, 사용자에게 굳이 알 필요 없는 API를 노출할 필요가 있나 싶어서 가급적이면 직접 노출이 안되었으면 좋겠습니다.

2022-03-23 03:21 UTC, adhrinae commented on apps/calendar/src/factory/calendarControl.tsx
>    getElement(eventId: string, calendarId: string) {
주석 좀 정리할 필요가 있곘네요.
`@todo` 부분도 지워야하고 설명의 영어 표현도 좀 다듬어서

> Get the DOM element of the event by event id and calendar id.

쪽이 더 말이 되겠어요.

2022-03-23 03:21 UTC, adhrinae commented on apps/calendar/src/slices/calendar.ts
> +          );
정말 `Collection` 다루는 작업 볼 때마다 이게 최선인가 하는 생각에 눈물이 나는군요 😢 

immer가 Map을 지원하니까 나중에는 순회를 좀 줄이는 방식으로 개선이 될 수 있겠지요.
`events.values().forEach` 를 돌면서 조건에 맞는 이벤트를 찾자마자 `event.isVisible = !toHide` 를 하면 아마 적용이 될 거에요.

2022-03-23 05:57 UTC, lja1018 commented on apps/calendar/index.d.ts
> +  public changeView(viewName: ViewType): void;
저도 그냥 `view`는 뷰 자체의 느낌이긴 합니다. 내일 얘기 나눠보겠습니다.

2022-03-23 05:58 UTC, lja1018 commented on apps/calendar/index.d.ts
> +  public toggleEvents(calendarId: string, toHide: boolean): void;
저도 일단 v1의 메서드 그대로 구현하긴 했는데 `show`, `hide`로 메서드를 분리했으면 좋겠습니다. 마찬가지로 내일 얘기나누겠습니다.

2022-03-23 06:09 UTC, lja1018 commented on apps/calendar/src/factory/calendarControl.spec.tsx
> +    return <Layout>mock</Layout>; // popup component is rendered in Layout component;
복붙하다가 들어갔나봅니다;; 수정했습니다.

2022-03-23 06:11 UTC, lja1018 commented on apps/calendar/src/factory/calendarControl.tsx
> +  protected getStoreState(): CalendarState;
`Month`의 `hideMoreView` 메서드 구현을 위해서 `protected`로 변경했습니다. 다른 방법을 고민해봐야겠네요.

2022-03-23 06:12 UTC, lja1018 commented on apps/calendar/src/factory/calendarControl.tsx
>    getElement(eventId: string, calendarId: string) {
주석도 같이 어느정도 정리하고 있었는데 빠졌나봅니다. 수정했습니다.

2022-03-23 06:16 UTC, adhrinae commented on apps/calendar/src/factory/calendarControl.tsx
> +  protected getStoreState(): CalendarState;
그런거면 어쩔 수 없네요.
리뷰할 때는 제가 사용 예를 못찾아서요.

유의해야하는건 저걸 `protected` 로 쓰는 이상 엔드유저가 캘린더 인스턴스를 통해 스토어 관련 메서드에 접근할 수 있다는거고, 설명하는 코멘트를 남겨야할 수도 있다는거네요.

2022-03-23 06:17 UTC, lja1018 commented on apps/calendar/src/factory/calendarControl.tsx
> +  protected getStoreState(): CalendarState;
`protected`도 외부에서는 호출할 수 없지 않나요?

2022-03-23 06:19 UTC, lja1018 commented on apps/calendar/src/slices/calendar.ts
> +          );
`Collection`을 개선할 때 같이 작업해야겠네요.

2022-03-23 06:21 UTC, adhrinae commented on apps/calendar/src/factory/calendarControl.tsx
> +  protected getStoreState(): CalendarState;
아이고 제가 착각했네요 😱 다시 확인해보니까 외부에서 못쓰는거 맞네요. 그럼 이대로 가시죠.

2022-03-24 05:28 UTC, adhrinae commented on apps/calendar/src/selectors/calendar.ts
> +}
셀렉터를 다른 방식으로 고민해봐야겠네요.

적어도 지금대로라면 매번 스토어가 바뀔 때마다 리렌더될거에요. 객체 리터럴이 리턴되어 새로운 객체 레퍼런스가 형성되니까요.
일단 `calendars`, `idsOfDay` 는 별도 셀렉터로 떼어버려야겠고, 저 `events` 를 어떻게 하느냐인데... 어차피 이렇게 만들거면 뭘 어떻게 해도 새로운 객체를 만드는게 될테니까 리렌더링을 피할 수 없겠네요.

아쉽지만 막상 결과물을 보니 그냥 이벤트를 내려줘야하는 곳 최상단에서 `useMemo` 를 쓰는게 제일 나을 것 같습니다.

2022-03-24 05:46 UTC, lja1018 commented on apps/calendar/src/selectors/calendar.ts
> +}
네. 이전에도 객체를 통으로 가져오는 셀렉터를 가져오고있었고 `state.calendar`가 바뀌면 어차피 리렌더링을 해야한다고 생각해서 이렇게 작성을 했습니다.

2022-03-24 05:51 UTC, adhrinae commented on apps/calendar/src/selectors/calendar.ts
> +}
이게 문제가 `state.calendar` 를 가져오는 셀렉터는 그렇게 자주 바뀌진 않는데 이 경우는 다른 상태가 변해도 바뀔거라서요. 혹시 셀렉터가 원하는 타이밍에만 새 상태를 리턴하는지 확인해 보셨나요?

2022-03-24 06:10 UTC, lja1018 commented on apps/calendar/src/selectors/calendar.ts
> +}
아 이해했습니다. 새 상태를 리턴하는지는 확인은 안해봤는데 이대로면 `isVisible` 뿐 아니라 다른게 변경되어도 매번 새롭게 생성해서 리턴하겠네요.

2022-03-24 06:44 UTC, adhrinae commented on apps/calendar/index.d.ts
> +  public changeView(viewName: ViewType): void;
`changeView`, `getViewName` 모두 특별히 인자나 메서드명의 변경은 필요 없는 것으로 결정됨.

2022-03-24 06:49 UTC, adhrinae commented on apps/calendar/index.d.ts
> +  public toggleEvents(calendarId: string, toHide: boolean): void;
- `setCalendarVisibility` 메서드 하나만으로 보이기/숨기기 처리를 하는 것으로 결정
- 여러 인자를 한번에 받을 수 있는 형태도 되도록 타입 정의나 주석 빠지지 않았는지 확인

2022-03-24 08:45 UTC, adhrinae approved these changes

2022-03-24 08:49 UTC, merged