refactor: current time indicator
nhn/tui.calendar pull request #1051
Opened 2022-03-22 07:43 UTC by adhrinae

# Conflicts:
#	apps/calendar/src/components/timeGrid/timeGrid.tsx

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- Refined the `CurrentTimeIndicator` component
  - use theme color
  - removed unused props (NOTE: `dateDifference` might be needed when applying timezone)
- Implemented useful custom hooks: useInterval, useIsMounted

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-03-22 09:36 UTC, dotaitch requested changes
리뷰 완료합니다.

2022-03-22 09:36 UTC, dotaitch commented on apps/calendar/src/components/timeGrid/timeGrid.spec.tsx
> +  const timeColumnTestId = 'timegrid-time-column';
test id도 상수처럼 관리하는 건 어떨까요?

2022-03-22 09:36 UTC, dotaitch commented on apps/calendar/src/components/timeGrid/times.tsx
> +      {showCurrentTime ? <CurrentTimeLabel unit={unit} time={currentTime} top={top} /> : null}
```suggestion
      {showCurrentTime && <CurrentTimeLabel unit={unit} time={currentTime} top={top} />}
```

삼항연산자 말고 `&&`를 써도 되지 않을까요?

2022-03-22 09:36 UTC, dotaitch commented on apps/calendar/src/hooks/common/useInterval.ts
> +    if (isPresent(delay)) {
`delay`가 0일 때도 처리해야 하지 않을까요? `delay`가 0인 것과 null인 것 모두 "delay가 없다"라고 생각되어서요.
그리고 이왕 하는김에 양수일 때만 setInterval을 실행하도록 하는게 좋을 것 같아요.

2022-03-23 03:21 UTC, adhrinae commented on apps/calendar/src/components/timeGrid/timeGrid.spec.tsx
> +  const timeColumnTestId = 'timegrid-time-column';
생각해보면 그게 나을거같아요. 이번에 `src/constants/test` 같은 파일로 분리해볼게요.

2022-03-23 03:23 UTC, adhrinae commented on apps/calendar/src/components/timeGrid/times.tsx
> +      {showCurrentTime ? <CurrentTimeLabel unit={unit} time={currentTime} top={top} /> : null}
그러게요. 일단 `&&` 으로 고칠게요. 참고로 컴포넌트 렌더링에 `&&` 을 사용하는 경우는 실수할 여지가 있으니 가급적이면 확실하게 불린값으로 구분되는 경우만 사용하는걸 권장하고 싶습니다.

https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx

2022-03-23 03:24 UTC, adhrinae commented on apps/calendar/src/hooks/common/useInterval.ts
> +    if (isPresent(delay)) {
어차피 캘린더 내에서 `useInterval` 이 한 군데 말고는 쓰일 일이 없어보이긴 하지만, 설계 측면에서 타당한 제안이네요. 변경해두겠습니다.

2022-03-23 04:58 UTC, adhrinae commented on apps/calendar/src/components/timeGrid/timeGrid.spec.tsx
> +  const timeColumnTestId = 'timegrid-time-column';
파일을 분리하면서 생각을 해 봤는데, 지금 `data-testid` 를 먹인 부분이 되도록이면 testid 대신 적절한 ARIA Role을 부여한다음에 그거 기반으로 셀렉트가 되도록 개선하는게 장기적인 관점에서 더 낫겠다는 생각이 드네요.

testid 사용에 익숙해져서 테스트 코드가 더러워져서 손대기 어려워지기 전에 개선을 하는게 좋겠어요.

2022-03-23 05:33 UTC, lja1018 reviewed
리뷰 완료합니다.

2022-03-23 05:33 UTC, lja1018 commented on apps/calendar/src/components/timeGrid/currentTimeIndicator.tsx
> +        style={{ left: leftLine.left, backgroundColor: currentTimeColor }}
계속 인라인 스타일 그대로 사용해도 별 문제 없을까요?

2022-03-23 05:33 UTC, lja1018 commented on apps/calendar/src/components/timeGrid/timeGrid.tsx
> +      isSameDate(column.date, new TZDate())
사소한건데 `findIndex` 밖에서 TZDate 만들어놓고 사용하는건 어떠신가요? 큰 성능차이는 없을 것 같긴 하지만요.

2022-03-23 05:33 UTC, lja1018 commented on apps/calendar/src/hooks/common/useIsMounted.spec.ts
> +test('it returns true when the hook is mounted', () => {
`it` 대신 `test`가 사용된 이유가 있을까요?

2022-03-23 05:38 UTC, adhrinae commented on apps/calendar/src/components/timeGrid/currentTimeIndicator.tsx
> +        style={{ left: leftLine.left, backgroundColor: currentTimeColor }}
이 경우는 테마의 값을 사용해야하니까 인라인 스타일을 사용해야한다고 생각했지요. 별 문제는 없을 것 같은데, 질문의 의도를 모르겠어요.

2022-03-23 05:38 UTC, adhrinae commented on apps/calendar/src/components/timeGrid/timeGrid.tsx
> +      isSameDate(column.date, new TZDate())
네 미리 만들어두는게 더 낫겠네요.

2022-03-23 05:40 UTC, adhrinae commented on apps/calendar/src/hooks/common/useIsMounted.spec.ts
> +test('it returns true when the hook is mounted', () => {
Jest 안에서 `it === test` 이긴 한데, 저는 개인적인 취향으로 `it` 은 항상 `describe` 스코프 아래에 존재해야한다고 생각했거든요. 그런데 보니까 딱히 그럴 필요가 없더라고요.

테스트를 작성하는 입장에서는 `it('returns ~)` 로 작성하는게 글자가 좀더 짧아져서 좋지만, 콘솔에는 `> returns ~` 로 찍히게 될겁니다. 그렇다고 `it('it returns~)` 라고 쓸 필요는 없으니 가독성 차이가 되겠네요.

2022-03-23 06:50 UTC, merged