refactor: remove unused function
nhn/tui.calendar pull request #1052
Opened 2022-03-23 05:03 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- remove unused function and its tests
- move tests file properly
- remove JSDoc

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-03-23 06:32 UTC, adhrinae requested changes
리뷰 완료합니다.

2022-03-23 06:32 UTC, adhrinae commented on apps/calendar/src/helpers/events.spec.ts
> +  it("should collide, if the times don' collision", () => {
단언에 뭔가 빠진 느낌이네요. 의도대로라면

> should not have a collision when there is no overlap between two times

정도?

2022-03-23 06:32 UTC, adhrinae commented on apps/calendar/src/helpers/grid.spec.ts
> +});
원본 코드 보고 한참 들여다본 뒤에야 의도를 읽을 수 있었네요.
모든 경우의 수를 테스트하려는건 알겠는데 그럴거면 차라리 이 API를 활용해보는게 어떨까요? 1~5정도까지는 수기로 경우의 수를 적는다해도 그리 많진 않을 것 같아요.

https://jestjs.io/docs/api#testeachtablename-fn-timeout

2022-03-23 06:32 UTC, adhrinae commented on apps/calendar/src/utils/dom.spec.ts
> +  it('getMousePosition', () => {
테스트명이 잘못된듯?

2022-03-23 06:32 UTC, adhrinae commented on apps/calendar/src/utils/preact.ts
> - * @param prop
이거 안넣으면 IDE가 뭐라고 했던가 린트가 뭐라고 했던가 해서 넣었던 기억이... 린트에서 뭐라고 안하면 전 안넣어도 된다고 보고요.

2022-03-23 07:18 UTC, lja1018 commented on apps/calendar/src/helpers/events.spec.ts
> +  it("should collide, if the times don' collision", () => {
테스트명 같은 경우엔 건드리지 않는 쪽으로 작업해서 그렇습니다. 리뷰 반영하겠습니다.

2022-03-23 07:29 UTC, lja1018 commented on apps/calendar/src/utils/preact.ts
> - * @param prop
넵 지워도 문제 없어서 제거했습니다!

2022-03-23 07:30 UTC, lja1018 commented on apps/calendar/src/utils/dom.spec.ts
> +  it('getMousePosition', () => {
수정했습니다.

2022-03-23 08:31 UTC, lja1018 commented on apps/calendar/src/helpers/grid.spec.ts
> +});
`it.each`로 수정했습니다.

2022-03-24 08:52 UTC, adhrinae approved these changes

2022-03-24 08:52 UTC, merged