fix: prev and next work properly
nhn/tui.calendar pull request #1061
Opened 2022-03-31 05:39 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- implement `addMonth` and `subtractMonth`
- If the rendenderDate is at the end of the month, fix that `prev` and `next` do not work properly.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-04-01 01:13 UTC, dotaitch requested changes
리뷰 완료합니다~ 몇 가지 리뷰 남겼는데 이 부분 확인 부탁드려요

2022-04-01 01:13 UTC, dotaitch commented on apps/calendar/src/time/datetime.ts
> +    date.setMonth(thisMonth + step + 1, 0);
그리고 `targetDaysOfMonth` 라는 변수명이 와닿지가 않네요. 이 변수는 달의 마지막 날짜를 담으니까 `endDayOfMonth` 같은 것으로 변경하는 건 어떨까요?

2022-04-01 02:42 UTC, adhrinae requested changes
리뷰 완료합니다.

2022-04-01 02:42 UTC, adhrinae commented on apps/calendar/src/time/datetime.ts
> +    date.setMonth(thisMonth + step + 1, 0);
아무래도 `date-fns` 의 구현을 활용하는게 제일 확실할 하겠어요. 구현을 설명한 코멘트도 확실하고요.
이러면 이 계산을 위해 윤달까지 체크할 필요도 없고요.

https://github.com/date-fns/date-fns/blob/master/src/addMonths/index.ts

특히 DST 이슈 문제 해결을 위해 `step` 변수가 0인 경우(아마 어쩌다 보면 이런 경우가 있겠죠) 가공을 하지 않고 `d` 자체를 리턴하는게 중요한 것 같습니다. 필요하지 않으면 시간을 불필요하게 변경하지 말아야 문제가 없을거같아요.

2022-04-01 02:42 UTC, adhrinae commented on apps/calendar/src/factory/calendarControl.tsx
> +      newRenderDate = subtractMonth(newRenderDate, -offset);
아마 가독성 때문에 그럴거라 생각하는데요. 하고자 하는 동작이 명확하게 드러나니까요.
그래도 `addMonth` 에 음수 인자 넣는 것도 그렇게 나쁘지 않을거같아요. 요건 취향이 좀 갈리겠네요.
대신 제가 `subtractMonth` 쪽에 코멘트 남긴거처럼 내부 구현에 차이가 발생하지 않도록 만드는게 중요하겠어요.

2022-04-04 01:40 UTC, lja1018 commented on apps/calendar/src/time/datetime.ts
> +    date.setMonth(thisMonth + step + 1, 0);
`date-fns`의 `addMonths`를 참고해서 수정했습니다.

2022-04-04 01:40 UTC, lja1018 commented on apps/calendar/src/factory/calendarControl.tsx
> +      newRenderDate = subtractMonth(newRenderDate, -offset);
`subtractMonths`가 `addMonths`를 호출하는 방식으로 바꿔 내부 구현에 차이가 없도록 했습니다.

2022-04-04 01:43 UTC, lja1018 commented on apps/calendar/src/factory/calendarControl.tsx
> +      newRenderDate = subtractMonth(newRenderDate, -offset);
`subtractMonths`를 제거하고 `addMonths`에 음수 `step`을 넘겨서 계산하도록 수정했습니다.

2022-04-04 05:51 UTC, adhrinae approved these changes

2022-04-04 06:43 UTC, merged