fix: mixed(and wrong) drag and drop behaviors
nhn/tui.calendar pull request #1071
Opened 2022-04-05 10:12 UTC by adhrinae

### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has a description of the breaking change

### Description

- Found and Fixed clearing state logics when dragging ends
- Expanded the role of `useDraggingEvent` hook so that we don't have to care the lifecycle of dragging
- chore: move timegrid event resizing logic to custom hook

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-04-05 10:21 UTC, adhrinae commented on apps/calendar/src/components/events/horizontalEvent.tsx
> +      const isClick = draggingState <= DraggingState.INIT;
`useDrag` 안의 콜백이지만 실제로는 클릭만 했는지 확인하고 팝업을 실행시키기 위해 필요한 변수라 명확하게 변경했습니다.

2022-04-05 10:25 UTC, adhrinae commented on apps/calendar/src/hooks/event/useDraggingEvent.ts
> +    if (isPresent(draggingEvent) && isIdle) {
다른 곳에서 `isDraggingEnd` 로 사용하고 있던 변수를 훅 안에서 쓰도록 만들었습니다.

여기서 더 나아가 드래깅이 종료된 후의 동작도 알아서 처리할 수 있도록 변경하는게 더 낫겠다는 생각이 들어서 다음과 같이 동작할 수 있도록 고민해보게 됩니다.

```ts
const movingEvent = useDraggingEvent({
  area: 'dayGrid',
  behavior: 'move',
  onEnd: () => {
    const shouldUpdate =
      isPresent(movingEvent) &&
      isPresent(columnIndex) &&
      isPresent(currentMovingLeft) &&
      isPresent(targetEventStartGridX);

    if (shouldUpdate) {
      const dateOffset = columnIndex - targetEventStartGridX;
      let newStartDate = new TZDate(movingEvent.getStarts());
      let newEndDate = new TZDate(movingEvent.getEnds());
      newStartDate = newStartDate.addDate(dateOffset);
      newEndDate = newEndDate.addDate(dateOffset);

      updateEvent({
        event: movingEvent.model,
        eventData: {
          start: newStartDate,
          end: newEndDate,
        },
      });
    }

    clearCurrentGridPos();
  },
});
```

이런 방식으로 구현하면 개별 커스텀 훅에서 드래그가 종료되었는지를 일일이 확인하지 않고 종료 후의 동작만 작성하면 됩니다. (아쉽게도 타입시스템 때문에 `isPresent(draggingEvent)` 는 호출해줘야 할 수도 있지만)

하지만 이렇게 하면 약간 가독성을 손해볼 수 있는 것이, 코드를 위에서 아래로 읽을 수가 없고 위에서 시작하여 변수 선언부를 본 다음 다시 콜백 부분을 읽어야합니다. 동작하는 모형은 이미 만들어봤으니 의견 나누고 적용할지 결정하면 되겠습니다.

2022-04-05 10:26 UTC, adhrinae commented on apps/calendar/src/hooks/timeGrid/useTimeGridEventMove.spec.tsx
> +  it.each(cases)(
눈에 띄어서 변경
당장 이슈를 파서 모든 forEach 사용 테스트를 바꿀 필요는 없지만 눈에 띄면 바꿔주도록 하죠.

2022-04-06 00:15 UTC, jwlee1108 approved these changes
리뷰 완료합니다. 확실히 마우스 이벤트는 테스트도 복잡하네요 🤔

2022-04-06 00:15 UTC, jwlee1108 commented on apps/calendar/src/hooks/dayGridMonth/useDayGridMonthEventMove.ts
> +    if (isDraggingEnd) {
`shouldUpdate` 자체가 `isDraggingEnd`가 첫 조건인데 아래에서 추가로 분기 처리를 한 이유가 있을까요? 보이는 코드상으로는 `else` 라인도 따로 없어서요.

2022-04-06 00:15 UTC, jwlee1108 commented on apps/calendar/src/hooks/dayGridWeek/useAlldayGridRowEventMove.ts
> +    if (isDraggingEnd) {
여기도 조건절 중복 되는 느낌이네요.

2022-04-06 00:15 UTC, jwlee1108 commented on apps/calendar/src/hooks/dayGridWeek/useAlldayGridRowEventMove.ts
> +            start: newStartDate,
여기 `newStartDate.addDate(dateOffset)` 할당하면 `let` 키워드로 선언하고 재할당할 필요는 없을 것 같은데, 실제로 중요한 코드가 `updateEvent`고 여기에 선언적 스타일을 강조하고 싶다면 그냥 넘어가도 괜찮을 것 같아요.

2022-04-06 00:51 UTC, adhrinae commented on apps/calendar/src/hooks/dayGridMonth/useDayGridMonthEventMove.ts
> +    if (isDraggingEnd) {
마우스를 한 자리에서 클릭하는 것 만으로도 상태 초기화를 해주어야 하기 때문입니다.
한 자리 클릭, 드래깅은 했지만 위치 변경을 하지 않은 것 등 케이스를 거쳐 실제로 업데이트가 되어야 할 때는 업데이트를 하되 기본적으로 `clear~` 를 호출해서 상태를 초기화하고 있지요.

2022-04-06 00:54 UTC, adhrinae commented on apps/calendar/src/hooks/dayGridMonth/useDayGridMonthEventMove.ts
> +    if (isDraggingEnd) {
근데 질문하신 것 처럼 동작에 너무 많은 것을 알아야하고 깔끔하게 떨어지지 않는다는 느낌이 들어서 좀 더 추상화를 해보려고 머리를 굴리는데 쉽지 않네요.

2022-04-06 00:56 UTC, adhrinae commented on apps/calendar/src/hooks/dayGridWeek/useAlldayGridRowEventMove.ts
> +            start: newStartDate,
말씀하신대로 여기서는 재할당 스타일이 가독성 측면에서 조금 더 낫다고 생각합니다.

2022-04-06 05:06 UTC, dotaitch requested changes
리뷰 완료합니다. 아래 이슈도 확인 부탁드려요.

![bug_alldaygrid-select-then-click-event](https://user-images.githubusercontent.com/8615506/161899319-f47fa2b3-9902-4e72-b9dc-c614210515ca.gif)

제가 디버깅해보니 alldayGrid에서 select 이후 `clearCurrentGridPos()`가 실행되지 않는 게 문제예요. eventMove가 일어났을 때 `currentGridPos.columnIndex`가 select가 끝난 columnIndex로 되어 있어요.

2022-04-06 05:06 UTC, dotaitch commented on apps/calendar/src/hooks/timeGrid/useTimeGridEventMove.spec.tsx
> +  it.each(cases)(
이 함수를 깜박하고 있었네요;; 저도 보이는 대로 수정해두겠습니다.

2022-04-06 05:46 UTC, dotaitch commented on apps/calendar/src/hooks/event/useDraggingEvent.ts
> +    if (isPresent(draggingEvent) && isIdle) {
개인적으로 저는 이 방식이 더 마음에 드네요. 👍

2022-04-06 05:51 UTC, adhrinae commented on apps/calendar/src/hooks/dayGridMonth/useDayGridMonthEventMove.ts
> +    if (isDraggingEnd) {
지금은 `useWhen` 커스텀 훅을 통해서 `isDraggingEnd` 조건을 확인하도록 하면서 `shouldUpdate` 에서 뺐습니다.

2022-04-06 06:24 UTC, adhrinae commented on apps/calendar/src/hooks/timeGrid/useTimeGridEventResize.ts
> +      ) {
이 훅처럼 다양한 케이스에 따라 나누어 동작되어야하는 경우도 `useWhen` 을 써먹기 좋겠다고는 생각했는데, 조건 인자를 작성했음에도 타입 보장을 하려면 또 똑같은 if문이 들어가야해서 적용할까하다 포기했습니다.

그래도 적용했을 때 유의미한 차이가 있다면 불필요하게 이펙트 함수들이 동작하면서 자신의 조건이 맞는지 체크하는 일은 없다는 것 정도겠네요.

2022-04-06 06:40 UTC, lja1018 approved these changes
리뷰 완료합니다. 고생하셨습니다.

2022-04-06 06:40 UTC, lja1018 commented on apps/calendar/src/hooks/event/useDraggingEvent.ts
> +    if (isPresent(draggingEvent) && isIdle) {
저도 이 방식이 더 나은 것 같습니다.

2022-04-06 06:40 UTC, lja1018 commented on apps/calendar/src/hooks/timeGrid/useTimeGridEventResize.ts
> +import { useDraggingEvent } from '../event/useDraggingEvent';
path 수정해야할 것 같습니다.

2022-04-06 06:47 UTC, adhrinae commented on apps/calendar/src/hooks/timeGrid/useTimeGridEventResize.ts
> +import { useDraggingEvent } from '../event/useDraggingEvent';
요즘 간만에 VSCode 쓰다보니 요게 또... 설정을 이거 이후에 바꿨나보네요.

2022-04-06 07:10 UTC, adhrinae commented on apps/calendar/src/hooks/event/useDraggingEvent.ts
> +    if (isPresent(draggingEvent) && isIdle) {
흠... 그러면 모두 `useWhen` 사용보단 훅이 onEnd까지 차리하는게 낫다고 보시는거죠?

2022-04-07 00:11 UTC, dotaitch approved these changes
리뷰 완료합니다. 저는 `useWhen`이 더 깔끔해서 좋네요 👍 👍  고생 많으셨습니다~

2022-04-07 06:49 UTC, merged