feat: implement theme store
nhn/tui.calendar pull request #1075
Opened 2022-04-06 07:29 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- implement theme store (remove theme class)
- add `ts-essentials`
- add tests for theme store

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-04-07 01:00 UTC, jwlee1108 approved these changes
리뷰 완료합니다.

2022-04-07 05:15 UTC, dotaitch approved these changes
리뷰 완료합니다!

2022-04-07 05:15 UTC, dotaitch commented on apps/calendar/types/theme.d.ts
> +  borderBottom: string;
week에 borderTop이랑 borderBottom이 추가된 이유는 무엇인가요? 기존에는 month와 동일하게 borderLeft와 backgroundColor만 받은 것 같아서요.

2022-04-07 05:20 UTC, lja1018 commented on apps/calendar/types/theme.d.ts
> +  borderBottom: string;
일단 v1과 동일한 theme 옵션으로 가져가기 위해서 추가했습니다! month와 week이 `borderLeft`, `backgroundColor`만 사용하고 있었는데 v1을 보니 week은 `borderTop`, `borderBottom`도 받고 있더라구요.

2022-04-07 06:35 UTC, adhrinae requested changes
리뷰 완료합니다. `DeepPartial` 과 유사한 타입이 `utils/object.ts` 파일 안에 있으니 그것도 같이 교체해주세요.

2022-04-07 06:35 UTC, adhrinae commented on apps/calendar/src/theme/dispatch.spec.tsx
> +  }
어차피 테스트하는게 테마 값이긴 해도 스타일을 적용할때 쓰는거니까 `toHaveStyle` 단언을 쓰기 위해 div 태그 하나에 인라인 스타일을 주입하고 그걸 가지고 테스트해도 되지 않을까요?

https://github.com/testing-library/jest-dom#tohavestyle

2022-04-07 06:37 UTC, adhrinae commented on apps/calendar/src/factory/calendarControl.spec.tsx
> +  }
제가 Zustand 옮겨오면서 이 동작을 제외해서 그런거였네요. 그냥 조금만 수정하면 적용할 수 있을거같긴 한데 🤔

2022-04-07 06:59 UTC, lja1018 commented on apps/calendar/src/factory/calendarControl.spec.tsx
> +  }
넵 지금은 일단 셀렉터가 없으면 에러가 발생하게 되어있습니다!

2022-04-08 05:50 UTC, lja1018 commented on apps/calendar/src/factory/calendarControl.spec.tsx
> +  }
좀더 깊은 셀렉터를 사용하도록 수정했습니다.

2022-04-08 06:33 UTC, adhrinae requested changes
몇개 갸우뚱한 부분이 있는데 가볍게 확인해주세요.

2022-04-08 06:33 UTC, adhrinae commented on apps/calendar/src/hooks/dayGridWeek/useDayGridRowTitleStyle.spec.tsx
> +    setWeekThemeDispatcher = theme.getState().dispatch.setWeekTheme;
이건 굳이 이름이 `~Dispatcher` 로 바뀐 이유가 있나요?

2022-04-08 06:33 UTC, adhrinae commented on apps/calendar/src/components/timeGrid/currentTimeIndicator.tsx
> +  const color = useTheme(useCallback((theme) => theme.week.currentTime.color, []));
이 변수명은 `currentTimeColor` 가 아니라 `color` 가 되면 많이 축약된 느낌이 드네요.

2022-04-08 06:33 UTC, adhrinae commented on apps/calendar/src/contexts/themeStore.tsx
> +      ({ common, week, month }) => ({
`(theme) => theme` 면 되지 않나요?

2022-04-08 06:58 UTC, lja1018 commented on apps/calendar/src/hooks/dayGridWeek/useDayGridRowTitleStyle.spec.tsx
> +    setWeekThemeDispatcher = theme.getState().dispatch.setWeekTheme;
디스트럭쳐링하라는 eslint때문에 변수명을 살짝 변경했습니다.

2022-04-08 06:59 UTC, lja1018 commented on apps/calendar/src/components/timeGrid/currentTimeIndicator.tsx
> +  const color = useTheme(useCallback((theme) => theme.week.currentTime.color, []));
변경했습니다

2022-04-08 07:00 UTC, lja1018 commented on apps/calendar/src/contexts/themeStore.tsx
> +      ({ common, week, month }) => ({
`dispatch`를 제외하기 위해서 디스트럭쳐링해서 따로 내보냈습니다!

2022-04-08 07:07 UTC, adhrinae commented on apps/calendar/src/contexts/themeStore.tsx
> +      ({ common, week, month }) => ({
👌

2022-04-08 07:08 UTC, adhrinae approved these changes

2022-04-08 07:25 UTC, merged