feat: implement `calculateTimezoneOffset` function
nhn/tui.calendar pull request #1082
Opened 2022-04-13 13:20 UTC by adhrinae

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- Implemented a utility function to get timezone offset from the given timezone name.
  - the timezone name should be matched with the IANA timezone name.
- Also implemented another utility function to check whether given `Date` is using Daylight Saving Time in the target timezone.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-04-13 15:18 UTC, dotaitch requested changes
리뷰 완료합니다. 고생 많으셨어요

2022-04-13 15:18 UTC, dotaitch commented on apps/calendar/src/time/timezone.ts
> +      'tui-calendar: Intl.DateTimeFormat is not fully supported. So It will return local timezone offset only.\nYou can use polyfill to fix this issue.'
그리고 v2의 경우 `@toast-ui/calendar`로 배포되지 않나요? 만약 이렇게 배포된다면 `tui-calendar`도 `@toast-ui/calendar` 로 변경 부탁드려요!

2022-04-13 15:18 UTC, dotaitch commented on apps/calendar/src/time/timezone.ts
> +    Intl.DateTimeFormat('en-US', { timeZone: timezoneName });
`timezoneNameValidationCache`를 사용하는 이유가 있나요? 이 함수 실행이 오래 걸릴 것 같진 않아서요.

2022-04-13 15:18 UTC, dotaitch commented on apps/calendar/src/time/timezone.ts
> +    Intl.DateTimeFormat('en-US', { timeZone: timezoneName });
아래의 `dtfCache`도 마찬가지로 궁금합니다!

2022-04-14 01:54 UTC, adhrinae commented on apps/calendar/src/time/timezone.ts
> +      'tui-calendar: Intl.DateTimeFormat is not fully supported. So It will return local timezone offset only.\nYou can use polyfill to fix this issue.'
네 약간 실험적으로 넣은거긴 한데 손을 좀 볼게요.
특히 저런 메세지 띄워주는건 `logger` 같은 모듈을 정의하는게 나을거고, 에러 던지는것도 비슷한 함수를 만드는게 나을거라는 생각이 듭니다.

2022-04-14 01:58 UTC, adhrinae commented on apps/calendar/src/time/timezone.ts
> +    Intl.DateTimeFormat('en-US', { timeZone: timezoneName });
이런 방식의 캐싱은 date-fns-tz 패키지에서 활용되고 있길래 차용했습니다. 

https://github.com/marnusw/date-fns-tz/blob/ab13900b2994d9c6fdaf29b86e70355b9037664d/src/_lib/tzTokenizeDate/index.js#L50
https://github.com/marnusw/date-fns-tz/blob/ab13900b2994d9c6fdaf29b86e70355b9037664d/src/_lib/tzParseTimezone/index.js#L136

제 나름의 이유를 덧붙이자면, 실행이 오래 걸리지 않지만 같은 동작이 무수히 많이 호출될것이기 때문에 캐싱을 하는게 명확하게 이득이 될 부분이라고 생각합니다. 가령 Primary 타임존을 바꾸도록 설정했을 경우 거의 대부분의 `TZDate` 인스턴스에 타임존 오프셋을 계산하는 함수가 호출될텐데 그때마다 새로이 `Intl.DateTimeFormat` 인스턴스를 만드는게 비효율적으로 보여서요.

2022-04-14 02:09 UTC, adhrinae commented on apps/calendar/src/time/timezone.ts
> +    Intl.DateTimeFormat('en-US', { timeZone: timezoneName });
추가로 의견을 모아보고 싶은게, 저는 단순히 Key-Value 형태의 자료구조를 쓸 때는 `Map` 을 좀더 선호하는 경향이 
 있는데 이정도면 리터럴 객체로 캐싱을 해도 별로 상관은 없을 것 같아요. 값을 저장만 하고 추가 변경이 일어날 일이 적은덷, 객체를 쓰는 편이 더 직관적이기도 하고요.

Map이 객체보다 확실히 나은 점이 있다면 기본적으로 이터러블하다는 것과 크기를 바로 알 수 있는 객체라는 점, 그리고 삭제 등의 동작이 객체보다 훨씬 빠르다는 것이라 볼 수 있습니다. 그런데 지금같은 형태의 캐시에 사용하기엔 약간 오버킬이 될 수 있겠네요. 다른 분들의 생각이 궁금해요.

2022-04-14 03:16 UTC, lja1018 commented on apps/calendar/src/time/timezone.ts
> +    Intl.DateTimeFormat('en-US', { timeZone: timezoneName });
저도 단순히 값의 저장+호출 용도가 대부분이라면 객체 리터럴로 해도 충분할 것 같습니다!

2022-04-14 05:11 UTC, lja1018 reviewed
리뷰 완료합니다.

2022-04-14 05:11 UTC, lja1018 commented on apps/calendar/src/time/timezone.ts
> +    return dtfCache.get(timezoneName) as Intl.DateTimeFormat;
~~타입 단언 없어도 될 것 같습니다.~~
`has`로 체크해도 `undefined`가 될 수 있네요. 아쉽습니다.

2022-04-14 05:43 UTC, adhrinae commented on apps/calendar/src/time/timezone.ts
> +    return dtfCache.get(timezoneName) as Intl.DateTimeFormat;
네 이것도 거슬리는 포인트라 일반 객체로 바꾸는게 더 나을 수 있겠네요.

2022-04-15 02:08 UTC, dotaitch commented on apps/calendar/src/time/timezone.ts
> +    Intl.DateTimeFormat('en-US', { timeZone: timezoneName });
저도 `Map`을 선호하긴 한데, 말씀하신대로 지금은 값을 저장하기만 하고 변경이 거의 없다보니 객체 리터럴을 사용해도 될 것 같아요. 그리고 객체 리터럴을 사용한다면 [아래 댓글에서 언급한 타입 관련 아쉬운 점](https://github.com/nhn/tui.calendar/pull/1082/files/12e31ed3628709ffbd5ebaa5839075b487be89b6#r850087390)을 해결할 수 있어서 지금 상황에서는 객체 리터럴이 더 편리할 것 같아요.

2022-04-18 07:24 UTC, lja1018 approved these changes
리뷰 완료합니다. 고생하셨습니다.

2022-04-18 08:19 UTC, dotaitch approved these changes

2022-04-19 01:27 UTC, merged