feat: implement gridSelection.enableDblClick and gridSelection.enableClick options
nhn/tui.calendar pull request #1090
Opened 2022-04-21 10:59 UTC by dotaitch

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has description for the breaking change

### Description

* [BREAKING CHANGE] disableDblClick and disableClick options are
deprecated.
  * Instead, use `gridSelection.enableDblClick` and `gridSelection.enableClick`.
  ```js
  const options = {
    // disableDblClick: true, // deprecated
    // disableClick: true, // deprecated
    gridSelection: {
      enableDblClick: false,
      enableClick: false
    }
  }
  ```
* Implement `gridSelection.enableDblClick` and `gridSelection.enableClick`.
* Fix to show a creationPopup only once when double clicking.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-04-21 11:07 UTC, dotaitch commented on apps/calendar/src/hooks/gridSelection/useGridSelection.ts
> +    delay: 250, // heuristic value
v1에서는 [delay 값으로 `300ms`](https://github.com/nhn/tui.calendar/blob/master/src/js/handler/time/creation.js#L17)를 사용하고 있으며, [더블클릭과 클릭을 구분해야 할 때만 사용](https://github.com/nhn/tui.calendar/blob/master/src/js/handler/time/creation.js#L83)하고 있음.

2022-04-22 05:41 UTC, lja1018 approved these changes
리뷰 완료합니다.

2022-04-22 05:41 UTC, lja1018 commented on apps/calendar/index.d.ts
> +export interface IGridSelectionOptions {
나중에 `I` 프리픽스도 제거했으면 좋겠네요...

2022-04-22 05:41 UTC, lja1018 commented on apps/calendar/src/hooks/common/useClickPrevention.spec.tsx
> +    jest.useFakeTimers();
이부분도 아까 얘기 나눴던데로 `useRealTimers` 호출이 필요하겠네요.

2022-04-22 05:41 UTC, lja1018 commented on apps/calendar/src/hooks/gridSelection/useGridSelection.ts
> +  let isDragEvent = false;
아까 얘기 나눴던데로 ref로 변경되어야겠네요.

2022-04-22 05:41 UTC, lja1018 commented on apps/calendar/src/slices/options.ts
> +    options = {};
파라미터에 재할당하는 것보단 따로 변수로 선언해서 사용하는게 좋을 것 같습니다.

2022-04-22 05:41 UTC, lja1018 commented on apps/calendar/src/utils/requestTimeout.spec.ts
> +    expect(fn).not.toHaveBeenCalled();
여기까지 `Given`이여도 되지 않을까요?

2022-04-22 05:47 UTC, dotaitch commented on apps/calendar/index.d.ts
> +export interface IGridSelectionOptions {
사실 이 파일은 더 이상 필요 없어질텐데 혹시 몰라서 추가는 해두었어요.

2022-04-22 05:48 UTC, dotaitch commented on apps/calendar/src/hooks/gridSelection/useGridSelection.ts
> +  let isDragEvent = false;
ref말고 `onMouseUp`의 두번째 인자 사용하는 것으로 변경할 예정입니다~

2022-04-22 06:06 UTC, adhrinae requested changes
리뷰 완료합니다.

2022-04-22 06:06 UTC, adhrinae commented on apps/calendar/src/utils/requestTimeout.ts
> +    const delta = new Date().getTime() - start;
제가 이전에 `performance.now` 에 대해 언급한 적이 있을거에요. 가급적이면 그걸로 대체되는게 좋고요.

`new Date().getTime() === Date.now()` 이기도 합니다.

그리고 궁극적으로 둘 다 쓸 필요 없을거같은게 rAF에 인자로 넘기는 콜백은 기본적으로 타임스탬프를 패러매터로 받습니다.

https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame#parameters (Example도 참고)

https://codepen.io/rinae/pen/MWrRYXy

2022-04-22 06:13 UTC, dotaitch commented on apps/calendar/src/hooks/gridSelection/useGridSelection.spec.tsx
> +      it(`should return grid selection data when just mousedown and mousemove at (${initX}, ${initY})`, () => {
drop은 안하고 mousedown -> mousemove 까지만 했을 때 gridSelection이 그려지는 지를 확인하는 테스트라서 입니다. `dragAndDrop` 함수 옵션으로 `hold: true`를 넘기고 있어요

2022-04-22 06:17 UTC, dotaitch commented on apps/calendar/src/hooks/common/useClickPrevention.ts
> +  onClick: Function;
`onClick`과 `onDblClick`의 함수 타입을 유연하게 하고 싶어서 `Function` 타입을 사용한 것이었는데, 생각해보니 이벤트 핸들러니까 굳이 유연하게 할 필요가 없겠네요. `(e: MouseEvent) => void`로 수정하겠습니다.

2022-04-22 06:20 UTC, dotaitch commented on apps/calendar/src/hooks/gridSelection/useGridSelection.spec.tsx
> +      it(`should return grid selection data when just mousedown and mousemove at (${initX}, ${initY})`, () => {
[이 부분](https://github.com/nhn/tui.calendar/pull/1090/files/0d418ae82cd30141c4d86cac0bbc9d8ef605cf27#diff-a9ae927acbb48328d20c7e3dc451444dee8491a85872f871c0ab7778ab134fd9R170-R174)을 테스트하는 코드예요.

2022-04-22 06:26 UTC, adhrinae commented on apps/calendar/src/hooks/gridSelection/useGridSelection.spec.tsx
> +      it(`should return grid selection data when just mousedown and mousemove at (${initX}, ${initY})`, () => {
제가 `hold: true` 옵션을 못봤네요.

2022-04-25 02:02 UTC, adhrinae approved these changes

2022-04-25 02:02 UTC, adhrinae commented on apps/calendar/src/slices/options.ts
> +      enableClick: options,
오 똑똑한 해결책으로 보이네요 👍

2022-04-25 02:31 UTC, merged