feat: implement week.eventView and week.taskView options
nhn/tui.calendar pull request #1091
Opened 2022-04-26 01:47 UTC by dotaitch

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has description for the breaking change

### Description

* [BREAKING CHANGE] `scheduleView` and `taskView` options are deprecated.
  * Instead, use `week.eventView` and `week.taskView`.
  ```js
  const options = {
    // scheduleView: true, // deprecated
    // taskView: true, // deprecated
    week: {
      eventView: true, // set by a boolean value
      taskView: ['milestone', 'task'] // or array
    }
  };
  ```
  * The default values of `week.eventView` and `week.taskView` are `true`.
* Implement `week.eventView` and `week.taskView`.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-04-26 07:55 UTC, lja1018 approved these changes
리뷰 완료합니다. 고생하셨습니다!

2022-04-26 07:55 UTC, lja1018 commented on apps/calendar/src/components/panel.tsx
> +
```suggestion
  const isResizable = useMemo(() => {
    if (isNil(resizable) || isBoolean(resizable)) {
      return !!resizable;
    }

    return resizable.includes(name);
  }, [resizable, name]);
```
`useMemo`로 감싸서 변수화하는건 어떨까요?

2022-04-26 07:55 UTC, lja1018 commented on apps/calendar/src/components/view/day.spec.tsx
> +      it(`show/hide the panels in the daily view: { eventView: ${weekOptions.eventView}, taskView: ${weekOptions.taskView} }`, () => {
사소하지만 `should`가 붙었으면 좋겠습니다 ㅋㅋ..

2022-04-26 07:55 UTC, lja1018 commented on apps/calendar/src/components/view/day.spec.tsx
> +        }
질문입니다! `.forEach()`가 아니라 `for...of`를 사용하신 이유가 있을까요?

2022-04-26 09:32 UTC, adhrinae requested changes
리뷰 완료합니다.

2022-04-26 09:32 UTC, adhrinae commented on apps/calendar/playwright/day/timeGridEventMoving.e2e.ts
> -import waitForExpect from 'wait-for-expect';
이걸 import 해놓고 깜빡한거보니까 단언부분에 감싸줬으면 실패할 일이 더 적어졌으려나 하는 생각도 드네요.

2022-04-26 09:32 UTC, adhrinae commented on apps/calendar/src/components/panel.tsx
> +
네 요건 `useMemo` 쓰는게 더 적절해보이네요.

2022-04-26 09:32 UTC, adhrinae commented on apps/calendar/src/components/view/day.spec.tsx
> +  }
`render` 함수를 `@src/test/utils` 에서 가져오면 이미 프로바이더가 래핑되어있습니다.

2022-04-26 09:32 UTC, adhrinae commented on apps/calendar/src/components/view/day.spec.tsx
> +      it(`show/hide the panels in the daily view: { eventView: ${weekOptions.eventView}, taskView: ${weekOptions.taskView} }`, () => {
+1

2022-04-26 09:32 UTC, adhrinae commented on apps/calendar/src/components/view/day.spec.tsx
> +    cases.forEach((weekOptions) => {
요건 `it.each` 사용하지 않은 이유가 있나요?

2022-04-26 09:32 UTC, adhrinae commented on apps/calendar/src/components/view/week.spec.tsx
> +    function getExpectedResult({ eventView, taskView }: WeekOptions) {
헬퍼 함수같은거로 만들어서 컴포넌트 안에서 써도 될법한 동작으로 보이네요.

주어진 옵션에 따라 어떤 패널을 표시해야할지 결정하는 함수니까요.

2022-04-26 09:32 UTC, adhrinae commented on apps/calendar/types/options.d.ts
> +type taskViewValue = 'milestone' | 'task';
- 타입은 대문자로 시작해주세요
- `EventView`, `TaskView` 로 하면 충돌나는 타입이 있나요? 아니라면 `EventViewType` 이런식으로 해도 될거같은데요.

2022-04-26 09:58 UTC, jwlee1108 reviewed
리뷰 완료합니다. 디테일하게 보지는 못하겠네요 ㅠ 죄송합니다.

2022-04-27 01:23 UTC, dotaitch commented on apps/calendar/src/components/view/day.spec.tsx
> +        }
따로 이유는 없습니다. `forEach`가 더 나은 이유가 있나요?

2022-04-27 01:54 UTC, adhrinae commented on apps/calendar/src/components/view/day.spec.tsx
> +        }
지금 정도의 코드는 별로 차이가 없지요. 어차피 팀 단위로 바짝 선언적인 코드 작성에 매몰되어 있는게 아니라면 언제나 `forEach` 를 쓸 필요는 없다고 생각합니다.

2022-04-27 01:54 UTC, dotaitch commented on apps/calendar/src/components/view/day.spec.tsx
> +    cases.forEach((weekOptions) => {
`it.each`를 썼을 때 타입 추론이 잘 되지 않는 것 같아서 `cases.forEach`로 변경했었는데, 다시 확인해보니 제가 사용 방법을 잘못 알고 있었네요;; `it.each`로 변경할게요.

2022-04-27 04:35 UTC, dotaitch commented on apps/calendar/src/components/view/week.spec.tsx
> +    function getExpectedResult({ eventView, taskView }: WeekOptions) {
컴포넌트 내부에 비슷한 로직을 찾아보니([참고](https://github.com/nhn/tui.calendar/pull/1091/files/0887d5e319a462bd12e50c37438ce4ef93bbc37d#diff-e05a078f6a195bf9ee7ce0c813fb0796d29d76c1b1da31d37a10a6e9e7478402R84)) 오히려 제가 만든 `getExpectedResult`를 제거하고 테스트 파일에서 `getDisplayPanel` 라는 헬퍼 함수를 사용하는게 더 낫겠더라구요. 그래서 이 헬퍼 함수를 사용하도록 수정할 예정입니다.

2022-04-28 03:05 UTC, dotaitch commented
@adhrinae 리뷰 반영했습니다. 리팩토링한 부분도 있어서 다시 리뷰 부탁드려요~

2022-04-28 05:06 UTC, adhrinae requested changes
어제 깃헙 모바일 앱으로 바로 코멘트 달려고 했는데 안되더라고요. 늦게나마 추가 리뷰 남깁니다.

2022-04-28 05:06 UTC, adhrinae commented on apps/calendar/src/components/view/week.spec.tsx
>      });
`initCalendarStore` 가 옵션을 인자로 받기 때문에 번거롭게 디스패치를 호출하지 않아도 됩니다. 함수 호출 시 옵션을 넣어주면 되겠네요.

2022-04-28 05:06 UTC, adhrinae commented on apps/calendar/src/components/view/week.tsx
> +      {activePanels.includes('time') ? (
컴포넌트 리렌더마다 `activePanel` 배열을 순회하게 되는 것 치고, 그리 동적으로 변하지 않는 값이니까 이것도 `useMemo` 로 캐싱하면 좋겠네요.

2022-04-29 00:26 UTC, adhrinae approved these changes

2022-04-29 03:15 UTC, merged