feat: implement usageStatistics option
nhn/tui.calendar pull request #1100
Opened 2022-05-03 03:21 UTC by dotaitch

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has description for the breaking change

### Description

* Implement the `usageStatistics` option.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-05-03 04:39 UTC, jwlee1108 approved these changes
리뷰 완료합니다.

2022-05-03 04:39 UTC, jwlee1108 commented on apps/calendar/src/factory/calendarControl.tsx
> +    if (initOptions.usageStatistics === true) {
`usageStatistics`는 타입이 이미 `boolean`일 것 같은데 혹시 `=== true`로 비교할 케이스가 있나요? 의미를 조금 더 잘 주고 싶다는 뜻이었으면 넘기셔두 괜찮습니다.

2022-05-03 04:44 UTC, dotaitch commented on apps/calendar/src/factory/calendarControl.tsx
> +    if (initOptions.usageStatistics === true) {
boolean이긴 하지만 혹시나 truthy 값이 들어왔을 때 `usageStatistics`이 동작하지 않게끔 하기 위해서 이렇게 처리했습니다. `usageStatistics`은 개인 정보 관련 문제가 있어서 특히나 더 엄격하게 확인해야 한다고 생각해서요.

2022-05-03 04:47 UTC, adhrinae commented on apps/calendar/src/factory/calendarControl.tsx
> +    if (initOptions.usageStatistics === true) {
사용자가 생각 외로 기대하지 않은 값을 넣을 때가 많으니까 저는 찬성이에요.

2022-05-03 04:52 UTC, adhrinae requested changes
제가 환경변수에 대해 언급한거만 조금 조사/실험해주고 알려주셨으면 좋겠어요. 이전에 리액트 프로젝트 할때는 비슷하게 했었거든요.

2022-05-03 04:52 UTC, adhrinae commented on apps/calendar/src/constants/statistics.ts
> +export const GA_TRACKING_ID = 'UA-129951699-1';
이게 그렇게 치명적인 정보는 아니긴 한데... 🤔 그렇다고 소스코드에 떡하니 박아두고 싶진 않아서 고민되네요.

저라면 이 변수를 환경변수로 할당하고 소스코드가 `process.env.GA_TRACKING_ID` 처럼 환경변수를 사용하도록만 해둔 뒤에, 웹팩을 통해 빌드를 할 때 지정한 환경변수를 조회하고 값으로 치환하여 빌드가 되도록 했으면 좋겠다는 생각이 드네요.

의도대로 구현할 수 있는지는 추가 조사가 필요하긴 하지만요.

2022-05-03 04:52 UTC, adhrinae commented on apps/calendar/src/factory/calendarControl.tsx
> +      usageStatistics = true,
`initOptions` 는 없애버릴 예정이에요. option slice의 기본 값으로 만들어주세요.

2022-05-03 07:59 UTC, dotaitch commented on apps/calendar/src/factory/calendarControl.tsx
> +      usageStatistics = true,
optionSlice에는 이미 기본값 처리가 되어있습니다. ([참고](https://github.com/nhn/tui.calendar/blob/next/apps/calendar/src/slices/options.ts#L113))

2022-05-03 08:50 UTC, lja1018 approved these changes
리뷰 완료합니다.

2022-05-04 00:59 UTC, adhrinae commented on apps/calendar/src/constants/statistics.ts
> +export const GA_TRACKING_ID = 'UA-129951699-1';
https://webpack.js.org/plugins/define-plugin/

DefinePlugin을 설정하고, 거기에 `process.env.GA_TRACKING_ID` 의 값을 빌드타임 환경변수에서 쓰도록 만들면 되겠습니다. 간략한 구현 방법은 페어로 전달할게요.

2022-05-04 02:15 UTC, adhrinae commented on apps/calendar/src/constants/statistics.ts
> +export const GA_TRACKING_ID = 'UA-129951699-1';
현재 구현체로 가고, 빌드 시 환경변수를 활용하는 방안은 전체 제품군에서 고려되는게 좋기 때문에 팀 안에서 추가 논의하기로 합의.

2022-05-04 02:15 UTC, adhrinae approved these changes

2022-05-04 02:18 UTC, merged