feat: apply primary timezone option
nhn/tui.calendar pull request #1101
Opened 2022-05-03 10:19 UTC by adhrinae

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has description for the breaking change

### Description

- Implemented the primary timezone option
  - Now users can set their primary timezone on the calendar through `options.timezone.zones[0]`.
  - It calculates the difference between the system's timezone and the given timezone value and applies to the view only.
- To change the timezone value, `TZDate#tz` and `TZDate#local` are implemented.
- Fixed missing points of the `calculateTimezoneOffset` function.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-05-03 10:20 UTC, adhrinae commented on apps/calendar/src/components/timeGrid/multipleTimezones.tsx
> +// @ts-nocheck
스토리북 + 테스트 도입하다가 들어간 흔적인데, 이 컴포넌트는 현재 아무데도 쓰이지 않으면서 TimeColumn으로 대체되기 전까지 로직 참고용으로 살려둔거니까 무시하셔도 됩니다.

2022-05-03 10:21 UTC, adhrinae commented on apps/calendar/src/factory/calendarControl.spec.tsx
> +        await waitFor(() => expect(screen.queryByText(`date: ${date}`)).not.toBeInTheDocument());
로컬에서 테스트가 실패하길래 적용했습니다.

2022-05-03 10:21 UTC, adhrinae commented on apps/calendar/src/factory/calendarControl.tsx
> -  private initOptions(options: Options = {}): Options {
`initOptions` 는 스토어를 본격적으로 도입하기 전에 남아있던 녀석인데, 이제 스토어 생성 시 옵션 슬라이스에서 기본값을 넣어 생성하기로 했으니 필요가 없어졌습니다.

2022-05-03 10:22 UTC, adhrinae commented on apps/calendar/src/factory/month.spec.tsx
> +    jest.spyOn(Element.prototype, 'getBoundingClientRect').mockImplementation(() => ({
다른 방식으로 적용을 해보고싶긴 했는데 딱히 방법이 떠오르지 않더라고요. 이렇게 하지 않으면 초기 렌더링 시 월간 뷰의 이벤트가 아무것도 보이지 않는 문제가 있습니다.

2022-05-03 10:23 UTC, adhrinae commented on apps/calendar/src/hooks/timezone/useEventsWithTimezone.ts
> +          )
사용자가 `cutstomOffsetCalculator` 를 사용하는 경우 거기서 계산된 값을 반영합니다.

2022-05-03 10:24 UTC, adhrinae commented on apps/calendar/src/slices/view.spec.ts
> -    expect(view.currentView).toBe('month');
뭔가 변경사항이 제대로 반영되지 않아 테스트가 실패하던 부분.

2022-05-03 10:25 UTC, adhrinae commented on apps/calendar/src/time/date.ts
> +  local(tzValue?: string | number) {
일종의 보험으로 `tzOffset` 값을 넣어놓긴 했는데 `local` 을 호출하는 상황에서는 보통 `tzOffset` 값이 없는 경우가 많더라고요. 해당 `TZDate` 인스턴스를 직접 쓰는게 아니다보니... 그래서 별도로 관련 정보를 받아서 환산할 수 있도록 만들었습니다. 이 메서드는 지금 바로 쓰이지 않고, 일정 이동 등을 할 때 환산해주기 위한 용도로 먼저 만들었습니다.

2022-05-05 18:03 UTC, dcookie75 commented
Hi there @adhrinae - we are looking to use this tool for one of our customers.  I see you are an active contributor and I was wondering if you are open to possibly answering some questions related to how to implement some needed changes.  For example, we will need to override the task edit form and suppress the "new task" function. 
Looking forward to hearing back from you, thanks!!

2022-05-06 00:15 UTC, adhrinae commented
@dcookie75 
Please use the discussion tab if you want to leave questions.
You can find the answer to most of your questions in the issue & discussion tabs.
But as a short tip, You need to disable the `useCreationPopup` option and implement your own popup to achieve what you want.

For more info, see #941.

2022-05-06 05:58 UTC, dotaitch requested changes
리뷰 완료합니다. 고생 많으셨어요

2022-05-06 05:58 UTC, dotaitch commented on apps/calendar/playwright/week/primaryTimezone.e2e.ts
> +  test(`${mockEvent.title} should be rendered at the top of the time grid in Pakistan Standard Time`, async ({
지금 `mockEvent`로 필터링된 이벤트의 경우에만 top에 렌더링되어야 하는 것이고, 실제로는 -4시간이 되는지 확인해야 하는 테스트라고 생각해요. 제 생각에는 파키스탄 시간대 offset을 상수로 정의한 후 `mockEvent.start`에서 계산한 값을 사용하는게 더 좋을 것 같습니다.

2022-05-06 05:58 UTC, dotaitch commented on apps/calendar/playwright/week/primaryTimezone.e2e.ts
> +  test(`${mockEvent.title} should be rendered at the top of the time grid in Pakistan Standard Time`, async ({
이에 맞게 테스트 설명과 assertion도 바뀌면 좋을 것 같아요.

2022-05-06 05:58 UTC, dotaitch commented on apps/calendar/src/factory/month.spec.tsx
> +    jest.spyOn(Element.prototype, 'getBoundingClientRect').mockImplementation(() => ({
month에서 일정이 제대로 그려지는지를 확인하지 않고 instace method로 확인할 수 있으면 좋을 것 같아요. 예를 들면 `monthInstance.getEvent(...).getTime()` 같은 걸 이용해서요.

2022-05-06 06:02 UTC, adhrinae commented on apps/calendar/playwright/week/primaryTimezone.e2e.ts
> +  test(`${mockEvent.title} should be rendered at the top of the time grid in Pakistan Standard Time`, async ({
🙆‍♂️ 현재 시점에서 Playwright 테스트는 의미가 없어서 빼버릴까 싶기도 한데 코멘트 남겨주신거 기반으로 고민을 해 볼게요.

2022-05-06 06:03 UTC, adhrinae commented on apps/calendar/src/factory/month.spec.tsx
> +    jest.spyOn(Element.prototype, 'getBoundingClientRect').mockImplementation(() => ({
그렇게하면 세부 구현에 의존적인 단위 테스트가 되어버리는 것 같아 약간 마음에 걸리네요.

2022-05-06 06:05 UTC, lja1018 approved these changes
리뷰 완료합니다. 고생하셨습니다!

2022-05-06 06:05 UTC, lja1018 commented on apps/calendar/src/time/date.ts
> +    return new TZDate(this.getTime());
```suggestion
const tzOffset = getTZOffsetMSDifference(this.tzOffset);

return new TZDate(this.getTime() + (isPresent(this.tzOffset) ? tzOffset : 0));
```
는 어떠신가요?

2022-05-06 06:05 UTC, lja1018 commented on apps/calendar/src/utils/collection.ts
> +      result[key] ??= new Collection<ItemType>(this.getItemID);
👍

2022-05-06 07:29 UTC, adhrinae commented on apps/calendar/src/factory/month.spec.tsx
> +    jest.spyOn(Element.prototype, 'getBoundingClientRect').mockImplementation(() => ({
이 부분은 지금의 테스트 방식을 유지해보겠습니다. 나중에 다른 방식으로 문제가 드러나면 다시 고민해보죠.

2022-05-06 07:30 UTC, merged