feat: apply grid template for week
nhn/tui.calendar pull request #1112
Opened 2022-05-16 22:59 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- apply week grid template

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-05-17 09:01 UTC, adhrinae requested changes
리뷰 완료합니다.

2022-05-17 09:01 UTC, adhrinae commented on apps/calendar/src/template/default.tsx
> +    return <i className={className} />;
여기에 `i` 태그가 사용된 이유가 있나요? 아이콘 용도로 그렇게 활용을 하려고 한거같은데 부트스트랩과 폰트어썸이 잘못 만든 생태계라고 생각합니다. 요즘은 그래도 `span` 태그 사용을 옵셔널로 안내하고 있긴 하네요.

https://fontawesome.com/docs/web/add-icons/how-to#add-icons-to-html

그리고 클래스 이름도 차라리 `collapse-btn-icon` 으로 바뀌는게 나을거같네요.

2022-05-18 01:34 UTC, lja1018 commented on apps/calendar/src/template/default.tsx
> +    return <i className={className} />;
`span` 태그로 수정하고 클래스명 변경했습니다.

2022-05-18 02:17 UTC, adhrinae approved these changes
리뷰 완료합니다.

2022-05-18 02:17 UTC, adhrinae commented on apps/calendar/src/components/dayGridWeek/gridCell.tsx
> +      <Template template="collapseBtnTitle" model="collapse" />
어차피 아무 Prop도 안쓰는데 `model` 속성이 반드시 들어가야해서 넣은건가요?

2022-05-18 03:12 UTC, dotaitch approved these changes

2022-05-18 05:56 UTC, lja1018 commented on apps/calendar/src/components/dayGridWeek/gridCell.tsx
> +      <Template template="collapseBtnTitle" model="collapse" />
네 일단 model 속성이 필요해서 넣었습니다.

2022-05-18 06:15 UTC, adhrinae commented on apps/calendar/src/components/dayGridWeek/gridCell.tsx
> +      <Template template="collapseBtnTitle" model="collapse" />
네 그럼 일단 이대로 하죠

2022-05-18 06:49 UTC, lja1018 commented on apps/calendar/src/components/dayGridWeek/gridCell.tsx
> +      <Template template="collapseBtnTitle" model="collapse" />
넵 문자열만 넘기는 경우가 몇군데 더 있어서 `Template` 컴포넌트에 주석으로 남겼습니다.

2022-05-18 07:16 UTC, merged

2022-05-18 09:02 UTC, dotaitch commented on apps/calendar/src/components/dayGridWeek/gridCell.tsx
> +      <Template template="collapseBtnTitle" model="collapse" />
template Props에서 `model`을 optional로 처리하면 안되는 이유가 있나요?? model이 필요한 경우가 있고 필요하지 않은 경우가 있다면 그냥 optional로 처리해도 될 것 같아서요. 
* 참고: https://github.com/nhn/tui.calendar/pull/1112/files#diff-9d60d39a9037538f85d3cf07f06a516cc1851e439d2025df71b22ba82bc84b51R12