docs: template docs
nhn/tui.calendar pull request #1122
Opened 2022-05-20 07:20 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- add template API docs

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-05-20 07:50 UTC, lja1018 commented on apps/calendar/src/components/dayGridWeek/gridCell.tsx
> +    <span className={cls('weekday-exceed-in-week')} onClick={clickExceedCount} style={style}>
이전에 템플릿 적용했던 부분이나 다른 PR에서 revert 되어 다시 추가.

2022-05-20 07:50 UTC, lja1018 commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +| [milestone](#milestone)                                   | EventModel              | milestone 이벤트                                                 |
각 링크 정상 동작 확인 완료

2022-05-24 02:00 UTC, lja1018 commented on apps/calendar/src/components/dayGridWeek/gridCell.tsx
> +    <span className={cls('weekday-exceed-in-week')} onClick={clickExceedCount} style={style}>
`next`에 머지된 PR에 이미 적용되어 있어 다시 revert

2022-05-24 02:09 UTC, adhrinae approved these changes

2022-05-25 00:21 UTC, dotaitch requested changes
리뷰 완료합니다. 중복되는 리뷰는 여러 번 적지 않았으니 이 부분 신경써서 수정 부탁드려요~

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +### milestone 관련
```suggestion
### milestone 패널
```

`관련`이라는 단어가 조금 애매하다고 생각되어서요. 어차피 아래에서 `패널`이라는 단어를 쓰고 있으니 이렇게 수정해도 좋을 것 같아요.

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +### task 관련
```suggestion
### task 패널
```

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +### allday 관련
```suggestion
### allday 패널
```

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +### time 관련
```suggestion
### time 이벤트
```

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +### 월간뷰의 더보기 팝업 관련
```suggestion
### 월간뷰의 더보기 팝업
```

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +더 보기 팝업의 닫기 버튼을 커스터마이징할 수 있다. 기본 값이 빈 문자열을 반환하기 때문에 기본적으로는 닫기 버튼이 표시되지 않는다.
```suggestion
더 보기 팝업의 닫기 버튼을 커스터마이징할 수 있다. 기본적으로는 닫기 버튼이 표시되지 않는다.
```

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +| [monthGridHeader](#monthgridheader)                       | TemplateMonthGrid       | 월간뷰의 각 셀의 헤더의 날짜                                     |
푸터도 마찬가지 입니다~

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +### 월간뷰의 header, footer 관련
```suggestion
### 월간뷰의 header, footer 영역
```

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +월간뷰 각 셀의 헤더의 날짜를 커스터마이징할 수 있다. `TemplateMonthGrid` 객체를 파라미터로 받는다.
```suggestion
월간뷰 각 셀의 헤더 영역을 커스터마이징할 수 있다. `TemplateMonthGrid` 객체를 파라미터로 받는다.
```

앞서 말씀드렸듯이 날짜 뿐만 아니라 다른 정보들도 표시할 수 있으니까 `영역`이라는 단어가 더 적절한 것 같아요.

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +월간뷰 각 셀의 푸터의 날짜를 커스터마이징할 수 있다. `TemplateMonthGrid` 객체를 파라미터로 받는다.
```suggestion
월간뷰 각 셀의 푸터 영역을 커스터마이징할 수 있다. `TemplateMonthGrid` 객체를 파라미터로 받는다.
```

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +}
```suggestion
interface TemplateMonthGrid {
  date: string; // 해당 날짜의 일
  day: number; // 해당 요일
  hiddenEventCount: number; // 표시되지 않은 이벤트의 갯수
  isOtherMonth: boolean; // 현재 월간뷰의 달과 다른 달의 날짜인지 여부
  isToday: boolean; // 오늘 날짜인지 여부
  month: number; // 해당 월
  ymd: string; // 해당 날짜의 `YYYY-MM-DD` 문자열 형식 데이터
}
```

`TemplateMonthGrid`의 프로퍼티 설명이 각 옵션 아래에 적혀 있더라구요. 인터페이스에서 설명해주면 같은 설명을 중복해서 적지 않아도 되고, 줄글이 아니라서 좀 더 읽기 편할 것 같아요.

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +}
만약 이렇게 수정한다면 다른 옵션의 파라미터 인터페이스도 수정 부탁들려요~

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +기본 값이 빈 문자열을 반환하기 때문에 따로 설정하지 않는다면 표시되지 않는다.
```suggestion
기본적으로는 아무 것도 표시되지 않는다.
```

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +기본 값이 빈 문자열을 반환하기 때문에 따로 설정하지 않는다면 표시되지 않는다.
```suggestion
기본적으로는 아무 것도 표시되지 않는다.
```

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +#### titlePlaceholder
placeholder와 관련된 옵션의 경우 결과값이 무조건 문자열이어야 해요. 이 부분도 문서에서 언급 부탁드립니다~

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +이벤트 생성 팝업에서 save 버튼의 텍스트를 커스터마이징할 수 있다.
```suggestion
이벤트 생성 팝업에서 저장 버튼의 텍스트를 커스터마이징할 수 있다.
```

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +이벤트 수정 팝업에서 update 버튼의 텍스트를 커스터마이징할 수 있다.
```suggestion
이벤트 수정 팝업에서 수정 버튼의 텍스트를 커스터마이징할 수 있다.
```

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +이벤트 상세 팝업에서 edit 버튼의 텍스트를 커스터마이징할 수 있다.
```suggestion
이벤트 상세 팝업에서 편집 버튼의 텍스트를 커스터마이징할 수 있다.
```

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +이벤트 상세 팝업에서 delete 버튼의 텍스트를 커스터마이징할 수 있다.
```suggestion
이벤트 상세 팝업에서 삭제 버튼의 텍스트를 커스터마이징할 수 있다.
```

2022-05-25 00:21 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +이벤트 상세 팝업에서 이벤트의 기간 표시를 커스터마이징할 수 있다.
```suggestion
이벤트 상세 팝업에서 이벤트의 기간을 커스터마이징할 수 있다.
```

아래 옵션들에서도 `표시`라는 단어 빼도 될 것 같아요

2022-05-25 02:45 UTC, dotaitch requested changes
템플릿 옵션 중에 변경된 것이 있었는데 그게 공유가 안되었네요ㅠㅠ 변경사항 반영 부탁드려요!

2022-05-25 02:45 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +| [popupDelete](#popupdelete)                               | 없음                    | 이벤트 상세 팝업에서 delete 버튼 텍스트                            |
```suggestion
| [popupSave](#popupsave)                                   | 없음                    | 이벤트 생성 팝업에서 저장 버튼 텍스트                              |
| [popupUpdate](#popupupdate)                               | 없음                    | 이벤트 수정 팝업에서 수정 버튼 텍스트                            |
| [popupEdit](#popupedit)                                   | 없음                    | 이벤트 상세 팝업에서 편집 버튼 텍스트                              |
| [popupDelete](#popupdelete)                               | 없음                    | 이벤트 상세 팝업에서 삭제 버튼 텍스트                            |
```

2022-05-25 02:45 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +| [popupDetailDate](#popupdetaildate)                       | boolean, TZDate, TZDate | 이벤트 상세 팝업에서 이벤트의 기간                                 |
`PopupDetailTitle`도 추가되었습니다! 자세한 건 업무#1780 댓글 확인 부탁드려요~

2022-05-25 02:45 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +| [popupDetailDate](#popupdetaildate)                       | boolean, TZDate, TZDate | 이벤트 상세 팝업에서 이벤트의 기간                                 |
```suggestion
| [popupDetailDate](#popupdetaildate)                       | EventModel | 이벤트 상세 팝업에서 이벤트의 기간                                 |
```

이 부분도 파라미터 변경되었습니다~

2022-05-25 02:45 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +| [popupDetailDate](#popupdetaildate)                       | boolean, TZDate, TZDate | 이벤트 상세 팝업에서 이벤트의 기간                                 |
아래 설명도 변경 부탁드려요!

2022-05-25 02:45 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +| [popupDetailUser](#popupdetailuser)                       | EventModel              | 이벤트 상세 팝업에서 이벤트의 참석자                               |
```suggestion
| [popupDetailAttendees](#popupdetailattendees)                       | EventModel              | 이벤트 상세 팝업에서 이벤트의 참석자                               |
```

2022-05-25 02:45 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +| [popupDetailRepeat](#popupdetailrepeat)                   | EventModel              | 이벤트 상세 팝업에서 이벤트의 반복 룰                              |
```suggestion
| [popupDetailRecurrenceRule](#popupdetailrecurrenceRule)                   | EventModel              | 이벤트 상세 팝업에서 이벤트의 반복 룰                              |
```

2022-05-25 02:45 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +| [comingDuration](#comingduration)                         | EventModel              | 주간/일간뷰의 timed 이벤트의 coming duration                        |
```suggestion
| [goingDuration](#goingduration)                           | EventModel              | 주간/일간뷰의 timed 이벤트의 일정 장소까지 이동 시간                         |
| [comingDuration](#comingduration)                         | EventModel              | 주간/일간뷰의 timed 이벤트의 복귀 시간                        |
```

2022-05-25 02:45 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +`eventModel` 파라미터를 이용해 주간/일간뷰의 timed 이벤트를 커스터마이징할 수 있다. going, coming duration을 제외한 부분이다.
```suggestion
`eventModel` 파라미터를 이용해 주간/일간뷰의 timed 이벤트를 커스터마이징할 수 있다. 이동 시간 및 복귀 시간을 제외한 부분이다.
```

2022-05-25 02:45 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/template.stories.mdx
> +| [popupDetailDate](#popupdetaildate)                       | boolean, TZDate, TZDate | 이벤트 상세 팝업에서 이벤트의 기간                                 |
아래 자세한 설명도 추가해야겠네요

2022-05-25 03:07 UTC, dotaitch approved these changes
리뷰 완료합니다! 고생 많으셨습니다

2022-05-25 03:22 UTC, merged