refactor: implement EventObject
nhn/tui.calendar pull request #1125
Opened 2022-05-24 12:12 UTC by dotaitch

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has description for the breaking change

### Description

* rename EventModelData to EventObject
* make EventModel class implement EventObject
* Use `new EventModel(event)` instead of `EventModel.create(event)` when creating a new instance of `EventModel`.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-05-25 11:48 UTC, adhrinae requested changes
다 찾아서 변경하느라 고생하셨어요.

`init` 메서드의 내용물을 `constructor` 로 옮기는 방식으로만 추가 개선이 되었으면 좋겠네요.

2022-05-25 11:48 UTC, adhrinae commented on apps/calendar/index.d.ts
> +  afterRenderEvent?: (eventObj: { eventData: EventObject }) => void;
요것도 실제로는 바로 `eventData: EventObject` 리턴해도 될거같네요.

2022-05-25 11:48 UTC, adhrinae commented on apps/calendar/src/model/eventModel.ts
> +  init(event: EventObject) {
기왕 `new EventModel` 방식으로 인스턴스를 생성한다면 이 메서드는 이제 필요가 없겠네요. `constructor` 안에서 해결하면 되니까요.

그리고 전반적으로 `||` 이용하는게 클래스 프로퍼티에 기본값 선언한 부분이랑도 겹치니까 코드를 다듬어서 불필요한 `||` 없이 `Object.keys` 로 객체 루프 돌면서 속성 할당하는 방식으로 바꿔도 될거같아요.

```ts
constructor(event: EventObject = {}) {
  Object.keys(event).filter(isPrimitiveProp).forEach(k => {
    if (isPresent(this[k]) && isPresent(event[k])) {
      this[k] = event[k]
    }
  });
  // 이후 추가 기본값 할당
}
```

하면서 타입 미스매치로 삽질을 하게 될지 모르겠네요. 제가 먼저 볼 수 있으면 이렇게 변경 가능한지 살펴볼게요.

2022-05-25 11:48 UTC, adhrinae commented on apps/calendar/src/model/eventModel.ts
> +    const result: { [k: string]: any } = {};
이 위에서 바로 `EventObj~` 타입으로 할당해두는건 안되던가요? 안그러면 차라리 밑에서 `forEach` 대신 `reduce<EventObjectWithDefaultValues>` 를 쓰는게 나을지도 모르겠네요.

2022-05-25 12:34 UTC, adhrinae commented on apps/calendar/src/model/eventModel.ts
> +    const result: { [k: string]: any } = {};
조금 시도해보니까 잘 안되는군요. 가장 타입세이프하게 만드는 방법은 각각의 속성을 일일이 할당한 객체 리터럴을 리턴하는건가봅니다 :(

```ts
toEventObject(): EventObjectWithDefaultValues {
  return {
    id: this.id,
    // ...
  };
}
```

2022-05-25 23:02 UTC, lja1018 reviewed
리뷰 완료합니다.

2022-05-26 00:32 UTC, dotaitch commented on apps/calendar/src/model/eventModel.ts
> +  init(event: EventObject) {
아 init을 쓰는 곳이 있어서 init은 그대로 두었습니다.
https://github.com/nhn/tui.calendar/blob/feat/event-object/apps/calendar/src/controller/base.ts#L132

update를 하는 곳인데 constructor와 update 함수를 따로 두는 것보단 기존처럼 init함수를 따로 둔 후 constructor에서도 쓰고 init 함수 자체로도 쓰게 하는게 더 좋을 것 같아서 기존 방식 유지했습니다~

2022-05-26 01:45 UTC, dotaitch commented on apps/calendar/src/model/eventModel.ts
> +  init(event: EventObject) {
내부 코드는 변경하겠습니다.

2022-05-26 01:51 UTC, dotaitch commented on apps/calendar/src/model/eventModel.ts
> +    return result as EventObjectWithDefaultValues;
사실 저도 네이밍이 마음에 들지는 않는데.... 그래도 이게 최선이었습니다...ㅠㅠㅠ

2022-05-26 02:07 UTC, dotaitch commented on apps/calendar/src/model/eventModel.ts
> +  attendees: string[] = [];
지정해야 합니다. 타입 지정을 하지 않으면 `attendees`는 `never[]`로, `category`와 `state`는 `string`으로, `raw`는 `null`로 타입추론이 되어서요.

2022-05-26 02:14 UTC, dotaitch commented on apps/calendar/index.d.ts
> +  afterRenderEvent?: (eventObj: { eventData: EventObject }) => void;
index.d.ts를 계속 관리해야 하나요? 이 PR에서는 찾아바꾸기 때문에 수정되긴 했는데, index.d.ts를 어떻게 처리하면 좋을지 릴리즈 전에 얘기해보면 좋을 것 같아요.

2022-05-26 13:50 UTC, adhrinae approved these changes

2022-05-27 01:53 UTC, merged