docs: add docs for theme
nhn/tui.calendar pull request #1126
Opened 2022-05-25 02:15 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- add docs for theme

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-05-25 08:55 UTC, dotaitch requested changes
리뷰 완료합니다. 나중에 theme 미구현된 옵션 완성되면 스크린샷도 함께 첨부하면 이해하기 쉬울 것 같아요. 지금은 스크린샷이 없으니까 이해하기 어렵네요ㅠㅠ

2022-05-25 08:55 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/theme.stories.mdx
> +| [dayGrid](#week-daygrid)                                               | 주간/일간뷰의 패널의 각 셀                                                             |
```suggestion
| [dayGrid](#week-daygrid)                                               | 주간/일간뷰에서 패널의 각 셀                                                             |
```

`~의`가 반복되는 것 같아서 `~에서`로 바꿔보았습니다. 만약 이렇게 변경해도 괜찮다면 아래도 `주간/일간뷰에서`로 수정하면 될 것 같아요. 아래도 마찬가지로 `~의`가 반복되더라구요.

2022-05-25 08:55 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/theme.stories.mdx
> +| [timeGridLeftAdditionalTimezone](#week-timegridleftadditionaltimezone) | 주간/일간뷰의 timed 이벤트 영역의 왼쪽 영역의 서브 타임존                              |
```suggestion
| [timeGridLeftAdditionalTimezone](#week-timegridleftadditionaltimezone) | 주간/일간뷰에서 timed 이벤트 영역의 왼쪽에 표시되는 서브 타임존                              |
```

2022-05-25 08:55 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/theme.stories.mdx
> +| [pastTime](#week-pasttime)                                             | 주간/일간뷰의 timed 이벤트 영역의 왼쪽 영역에서 지난 시간                              |
```suggestion
| [pastTime](#week-pasttime)                                             | 주간/일간뷰에서 timed 이벤트 영역의 왼쪽 영역에 표시되는 지난 시간                              |
```

2022-05-25 08:55 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/theme.stories.mdx
> +| [futureTime](#week-futuretime)                                         | 주간/일간뷰의 timed 이벤트 영역의 왼쪽 영역에서 미래 시간                              |
```suggestion
| [futureTime](#week-futuretime)                                         | 주간/일간뷰에서 timed 이벤트 영역의 왼쪽 영역에 표시되는 미래 시간                              |
```

2022-05-25 08:55 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/theme.stories.mdx
> +| [panelResizer](#week-panelresizer)                                     | 패널 조절 컴포넌트                                                                     |
```suggestion
| [panelResizer](#week-panelresizer)                                     | 패널 크기 조절 컴포넌트                                                                     |
```

2022-05-25 08:55 UTC, dotaitch commented on apps/calendar/stories/docs/ko/apis/theme.stories.mdx
> +셀렉션의 배경색, 테두리를 지정한다. 기본 값은 `backgroundColor`는 `'rgba(81, 92, 230, 0.05)'` `border`는 `'1px solid #515ce6'`이다.
```suggestion
셀렉션의 배경색, 테두리를 지정한다. 기본 값은 `backgroundColor`의 경우 `'rgba(81, 92, 230, 0.05)'`, `border`의 경우 `'1px solid #515ce6'`이다.
```

2022-05-25 11:14 UTC, adhrinae commented on apps/calendar/stories/docs/ko/apis/theme.stories.mdx
> +| [gridSelection](#common-gridselection) | 셀렉션 |
좋은 지적해주셨어요. 캘린더만 쭉 개발하면서 우리가 쓰기 편한 도메인 용어를 사용하니까 자주 잊게 되지만 사용자가 아무것도 모르는 상태라고 가정하여 '나라면 이 개념을 어떻게 쉽게 받아들일까?'를 끊임없이 생각하면서 문서를 작성하는게 중요합니다.

2022-05-25 11:21 UTC, adhrinae requested changes
리뷰 완료합니다. 지금은 문서 작성 초반이니까 다듬을 점들이 많이 보이지만 금방 더 나아질 것 같아요.

2022-05-25 11:21 UTC, adhrinae commented on apps/calendar/stories/docs/ko/apis/theme.stories.mdx
> +});
여기 아래에 공백 넣어주는게 낫겠네요.
그리고 각각의 코드 블락은 역할을 달리 하고 있는 것 같으니 주석을 위에 각각 달아주는게 좋겠어요.

- `// 인스턴스 생성하며 테마 설정하기`
- `// 생성된 인스턴스의 테마를 setTheme 메서드로 변경하기`

각각 이런 식으로요.

2022-05-25 11:21 UTC, adhrinae commented on apps/calendar/stories/docs/ko/apis/theme.stories.mdx
> +| [background](#common-backgroundcolor)  | 배경색 |
캘린더 전체의 배경색이라는 것을 알려주는게 좋겠네요.

2022-05-25 11:21 UTC, adhrinae commented on apps/calendar/stories/docs/ko/apis/theme.stories.mdx
> +테마 객체는 객체는 공통으로 적용되는 `common`, 주간/일간뷰를 위한 `week`, 월간뷰를 위한 `month` 세 부분으로 나뉘어진 중첩 객체다.
설명 이후에 '모든 값은 해당 속성에 대응되는 CSS 문자열 값이다' 라는 것을 언급해줄 필요가 있겠네요. 그냥 `string` 타입이라고만 하면 어떻게 넣는지 모를테니까요.

2022-05-25 11:21 UTC, adhrinae commented on apps/calendar/stories/docs/ko/apis/theme.stories.mdx
> +| 테마                                   | 설명   |
조금 번거롭겠지만 `테마 | 기본값 | 설명` 순으로 들어가는게 좋을거같아요.

그러면 사용자가 일일이 디테일을 확인하지 않아도 대략적인 감을 잡고 쉽게 적용할 수 있으니까요.

2022-05-26 00:51 UTC, lja1018 commented on apps/calendar/stories/docs/ko/apis/theme.stories.mdx
> +    backgroundColor: string;
스타일에 직접 사용할 때가 있다보니 `backgroundColor`에 한표 주고 싶네요.

2022-05-26 00:51 UTC, lja1018 commented on apps/calendar/stories/docs/ko/apis/theme.stories.mdx
> +| 테마                                   | 설명   |
프로퍼티 2개 이상의 객체만 따로 아래 코드블락에 기본 값을 적겠습니다.

2022-05-26 00:51 UTC, lja1018 commented on apps/calendar/stories/docs/ko/apis/theme.stories.mdx
> +| [gridSelection](#common-gridselection) | 셀렉션 |
좀더 이해하기 쉬운 용어를 사용하도록 고민하겠습니다.

2022-05-28 04:47 UTC, adhrinae commented on apps/calendar/stories/docs/ko/apis/theme.stories.mdx
> +    backgroundColor: string;
저도 이건 `backgroundColor` 로 통일되는데 동의합니다.

2022-05-28 04:49 UTC, adhrinae reviewed
기본값에 코드 블락 적용하는거만 신경써주시면 될거같고 나머지는 괜찮습니다.

2022-05-28 04:49 UTC, adhrinae commented on apps/calendar/stories/docs/ko/apis/theme.stories.mdx
> +| [backgroundColor](#common-backgroundcolor) | 'white'                | 캘린더의 배경색 |
좀 번거롭지만 각각의 기본값은 마크다운의 코드 문법(``으로 감싸기)으로 해주는게 API 문서로서 읽기 쉽겠어요.

2022-05-30 08:06 UTC, lja1018 commented on apps/calendar/stories/docs/ko/apis/theme.stories.mdx
> +| [backgroundColor](#common-backgroundcolor) | 'white'                | 캘린더의 배경색 |
표 안의 코드블럭은 무시되네요. 다른 방법을 찾아야할 것 같습니다.

2022-05-31 04:57 UTC, adhrinae approved these changes

2022-05-31 05:16 UTC, merged