docs: write options docs
nhn/tui.calendar pull request #1134
Opened 2022-06-02 08:23 UTC by lja1018

* add example captures

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- write `options` docs

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-06-03 05:50 UTC, adhrinae approved these changes
전반적으로 자잘한거 빼고는 문제 없어보입니다. 문서 링크 이름정도만 수정해주시고, 추가 문서 수정은 제가 이어서 할게요.

2022-06-03 05:50 UTC, adhrinae commented on apps/calendar/docs/ko/apis/options.stories.mdx
> +  customOffsetCalculator?: (primaryTimezoneName: string, timestamp: number) => number;
이거 타입을 수정했었어야했는데 제가 놓쳤네요. `timezoneName` 이 될 테고, 모든 타임존 값 전환 로직에 이 함수가 적용된다고 안내해야할 것 같아요. 타임존 관련 문서 수정은 제가 할게요.

2022-06-03 05:50 UTC, adhrinae commented on apps/calendar/docs/ko/apis/options.stories.mdx
> +캘린더에서 사용되는 타임존 정보를 지정한다. 기본값은 `{ zones: [] }`이다. `zones`는 각 타임존 정보들의 배열이며 타임존 정보는 해당 타임존의 이름(`timezoneName`), 표시 라벨(`displayLabel`), 툴팁(`tooltip`)을 지정할 수 있다.
추가로 타임존에 관해서는 기본적으로 `Intl.DateTimeFormat` 을 사용하고 있고, 그걸 적용하기 어려운 ie11 환경 정도에서 이 함수를 사용할 것을 권하는 정도로 문서를 추가해야겠습니다. 타임존 관련 문서 수정은 다 제가 할테니 신경쓰지 않으셔도 됩니다.

2022-06-03 05:50 UTC, adhrinae commented on apps/calendar/docs/ko/apis/options.stories.mdx
> +캘린더의 테마를 지정한다. 캘린더 인스턴스 생성 시에만 적용할 수 있으며 `setOptions` 메서드로는 변경이 불가능하다. 대신 `setTheme` 메서드로 변경 가능하며 자세한 내용은 [theme 문서](/story/documentation-ko-api-테마--page)에서 확인할 수 있다.
```suggestion
캘린더의 테마를 지정한다. 캘린더 인스턴스 생성 시에만 적용할 수 있으며 `setOptions` 메서드로는 변경이 불가능하다. 대신 `setTheme` 메서드로 변경 가능하며 자세한 내용은 [테마 문서](/story/documentation-ko-api-테마--page)에서 확인할 수 있다.
```

2022-06-03 05:50 UTC, adhrinae commented on apps/calendar/docs/ko/apis/options.stories.mdx
> +캘린더의 템플릿을 지정한다. 자세한 내용은 [template 문서](/story/documentation-ko-api-템플릿--page)에서 확인할 수 있다.
```suggestion
캘린더의 템플릿을 지정한다. 자세한 내용은 [템플릿 문서](/story/documentation-ko-api-템플릿--page)에서 확인할 수 있다.
```

2022-06-03 05:50 UTC, adhrinae commented on apps/calendar/docs/ko/apis/options.stories.mdx
> +캘린더에서 사용되는 캘린더 목록을 지정한다. 캘린더 목록의 각 캘린더 정보는 해당 캘린더의 `id`와 캘린더명, 색상 정보를 가지고 있다. 기본값은 `[]`이다.
요거 나중에 EventObject에 추가로 달아놓은 캘린더 타입 설명 링크 달아야겠네요. 지금은 아직 머지되지 않았으니 넘어갈게요.

2022-06-03 06:45 UTC, dotaitch requested changes
리뷰 완료합니다~

2022-06-03 06:45 UTC, dotaitch commented on apps/calendar/docs/ko/apis/options.stories.mdx
> +| 프로퍼티                              | 설명                                                                                               |
여기서도 기본값 명시하면 좋겠네요. 복잡한 기본값 같은 경우는 링크로 넘겨도 될 것 같은데 defaultView, useCreationPopup 같은 건 명시할 수 있을 것 같아요.

2022-06-03 06:45 UTC, dotaitch commented on apps/calendar/docs/ko/apis/options.stories.mdx
> +이 옵션을 `false`로 설정하면 통계 수집을 하지 않는다.
```suggestion
[Google Analytics(GA)](https://analytics.google.com/analytics/web/)를 위한 hostname 수집을 허용할지 여부를 지정한다. 기본값은 `true`이며 `false`로 설정하면 통계 수집을 하지 않는다.
[TOAST UI 캘린더](https://github.com/nhn/tui.calendar)는 [GA](https://analytics.google.com/analytics/web/)를 적용하여 오픈 소스 사용에 대한 통계를 수집하여 전 세계에서 얼마나 널리 사용되는지 확인한다. 이는 프로젝트의 향후 진행을 결정하는 중요한 지표 역할을 한다. `location.hostname`(예를 들어 "ui.toast.com")을 수집하며 사용량에 대한 통계를 측정하기 위해서만 사용된다.
```

이 옵션 설명이 먼저 나온 후 부가 설명(이 지표가 왜 필요한지)이 나오는 게 좋을 것 같아요.

2022-06-03 06:45 UTC, dotaitch commented on apps/calendar/docs/ko/apis/options.stories.mdx
> +캘린더의 일정 필터링 조건을 지정한다. 기본값은 `(event) => !!event.isVisible`로 일정의 `isVisible` 속성이 `true`인 일정만 렌더링한다.
커스텀 이벤트 필터를 적용하여 isVisible을 필터링하지 않을 경우 isVisible: false 인 이벤트가 캘린더에 나타난다는 설명도 덧붙이면 좋을 것 같아요.

2022-06-03 06:45 UTC, dotaitch commented on apps/calendar/docs/ko/apis/options.stories.mdx
> +캘린더의 날짜/시간 선택의 클릭과 더블 클릭의 가능 여부를 지정한다. 기본값은 `true`이다. `true`나 `false`의 `boolean` 타입으로 지정하면 클릭과 더블 클릭이 둘 모두 가능하거나 불가능하게 만든다.
```suggestion
캘린더의 날짜/시간을 선택할 때 클릭과 더블 클릭의 가능 여부를 지정한다. 기본값은 `true`이다. `true`나 `false`의 `boolean` 타입으로 지정하면 클릭과 더블 클릭이 둘 모두 가능하거나 불가능하게 만든다.
```

2022-06-07 05:11 UTC, lja1018 commented on apps/calendar/docs/ko/apis/options.stories.mdx
> +| 프로퍼티                              | 설명                                                                                               |
원래 적었었는데.. 각 설명에 타입과 기본값에 대해 설명하고 있어서 지웠습니다. 프로퍼티의 링크로 이동해서 바로 볼 수 있어서 괜찮다고 생각하는데 도형전임님한테도 의견 물어보겠습니다.

2022-06-07 05:11 UTC, lja1018 commented on apps/calendar/docs/ko/apis/options.stories.mdx
> +  customOffsetCalculator?: (primaryTimezoneName: string, timestamp: number) => number;
넵 그럼 남겨두겠습니다!

2022-06-07 05:11 UTC, lja1018 commented on apps/calendar/docs/ko/apis/options.stories.mdx
> +캘린더에서 사용되는 타임존 정보를 지정한다. 기본값은 `{ zones: [] }`이다. `zones`는 각 타임존 정보들의 배열이며 타임존 정보는 해당 타임존의 이름(`timezoneName`), 표시 라벨(`displayLabel`), 툴팁(`tooltip`)을 지정할 수 있다.
마찬가지로 리뷰 resolve 하지 않고 놔두겠습니다.

2022-06-07 05:11 UTC, lja1018 commented on apps/calendar/docs/ko/apis/options.stories.mdx
> +캘린더에서 사용되는 캘린더 목록을 지정한다. 캘린더 목록의 각 캘린더 정보는 해당 캘린더의 `id`와 캘린더명, 색상 정보를 가지고 있다. 기본값은 `[]`이다.
넵!

2022-06-07 05:19 UTC, lja1018 commented on apps/calendar/docs/ko/apis/options.stories.mdx
> +| 프로퍼티                              | 설명                                                                                               |
기본값 추가했습니다!

2022-06-07 08:16 UTC, dotaitch approved these changes

2022-06-07 09:36 UTC, dotaitch requested changes

2022-06-07 09:36 UTC, dotaitch commented on apps/calendar/docs/ko/apis/options.stories.mdx
> +  dragBgColor?: string;
`bgColor` -> `backgroundColor`로 바꿔야 해요

2022-06-07 12:04 UTC, merged