docs: write v2 migration guide
nhn/tui.calendar pull request #1137
Opened 2022-06-08 05:23 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- write v2 migration guide

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-06-08 06:10 UTC, adhrinae requested changes
대체로 무난한 것 같고, 아마 부족한 부분은 추가로 채워야 할 것 같네요. 그래도 당장 내용이 보강되었으면 좋겠다 싶은 부분 코멘트 남깁니다.

2022-06-08 06:10 UTC, adhrinae commented on apps/calendar/docs/ko/guide/migration_v2.stories.mdx
> +[preact](https://preactjs.com/)를 이용해 더 효율적으로 캘린더를 렌더링하는 TOAST UI Calendar v2.0이 출시되었다. v2에서는 캘린더의 기능이 많이 변경되었으며, 이를 이용해 캘린더를 사용하는 사용자들의 이해를 높일 수 있도록 마이그레이션을 가이드로 제공하고 있다.
> v2에서는 캘린더의 기능이 많이 변경되었으며

실제로는 기능이 크게 바뀐건 아니니까 기능을 추가하기보다 번들 사이즈 개선, 모던 개발 환경으로 업그레이드 하여 다른 기능 추가하를 용이하게 만들기 위한 기반 마련, 문서 내용 개선 정도가 언급되는게 나을 것 같네요.

2022-06-08 06:10 UTC, adhrinae commented on apps/calendar/docs/ko/guide/migration_v2.stories.mdx
> +또한 v1에서 사용하던 다음 프로퍼티들이 테마에서 제거되거나 이름이 변경되었다. 각종 색상 값들과 주간/일간뷰의 각 패널의 왼쪽 영역의 너비를 제외한 테마 값들은 전부 제거되었다.
테마가 제거된 대신 CSS를 활용하여 속성을 적용하도록 안내하는 부분이 필요하겠어요. 어떤클래스인지 그 위치를 일일이 언급 하면 좋긴 한데... 쉽진 않을거같네요. 각각 적용하면 되는 클래스이름을 안내하는게 어려우면 연관 파일 위치라도 링크해주는게 좋겠고요.

2022-06-08 06:54 UTC, lja1018 commented on apps/calendar/docs/ko/guide/migration_v2.stories.mdx
> +또한 v1에서 사용하던 다음 프로퍼티들이 테마에서 제거되거나 이름이 변경되었다. 각종 색상 값들과 주간/일간뷰의 각 패널의 왼쪽 영역의 너비를 제외한 테마 값들은 전부 제거되었다.
연관파일 위치는 관련 컴포넌트를 말씀하시는건가요?

2022-06-08 07:02 UTC, dotaitch requested changes
리뷰 완료합니다~

2022-06-08 07:02 UTC, dotaitch commented on apps/calendar/docs/ko/guide/migration_v2.stories.mdx
> +#### 옵션 변경점
```suggestion
#### 옵션 변경 사항
```

변경점은 변경 "지점" 이라는 뜻이라서 여기서 사용하기엔 부적절한 것 같아요. 변경된 목록/내용들이니까 "변경 사항" 이라고 하는 건 어떨까요??

2022-06-08 07:02 UTC, lja1018 commented on apps/calendar/docs/ko/guide/migration_v2.stories.mdx
> +  - [제거](#제거)
순수 직접 만드는 목차라 아쉽긴 합니다 ㅋㅋ

2022-06-08 07:04 UTC, lja1018 commented on apps/calendar/docs/ko/guide/migration_v2.stories.mdx
> +v1의 `creation popup`이라는 명칭이 v2에서 `form popup`이라는 명칭으로 변경됨에 따라 팝업을 띄우는 인스턴스 메서드 `openCreationPopup`도 `openFormPopup`으로 변경되었다.
그러고보니 옵션의 `useCreationPopup`은 그대로네요..

2022-06-08 07:34 UTC, adhrinae commented on apps/calendar/docs/ko/guide/migration_v2.stories.mdx
> +또한 v1에서 사용하던 다음 프로퍼티들이 테마에서 제거되거나 이름이 변경되었다. 각종 색상 값들과 주간/일간뷰의 각 패널의 왼쪽 영역의 너비를 제외한 테마 값들은 전부 제거되었다.
컴포넌트는 사용자가 잘 모를 확률이 높으니 적어도 특정 컴포넌트가 사용하는 클래스네임이 있는 CSS파일 위치가 되겠죠.

요거는 실제로 next 브랜치가 main이 되고 나서야 직접 Github 파일 URL을 링크하는게 가능할 것 같네요. 적어도 파일 이름정도는 미리 적어둬도 될거같고요.

2022-06-08 07:49 UTC, adhrinae commented on apps/calendar/docs/ko/guide/migration_v2.stories.mdx
> +  - [제거](#제거)
저거땜에 heading 파싱해서 임의의 목차 만드는 스크립트 구상하다가 현재 손 놓은 상태 ㅠ 로직은 일단 짰으니까 어떻게 만들 수는 있을거같아요.

2022-06-08 07:56 UTC, lja1018 commented on apps/calendar/docs/ko/guide/migration_v2.stories.mdx
> +또한 v1에서 사용하던 다음 프로퍼티들이 테마에서 제거되거나 이름이 변경되었다. 각종 색상 값들과 주간/일간뷰의 각 패널의 왼쪽 영역의 너비를 제외한 테마 값들은 전부 제거되었다.
관련 github URL로 작성했습니다.

2022-06-08 09:09 UTC, adhrinae approved these changes

2022-06-09 01:05 UTC, adhrinae approved these changes

2022-06-09 01:24 UTC, dotaitch approved these changes

2022-06-09 01:27 UTC, merged