feat: implement `scrollToNow`
nhn/tui.calendar pull request #1160
Opened 2022-06-17 02:46 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has a description of the breaking change

### Description

- implement `scrollToNow`

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-06-17 04:43 UTC, jwlee1108 approved these changes

2022-06-17 05:56 UTC, adhrinae requested changes
추가로 조금 봐줬으면 하는게 있어요.

2022-06-17 05:56 UTC, adhrinae commented on apps/calendar/src/components/timeGrid/currentTimeIndicator.tsx
> +        scrollArea.scrollTop = offsetTop - offsetHeight / 2;
- `(scrollAreaOffsetHeight / 2) - indicatorOffsetTop` 같은 느낌이었으면 알아보기 더 쉬웠겠네요.
- 그리고 IE가 아닌 브라우저는 `scrollTop` 대신 `scrollTo` 로 하고 `behavior: 'smooth'` 옵션을 줄 수 있으면 더 좋을 것 같아요. 이러기 위해 래핑한 함수를 하나 만들어서 `scrollTo` 가 지원된다면 이거로 하고, 아니라면 `scrollTop` 속성에 할당을 하는 식으로 만들어볼 수도 있지 않을까요?

2022-06-17 05:56 UTC, adhrinae commented on apps/calendar/src/factory/calendarControl.tsx
> +   *   if (calendar.getViewName() !== 'month') {
이제 요 if문은 굳이 필요없을지도? 어차피 다른 뷰에서 쓴다고 에러가 나는 것도 아니니까요.
그리고 위에 description에 추가 설명을 좀 강조해서 써두면 좋을 것 같아요.

'Nothing happens in the month view' 정도?

2022-06-17 06:00 UTC, adhrinae commented on apps/calendar/src/components/timeGrid/currentTimeIndicator.tsx
> +        scrollArea.scrollTop = offsetTop - offsetHeight / 2;
`scrollTo` 는 옵셔널이니까 한번 시도해보고 생각처럼 잘 되지 않으면 다음에 할 일로 미뤄둡시다.

2022-06-17 06:01 UTC, lja1018 commented on apps/calendar/src/components/timeGrid/currentTimeIndicator.tsx
> +        scrollArea.scrollTop = offsetTop - offsetHeight / 2;
래핑 함수를 만들어서 IE에선 현재 방식, IE외에선 `scrollIntoView`로 동작하게 하면 될까요?

2022-06-17 06:21 UTC, lja1018 commented on apps/calendar/src/components/timeGrid/currentTimeIndicator.tsx
> +        scrollArea.scrollTop = offsetTop - offsetHeight / 2;
기능탐지를 위해서는 `scrollTo`가 나을 것 같네요.

2022-06-17 06:21 UTC, adhrinae commented on apps/calendar/src/components/timeGrid/currentTimeIndicator.tsx
> +        scrollArea.scrollTop = offsetTop - offsetHeight / 2;
그것도 괜찮을 것 같긴 한데... 어차피 IE용 로직에 `layoutContainer` 를 무조건 필요로 하니까 번거롭게 `indicatorRef.current.scrollIntoView` 와 `scrollArea.scrollTop` 이 나뉘지 않게 `scrollArea.scrollTo` 로 하죠.

```js
// 어차피 layoutContainer는 불러와야함
const layoutContainer = useLayoutContainer();

useEffect(() => {
  // ...
  if (isIE) {
    const scrollArea = layoutContainer.querySelector(/* */);
    scrollArea.top = newScrollTop;
  } else {
    // 이거 대신에
    indicatorRef.current.scrollIntoView(/* */);
    // 이거로 통일
    scrollArea.scrollTo({ top: newScrollTop, /* */ });
  }
}, [/* */]);
```

대신 옵션을 받아서 IE가 아닐 때의 스크롤 동작을 사용자가 커스터마이징할 수 있으면 좋지 않을까요?

`cal.scrollToNow('smooth' | 'instant' | 'auto')` - 'auto' 가 기본인걸로.

2022-06-17 06:29 UTC, lja1018 commented on apps/calendar/src/components/timeGrid/currentTimeIndicator.tsx
> +        scrollArea.scrollTop = offsetTop - offsetHeight / 2;
방금 구현한 방식과 거의 비슷하네요! 스크롤 동작 옵션만 추가해서 푸쉬하겠습니다.

2022-06-17 08:38 UTC, adhrinae commented on apps/calendar/docs/ko/apis/calendar.stories.mdx
>  주간 뷰 혹은 일간 뷰인 상태에서 현재 시간이 포함된 시간 범위를 표시하고 있을 때, 현재 시간이 있는 위치로 스크롤을 이동한다.
IE11에서는 'smooth'를 넣어도 작동하지 않는다고 문서에 내용 추가해야할듯요.
그리고 타입이 정확하진 않지만 문서상으로는 `scrollBehavior?:` 가 되어야 할거에요. 사용자는 인자 안넣고도 쓸 수 있으니까요.

2022-06-21 00:48 UTC, adhrinae approved these changes

2022-06-21 01:32 UTC, merged