feat: implement react wrapper
nhn/tui.calendar pull request #1168
Opened 2022-06-29 09:02 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's the right issue type on the title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has a description of the breaking change

### Description

- Implement the React wrapper.
- Add guides for a React wrapper.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-06-29 10:39 UTC, adhrinae reviewed
고생했어요. 자잘한 수정할거만 확인해주세요.
README 안의 설명이 클래스 컴포넌트로 되어있는건... 나중에 함수 컴포넌트로 바꾸던지 하죠.

2022-06-29 10:39 UTC, adhrinae commented on apps/react-calendar/README.md
> +Or, include `tui-code-snippet.js` (**v1.4.0** or **later**) and then immediately write the options as follows:
이 부분은 굳이 언급할 필요가 있을랑가 모르겠네요. 아니라면 이 파일을 가져오는 방법이 링크로라도 안내가 있어야겠어요.

2022-06-29 10:39 UTC, adhrinae commented on apps/react-calendar/README.md
> +The React wrapper of TOAST UI calendar is almost identical to v1, and you can follow the [v2 migration guide](https://github.com/nhn/tui.calendar/blob/main/docs/en/guide/migration-guide-v2.md) of the
문서 링크는 상대경로로 해주셔요

2022-06-29 10:39 UTC, adhrinae commented on apps/react-calendar/README.md
> +We are supported in the form of props for [Options of TOAST UI Calendar](https://nhn.github.io/tui.calendar/latest/Options). Each name of props is same options of Toast UI Calendar except `view` is f
```suggestion
This wrapper component support props in the form of [Options of TOAST UI Calendar](https://nhn.github.io/tui.calendar/latest/Options). Each name of props matches the same option property of Toast UI Calendar except `view` is for `defaultView` of option. Additionally, you can set events using the `events` of prop.
```

2022-06-29 10:39 UTC, adhrinae commented on apps/react-calendar/README.md
> +## 🔧 Pull Request Steps
기여 관련 부분은 Vue쪽이랑 합을 맞추거나 아니면 메인 문서 링크만 걸어도 될듯요.

2022-06-29 10:39 UTC, adhrinae commented on apps/react-calendar/example/app.tsx
> +// export const WithFunctionComponent = (args) => <FunctionComponent {...args} />;
주석은 지워야겠네요.

2022-06-30 02:16 UTC, lja1018 commented on apps/react-calendar/README.md
> +Or, include `tui-code-snippet.js` (**v1.4.0** or **later**) and then immediately write the options as follows:
제거했습니다.

2022-06-30 02:30 UTC, dotaitch reviewed
리뷰 완료합니다! 이 PR 먼저 머지하면 제가 다른 PR에서 README 등 문서들 형식 통일하도록 수정해둘게요

2022-06-30 02:30 UTC, dotaitch commented on apps/react-calendar/README.md
> +React Wrapper of TOAST UI Calendar applies Google Analytics (GA) to collect statistics on the use of open source, in order to identify how widely TOAST UI Calendar is used throughout the world. It al
Vue calendar의 경우 `TOAST UI Calendar for Vue`, `Vue Wrapper` 라는 용어만 사용했어요. 하나로 통일하는 게 어떨까요?

2022-06-30 02:30 UTC, dotaitch commented on apps/react-calendar/README.md
> +## Migration to v2
README에 Migration to v2 섹션이 있으니 좋네요 👍  나머지 README는 제가 추가해둘게요

2022-06-30 02:30 UTC, dotaitch commented on apps/react-calendar/README.md
> +## 💾 Installation
Calendar Core, vue calendar의 경우 README에는 최대한 간략하게 설치 방법 및 사용 방법을 적었어요.
먼저 #1168 PR 머지하시면 제가 #1170 PR에서 형식이나 내용 수정해둘게요!

2022-06-30 02:30 UTC, dotaitch commented on apps/react-calendar/package.json
> +    "types/index.d.ts"
`/ie11` import 시에도 index.d.ts 잘 찾아지나요? 안된다면 오늘 오전에 공유해드린 typeVersions 적용 부탁드려요!

2022-06-30 02:30 UTC, dotaitch commented on apps/react-calendar/vite.config.ts
> +        formats: isESM || isIE11 ? ['es'] : ['umd'],
vue-calendar의 경우 ie11용 번들을 umd로 내보내도 동작하던데, 이는 react와 관련있는 문제인건가요??

2022-06-30 02:30 UTC, dotaitch commented on apps/react-calendar/vite.config.ts
> +    build: {
rollupOptions.external에 react 설정할 필요 없나요?

2022-06-30 03:02 UTC, lja1018 commented on apps/react-calendar/README.md
> +## 🔧 Pull Request Steps
넵 vue wrapper 쪽에 맞춰서 작성했습니다!

2022-06-30 03:04 UTC, lja1018 commented on apps/react-calendar/example/app.tsx
> +// export const WithFunctionComponent = (args) => <FunctionComponent {...args} />;
전에 제거했었는데 커밋 취소하면서 날아갔네요 😂

2022-06-30 03:05 UTC, lja1018 commented on apps/react-calendar/README.md
> +React Wrapper of TOAST UI Calendar applies Google Analytics (GA) to collect statistics on the use of open source, in order to identify how widely TOAST UI Calendar is used throughout the world. It al
vue -> react 로 바꾼 용어로 통일하겠습니다!

2022-06-30 03:08 UTC, lja1018 commented on apps/react-calendar/vite.config.ts
> +        formats: isESM || isIE11 ? ['es'] : ['umd'],
넵. 어제 이리저리 테스트해보니 `umd`일 때는 IE에서 잘 동작 안하더라구요.

2022-06-30 03:18 UTC, lja1018 commented on apps/react-calendar/vite.config.ts
> +    build: {
테스트 결과 번들크기도 줄고 IE11에서 정상동작 하네요. 감사합니다 :)

2022-06-30 04:28 UTC, lja1018 commented on apps/react-calendar/package.json
> +    "types/index.d.ts"
`typeVersions` 적용하니 `index.d.ts` 잘 찾아가네요.

2022-06-30 05:44 UTC, dotaitch requested changes

2022-06-30 05:44 UTC, dotaitch commented on apps/react-calendar/example/app.tsx
> +        defaultView={selectedView}
`defaultView`가 쓰이고 있네요. `view`로 바꿔야 겠어요

2022-06-30 06:19 UTC, dotaitch commented on apps/react-calendar/example/app.tsx
> +        defaultView={selectedView}
`view`가 아예 동작을 안하고 있어요. Calendar Core로 view 값이 안넘어가는 것 같은데 확인 부탁드려요.
그리고 view 타입도 `ViewType`으로 변경 부탁드려요. 지금은 'month'랑 'week' 밖에 입력이 안되네요

2022-06-30 06:21 UTC, lja1018 commented on apps/react-calendar/example/app.tsx
> +        defaultView={selectedView}
`view` 타입은 `viewType`으로 지정되어 있어요

2022-06-30 06:38 UTC, dotaitch commented on apps/react-calendar/example/app.tsx
> +export function App({ view }: { view: CalendarViewType }) {
아 여기가 `week`, `month`로만 되어 있어서 `day`가 입력이 안되는거였네요. 사실 예제라서 상관없긴 한데, 예제를 보고 참고하려는 사람이 있을 것 같아서 여기도 수정 부탁드려요~

2022-06-30 07:11 UTC, lja1018 commented on apps/react-calendar/example/app.tsx
> +export function App({ view }: { view: CalendarViewType }) {
생각지도 못했네요;; 수정했습니다.

2022-06-30 08:26 UTC, dotaitch approved these changes

2022-06-30 12:46 UTC, merged