fix: getWeekDates calculate week dates correctly
nhn/tui.calendar pull request #1214
Opened 2022-07-18 07:09 UTC by lja1018

### Please check if the PR fulfills these requirements

- [x] It's the right issue type on the title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has a description of the breaking change

### Description

- fixed calculation of `getWeekDates` correctly
- today: `Friday`, `startDayOfWeek`: `6(Saturday)`
  - AS-IS
![스크린샷 2022-07-15 오후 4 04 14](https://user-images.githubusercontent.com/28647773/179460340-e05db005-d6cb-48e3-9ec6-c10d3fd2fb39.png)
  - TO-BE
![스크린샷 2022-07-15 오후 4 03 40](https://user-images.githubusercontent.com/28647773/179460392-fab3c6d2-8479-411f-b504-00b0c5754893.png)

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-07-18 23:06 UTC, adhrinae reviewed
LGTM

테스트용 데이터에 안내 주석 간단히 달려있음 좋겠네요. 그리고 `todayList` 가 화요일부터 시작하도록 만든거 맞나요?

2022-07-18 23:06 UTC, adhrinae commented on apps/calendar/src/helpers/grid.spec.ts
> +    new TZDate(2022, 6, 23),
5월 17일(화) 부터 23일(월) 까지인가요? 주석으로 간단히 언급이 있으면 알아보기 좋을거같네요.

2022-07-19 00:37 UTC, adhrinae commented on apps/calendar/src/helpers/grid.spec.ts
> +    new TZDate(2022, 6, 23),
잘못 봐서 1을 더해야하는게 아니라 빼버렸었네요

2022-07-19 05:21 UTC, dotaitch requested changes
리뷰 완료합니다. `require-await` 룰 off 한 것만 확인 부탁드려요~

2022-07-19 05:21 UTC, dotaitch commented on .eslintrc.js
> +        'require-await': 'off',
이 룰은 왜 off 처리 인가요?? 저는 이 룰 도움 받을 때가 종종 있어서 off 처리를 하지 않는게 좋을 것 같아요. 만약 off 해야 할 곳이 있다면 그 부분 코드를 수정하거나 그 부분만 off 하는게 어떨까요?

2022-07-19 05:21 UTC, dotaitch commented on apps/calendar/src/helpers/grid.spec.ts
> +    async (startDayOfWeek, dayOfToday, prevDateCount, nextDateCount) => {
여기 때문에 `require-await`을 off 처리한 것 같은데, 여기서 async를 빼면 되지 않나요? 함수 내부에서 await을 쓰지 않는데 async가 필요한가요??

2022-07-19 05:45 UTC, lja1018 commented on apps/calendar/src/helpers/grid.spec.ts
> +    async (startDayOfWeek, dayOfToday, prevDateCount, nextDateCount) => {
일단 [여기서](https://jestjs.io/docs/api#testconcurrenteachtablename-fn-timeout) async 함수여야 한다고 해서 넣었는데 린트에러가 발생해서 jest 테스트 파일에만 룰을 off 한거였습니다.
해당 부분만 주석으로 off하도록 수정할게요.

2022-07-20 00:35 UTC, dotaitch approved these changes

2022-07-20 06:30 UTC, merged