feat: collapse duplicate events
nhn/tui.calendar pull request #1215
Opened 2022-07-19 05:11 UTC by dotaitch

### Please check if the PR fulfills these requirements

- [x] It's the right issue type on the title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has a description of the breaking change

### Description

- Implement `weekOptions.collapseDuplicateEvents` option.
  - Collapse duplicate events in the daily/weekly view.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-07-20 02:09 UTC, adhrinae requested changes
리뷰 완료합니다. 어려운 기능 구현하느라 고생하셨어요.

사소한 코멘트와 함께 테스트, 문서 수정 요청합니다.

2022-07-20 02:09 UTC, adhrinae commented on docs/en/apis/options.md
> +You can collapse duplicate events in the daily/weekly view. The default value is `false`, duplicate events are handled in the same way as normal events. When it is `true`, **events with the same `tit
```suggestion
You can collapse duplicate events in the daily/weekly view. The default value is `false`. The calendar handles duplicate events in the same way as normal events. When it is `true`, **events with the same `title`, `start`, and `end`** are classified as duplicate events and **the last event** among them is expanded during initial rendering. If you want to filter duplicate events based on your requirements, set `getDuplicateEvents`. And if you want to choose which event is expanded during initial rendering, set `getMainEvent`.
```

2022-07-20 02:09 UTC, adhrinae commented on docs/en/apis/options.md
> +      getMainEvent: (events) => events[events.length - 1],
여기 윗줄에 "`event` 는 `getDuplicateEvents` 의 리턴 값이다" 라는 내용이 주석으로 담겨있으면 좋겠어요. 생각보다 사람들은 문서 본문 읽는것보다 예제만 바로 보고 가져다 쓴 다음 안된다고 하는 경우가 많더군요.

2022-07-20 06:49 UTC, lja1018 reviewed
리뷰 완료합니다.

2022-07-20 06:49 UTC, lja1018 commented on apps/calendar/playwright/utils.ts
> +  return `[data-testid^="time-event-${title}-"]`;
`^=` 때문에 `time-event-${title}`로 시작하기만 하면 잡히지 않나요?

2022-07-20 06:49 UTC, lja1018 commented on apps/calendar/playwright/week/timeGridEventClick.e2e.ts
> +    const longCollaspedEventLocator = page.locator(getTimeEventSelector(longCollapsedEventTitle));
```suggestion
    const longCollapsedEventLocator = page.locator(getTimeEventSelector(longCollapsedEventTitle));
```

2022-07-20 06:49 UTC, lja1018 commented on apps/calendar/src/controller/column.ts
> +    const { renderStart, renderEnd } = options;
위에서 같이 뺄 수 있을 것 같습니다.

2022-07-20 06:49 UTC, lja1018 commented on apps/calendar/src/slices/layout.ts
> +          state.weekViewLayout.selectedDuplicateEventCid = cid ?? -1;
`-1`을 `DEFAULT_DUPLICATE_EVENT_CID` 같은 상수로 분리하면 좋을 것 같습니다!

2022-07-20 06:49 UTC, lja1018 commented on apps/calendar/src/slices/options.ts
> +    getMainEvent: (events: EventObjectWithDefaultValues[]) => events[events.length - 1],
`utils/array.ts`의 `last` 활용하면 좋을 것 같습니다!

2022-07-20 07:50 UTC, dotaitch commented on apps/calendar/playwright/utils.ts
> +  return `[data-testid^="time-event-${title}-"]`;
네 맞아요. 그런데 mockEvent 중에서 `duplicate event`와 `duplicate event with attendee`가 있는데 전자를 찾으면 후자도 같이 찾아지더라구요. 그래서 title의 경우 전체가 똑같은 것만 찾게 하려고 뒤에 `-`를 붙였습니다.

참고로 timeEvent testID는 `time-event-${title (space 포함)}-${cid}`로 되어 있어요.

2022-07-20 07:51 UTC, dotaitch commented on apps/calendar/src/controller/column.spec.ts
> +      -1,
넵 맞습니다.

2022-07-20 08:29 UTC, dotaitch commented on apps/calendar/src/slices/options.ts
> +  week.collapseDuplicateEvents = initializeCollapseDuplicateEvents(week.collapseDuplicateEvents);
아뇨`initializeMonthOptions`과 비슷하게 하려고 이렇게 했어요. 그리고 이렇게 적으면 기본값도 한눈에 잘 보여서 좋더라구요.

테스트로 말씀하신대로 아래처럼 리턴문에서 바로 사용해봤는데, 에러나는 건 없었어요.
```js
function initializeWeekOptions(weekOptions: Options['week'] = {}): CalendarWeekOptions {
  return {
    startDayOfWeek: Day.SUN,
    dayNames: [],
    narrowWeekend: false,
    workweek: false,
    showNowIndicator: true,
    showTimezoneCollapseButton: false,
    timezonesCollapsed: false,
    hourStart: 0,
    hourEnd: 24,
    eventView: true,
    taskView: true,
    ...weekOptions,
    collapseDuplicateEvents: initializeCollapseDuplicateEvents(
      weekOptions.collapseDuplicateEvents ?? false
    ),
  };
}
```

2022-07-20 08:31 UTC, dotaitch commented on apps/calendar/stories/mocks/types.ts
> +  attendees?: string[];
`goingDuration`, `comingDuration`, `attendees`는 optional이어야 하는데 `Required<Pick<EventObject, ...>>` 이렇게 Pick한 건 Required로 만들고 있어서 따로 빼냈습니다.

2022-07-20 23:18 UTC, adhrinae commented on apps/calendar/src/components/events/timeEvent.tsx
> +import { DEFAULT_DUPLICATE_EVENT_CID } from '@src/slices/layout';
상수는 `src/constants/layout` 정도의 파일을 만들어서 거기서 가져오도록 하는게 어떨까요?

2022-07-20 23:18 UTC, adhrinae commented on apps/calendar/src/controller/column.ts
> +export const COLLAPSED_DUPLICATE_EVENT_WIDTH = 5;
이것도 외부로 내보낼걸면 상수 파일에 들어가면 좋겠어요.

2022-07-20 23:19 UTC, adhrinae commented on apps/calendar/src/slices/options.ts
> +  week.collapseDuplicateEvents = initializeCollapseDuplicateEvents(week.collapseDuplicateEvents);
기억났어요. 아마 지금은 괜찮은데 옵셔널로 처리된 타입 보강하려고 하면 그때 꼬이기 시작했던 것 같네요. 저도 가독성 측면에서 지금의 코드도 좋다고 생각합니다. 요대로 가시죠.

2022-07-22 01:28 UTC, adhrinae approved these changes

2022-07-22 03:21 UTC, lja1018 approved these changes

2022-07-27 04:44 UTC, merged