fix: solve side effects related to duplicate events
nhn/tui.calendar pull request #1226
Opened 2022-07-25 12:14 UTC by dotaitch

### Please check if the PR fulfills these requirements

- [x] It's the right issue type on the title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has a description of the breaking change

### Description

- Fix an issue: the layout is broken when the collide event differs for each duplicate event.

| Before | After |
| --- | --- |
| ![bug-collideeventdiffers](https://user-images.githubusercontent.com/8615506/180773817-54ce756c-cf21-4720-896c-8643cb785994.gif) | ![image](https://user-images.githubusercontent.com/8615506/180773973-22be7d9a-a7ea-4b52-9db3-6c5b29e42ce5.png) |

- Fix an issue: going and coming durations are not showing in the collapsed event.

| Before | After |
| --- | --- |
| ![bug-durationsnotshowing](https://user-images.githubusercontent.com/8615506/180774313-92fdd5ce-810b-4290-a591-6f056a23a3b9.png) | ![image](https://user-images.githubusercontent.com/8615506/180774402-472af6bf-811d-4f6b-bf13-61e829805097.png) |

- Fix an issue: when there are too many events in one column, the width of the expanded event is less than the collapsed one.

| Before | After |
| --- | --- |
| ![bug-toomanyevents](https://user-images.githubusercontent.com/8615506/180774733-72a7b4ce-8315-48d4-9eb6-c061984b52eb.png) | ![image](https://user-images.githubusercontent.com/8615506/180774946-b997459e-5cba-45e2-bd34-21b1c1914f41.png) |
| The width of the collapsed event was `5%` of the column. | Now, the width of the collapsed event is `9px`. |

- Add an example for `collapseDuplicateEvent` option.
- Update docs for `collapseDuplicateEvent` option.

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-07-25 12:16 UTC, dotaitch commented on apps/calendar/examples/00-calendar-app.html
> +              <label for="collapse">Collapse duplicate events and disable the detail popup</label>
중복 일정이 겹쳐지고 펼쳐지는 동작이 잘 보이도록 `collapseDuplicateEvents`를 활성화하면 `useDetailPopup`를 끄도록 만들었습니다.

2022-07-25 12:21 UTC, dotaitch commented on apps/calendar/src/controller/column.ts
> +    const baseWidth = Math.round(100 / maxRowLength);
중복 일정의 경우 preact에 스타일을 지정할 때 left와 width를 문자열값으로 넘기게 됩니다. 이 때 나누어 떨어지지 않는 baseWidth를 가지는 경우 css 스타일이 제대로 적용되지 못하는 경우가 생겨서 반올림하도록 하였습니다.

![bug-basewidth](https://user-images.githubusercontent.com/8615506/180776044-f5b8c0ed-cfb9-4977-9402-488c6a0128f2.png)

#### 기존에 문제가 발생하지 않았던 이유

기존에는 left와 width를 `number` 형식으로 preact에 넘기고, preact 내부에서 소숫점을 처리해주었습니다. 하지만 현재 중복된 일정의 경우 left와 width를 `string` 형식으로 넘기도록 변경되면서 preact에서 자동으로 처리되지 않습니다.

2022-07-25 12:24 UTC, dotaitch commented on apps/calendar/src/model/eventUIModel.ts
> +  duplicateWidth = '';
기존의 `left`와 `width`를 수정하지 않고 새로운 프로퍼티를 만든 이유는 타입 문제 때문입니다. `left`와 `width`가 문자열도 가능하도록 `number | string` 타입으로 바꾸면 다른 많은 곳에서 타입 에러가 발생하고, 이를 모두 수정해야 합니다. 생각보다 영향을 끼치는 부분이 많아서 새로운 프로퍼티를 만들었습니다.

2022-07-25 12:26 UTC, dotaitch commented on apps/calendar/src/model/eventUIModel.ts
> +        });
`duplicateStarts`에는 중복 일정 그룹 중 가장 이른 start + goingDuration을, `duplicateEnds`에는 가장 늦은 end + comingDuration을 저장합니다. `duplicateStarts`과 `duplicateEnds`는 이미 duration을 고려한 값이기 때문에 충돌을 계산할 때는 goingDuration과 comingDuration을 0으로 설정합니다.

2022-07-26 06:01 UTC, adhrinae requested changes
리뷰 완료합니다. 어려운 기능 구현하느라 무척 고생하셨어요.

자잘하게 코드 다듬어주셨으면 하는 부분, 설명이 조금 더 필요하다고 생각하는 부분 등 코멘트 남겼습니다.

2022-07-26 07:19 UTC, dotaitch commented on apps/calendar/src/components/events/timeEvent.tsx
> +  return left > 0 || percent > 0 || px > 0 ? TIME_EVENT_CONTAINER_MARGIN_LEFT : 0;
넵 만약 left가 number라면 `left > 0`에서 조건 확인하고, string이라면 `percent > 0 || px > 0`에서 조건 확인하게 하려고 의도한 동작입니다.

2022-07-26 07:34 UTC, dotaitch commented on apps/calendar/src/controller/column.ts
> +    left = `calc(${toPercent(left)})`;
중복 일정의 경우 동일한 형식으로 저장하여 반복 로직을 좀 더 깔끔하게 만들기 위해서요.

예를 들어 기존처럼 퍼센트값을 number로 저장한다면 `extractPercentPx`를 하기 전 `isNumber()`함수를 사용해서 예외 처리를 해주어야 하지만, `calc(N%)`로 저장하면 예외 처리 없이 중복 일정을 반복문에서 동일한 로직으로 처리할 수 있어요.

2022-07-26 07:36 UTC, dotaitch commented on apps/calendar/src/controller/column.ts
> +    left = `calc(${toPercent(left)})`;
아 `calc()`를 굳이 씌우지 않고 `toPercent()`만 사용해도 되는군요..! 수정해두겠습니다.

2022-07-26 07:39 UTC, dotaitch commented on apps/calendar/src/controller/column.ts
> +    if (percent) {
정확하게 말하자면 percent 값이 있는 경우(`percent !== 0`) 입니다. 그런데 percent가 음수가 되는 일이 없긴해요.

2022-07-26 07:45 UTC, dotaitch commented on apps/calendar/src/helpers/css.ts
> +  const pxRegexp = /(-?)\s?(\d+)px/;
`pxRegexp`가 **`-`가 있거나 없으면서** `숫자px`인 경우를 가려내기 때문에 `+`는 자동으로 추출되게 됩니다. `-`를 넣은 이유는 `-`가 있는 경우에는 음수로 변환하기 위해서예요.

<img width="387" alt="image" src="https://user-images.githubusercontent.com/8615506/180951650-2b15ce15-1043-44f0-92a3-212983554c2c.png">

사용 예는 추가해둘게요.

2022-07-26 07:59 UTC, dotaitch commented on apps/calendar/src/controller/column.ts
> +    const baseWidth = Math.round(100 / maxRowLength);
아 이 부분은 제가 잘못 파악했네요. 기존에도 number가 아닌 string으로 넘기고 있었습니다. ([참고 - TimeEvent.tsx L75-L79](https://github.com/nhn/tui.calendar/pull/1226/files/745508a1861f15d7d932afd3fb1dc7a001359e45#diff-48efdc794b1db796464d5e0160cb0137b5f855bd5cde912850596e6c49676c45L75-L79))

제 생각에는 이번에 추가된 퍼센트 값을 더하고 빼는 과정 때문에 부동소수점 오류가 난 것 같습니다.
기존에는 부동소수점의 연산이 아니라 `100 / baseWidth` 와 같이 결과가 부동소수점으로 나타나는 거라 문제가 없었는데, 이번에 추가된 로직은 부동소수점끼리의 연산이라 문제가 발생한 것 같아요.

2022-07-26 08:15 UTC, lja1018 reviewed
리뷰 완료합니다.

2022-07-26 08:15 UTC, lja1018 commented on apps/calendar/src/controller/column.ts
> +  const currEventIndex = duplicateEvents.findIndex((event) => event.cid() === uiModel.cid());
자잘하지만 `curEventIndex`는 어떠신가요? 줄여쓰면 보통 `cur`로 썼던거 같아서요.

2022-07-26 08:15 UTC, lja1018 commented on apps/calendar/src/controller/column.ts
> +  // if it is expanded, (baseWidth)% - (other duplicate events' width + marginLeft)px - (its marginLeft)px
```suggestion
  // if it is expanded, (baseWidth)% - (other duplicate event's width + marginLeft)px - (its marginLeft)px
```

2022-07-26 08:15 UTC, lja1018 commented on apps/calendar/src/controller/column.ts
> +  }
얼리리턴보다
```suggestion
  if (isDuplicateEvent || uiModel.duplicateEvents.length === 0) {
    // 아래 로직
  } else {
    uiModel.duplicateEvents.forEach((event) => {
      setRenderInfo({
        uiModel: event,
        columnIndex,
        baseWidth,
        startColumnTime,
        endColumnTime,
        isDuplicateEvent: true,
      });
    });
  }
```
같은 방식은 어떠신가요?

2022-07-27 00:09 UTC, adhrinae commented on apps/calendar/src/controller/column.ts
> +    if (percent) {
그러면 `percent !== 0` 처럼 명시적인 조건문이었으면 더 좋겠습니다.

2022-07-27 00:13 UTC, adhrinae commented on apps/calendar/src/helpers/css.ts
> +  const pxRegexp = /(-?)\s?(\d+)px/;
네 제가 리턴 부분을 주의깊게 보지 않았군요. 말씀하시는대로 동작하시는게 맞다는거 이해했습니다.

2022-07-27 02:09 UTC, dotaitch commented on apps/calendar/src/controller/column.ts
> +  // if it is expanded, (baseWidth)% - (other duplicate events' width + marginLeft)px - (its marginLeft)px
이벤트**들**의 너비를 의미한거라서 기존 문장 유지할게요~

2022-07-27 02:19 UTC, dotaitch commented on apps/calendar/src/controller/column.ts
> +  }
저는 개인적으로 얼리 리턴을 더 선호합니다..ㅎㅎㅎ 굳이 else 문을 만들어서 인덴테이션 한 단계를 추가하고 싶지 않기도 하고, 아래 로직에서도 return하는 로직이 없어서 어느 로직을 타더라도 리턴 타입이 동일하게 `undefined`이 되거든요.

2022-07-27 02:22 UTC, dotaitch commented on apps/calendar/src/controller/column.ts
> +  }
혹시 else 쓰는 걸 선호하는 이유가 있나요??

2022-07-27 03:16 UTC, lja1018 commented on apps/calendar/src/controller/column.ts
> +  }
지금 함수는 괜찮은데 함수가 길어지고 로직이 복잡할 때 중간에 얼리리턴으로 빠져나가면 로직 파악이 쉽지 않더라구요.

개인적인 의견이라 반영 안하셔도 괜찮습니다!

2022-07-27 03:40 UTC, adhrinae commented on apps/calendar/src/controller/column.ts
> +  }
저도 기본적으론 얼리리턴 좋아하는데 아무것도 리턴 안하고 `return` 만 있는 얼리리턴보단 값이 명시적인 얼리리턴이어야 그럴만한 가치가 있다고 생각하는 편이에요.

이 함수는 약간 다른데, 재귀함수이므로 조건 종료 부분이 먼저 함수 상단에 드러나있는게 좋다고 생각해서 지금 상태로도 충분하다 봅니다.

제 코멘트에도 썼지만 이런 형태의 재귀가 아닌 다른 방식으로 풀어나갈 수 있으면 좋겠지만 마땅한 개선 아이디어가 떠오르지 않아 넘어가시죠.

2022-07-27 03:43 UTC, adhrinae approved these changes

2022-07-27 04:55 UTC, merged