Feat : custom timezone spec
nhn/tui.calendar pull request #721
Opened 2020-11-22 12:06 UTC by jungeun-cho

### Please check if the PR fulfills these requirements
- [ ] It's submitted to right branch according to our branching model
- [ ] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2020-11-22 12:31 UTC, jungeun-cho commented
ok to test

2020-11-22 13:31 UTC, jungeun-cho commented
ok to test

2020-11-23 03:11 UTC, jungeun-cho commented
ok to test

2020-11-25 07:05 UTC, dongsik-yoo reviewed
진행한 데까지는 남겨놓고 이어서할게요.

2020-11-25 07:05 UTC, dongsik-yoo commented on src/js/common/timezone.js
> +    var timezoneCode = timezoneObj.timezone;
timezone, timeZone의 네이밍이 통일되어 있지 않습니다. 적어도 인터페이스에서는 맞추어야 되겠습니다.

2020-11-27 07:50 UTC, dongsik-yoo requested changes
리뷰 완료합니다. 고생하십니다!

2020-11-27 07:50 UTC, dongsik-yoo commented on src/js/common/timezone.js
> +    timestamp = Date.now();
`timestamp` 변수 초기화는 다음 if문 내부에서 실제로 쓰일 때 해도 되겠어요.

2020-11-27 07:50 UTC, dongsik-yoo commented on src/js/common/timezone.js
> +    if (!timezoneObj) {
346 라인에서 이미 `timezoneObj`객체의 프러터티에 접근하고 있어서 null이라면 벌써 에러가 날거예요. 조건문과 파라미터가 올 수 있는 값을 확인 부탁드립니다.

2020-11-27 07:50 UTC, dongsik-yoo commented on src/js/common/timezone.js
> +    if (timezoneCode) {
349 라인에서 `!timezoneCode` 조건을 체크해서 한꺼번에 리턴하면 여기서는 if문을 뺄 수 있겠어요.

2020-11-27 07:50 UTC, dongsik-yoo commented on src/js/common/timezone.js
> +            setByTimezoneOption = false;
이 부분이 OS 오프셋과 동일한 오프셋을 설정할 때 무시하는 코드인가요?

2020-11-27 07:50 UTC, dongsik-yoo commented on src/js/common/timezone.js
> + *
이 함수는 설명이 없네요?

2020-11-27 07:50 UTC, dongsik-yoo commented on src/js/common/timezone.js
> +var differentOffset = {
상수라서 상수 네이밍을 하는게 좋겠습니다.

2020-11-27 07:50 UTC, dongsik-yoo commented on src/js/controller/base.js
> +        // 커스텀 타임존을 사용할때는 네이티브 타임존 오프셋을 고정해서 렌더링한다.
주석이 필요하면 영어로 부탁드릴게요.

2020-11-27 07:50 UTC, dongsik-yoo commented on src/js/factory/calendar.js
> +            timezones: options.timeZone && options.timeZone.zones ? options.timeZone.zones : [],
` options.timeZone`이 없고 `options.timezones`가 설정되었을 경우는 어디서 설정하나요? 하위 호환성이 유지가 되는지 확인 부탁합니다.

2020-11-27 07:50 UTC, dongsik-yoo commented on src/js/factory/calendar.js
> +    var timeZone = options.timeZone;
`options.timezones`가 들어왔을 경우도 고려가 되어야 합니다.

2020-11-27 07:50 UTC, dongsik-yoo commented on src/js/model/schedule.js
> +    var isOffsetChanged = checkOffset.isOffsetChanged;
표현은 different가 맞지 않을까요?

2020-11-27 07:50 UTC, dongsik-yoo commented on src/js/model/schedule.js
> + * @param {Date} start render start date
타입이 TZDate로 들어오네요^^

2020-11-27 07:50 UTC, dongsik-yoo commented on src/js/view/popup/scheduleDetailPopup.js
> +    var schedule = util.extend({}, scheduleViewModel);
`schedule` => `viewModel`로 바꾸는 것은 어때요? 실제 클래스가 ScheduleViewModel 이라서 Schedule 객체와 헷갈리는 것 같아요.

2020-11-27 07:50 UTC, dongsik-yoo commented on src/js/view/week/time.js
> +    var modelDuration = viewModel.duration();
타임존을 인해 변하는 offsetStart를 구하는 로직을 별도의 함수로 빼는게 어떤 부분이 수정이 되고 있는지 확인하기 좋을 것 같아요.

2020-11-27 07:50 UTC, dongsik-yoo commented on test/app/common/timezone.spec.js
> +        var offset1 = tz.getOffsetByTimezoneCode('America/New_York', new Date(2020, 10, 1, 13));
여러 개를 검증할 필요가 있을까요? 오프셋이 변하는 시기는 확실하니까요.

2020-11-27 07:50 UTC, dongsik-yoo commented on test/app/common/timezone.spec.js
> +        expect(tz.isNativeOsUsingDSTTimezone()).toBe(false);
요건 썸머타임이 있는 지역에서는 실패할 테스트예요.

2020-12-09 09:00 UTC, jungeun-cho commented on src/js/common/timezone.js
> +    STANDARD_TO_DST: 1,
변수 네이밍을 다시 해야겠어요. 
차이나는 offset hour 시간이 아니라 표준에서 DST인지, DST에서 표준으로 변경되는 지점인지를 나타내는 값이라서요.

음... `offsetChanged`는 어떻할까요?

2020-12-09 09:35 UTC, jungeun-cho commented on src/js/common/timezone.js
> + * @param {string} timezoneCode - timezone code (such as 'Asia/Seoul', 'America/New_York')
```
timezoneName is the time zone names of the IANA time zone database, such as 'Asia/Seoul', 'America/New_York'.
```
이렇게 설명하는건어떻할까요?

2020-12-09 09:48 UTC, jungeun-cho commented on src/js/common/timezone.js
> +    var timezoneCode = timezoneObj.timezone;
인터페이스 확인 부탁드립니다.
```js
    timezone: {
      zones: [
        {
          timezoneName: 'Asia/Seoul',
          displayLabel: 'GMT+09:00',
          tooltip: 'Seoul'
        },
        {
          timezoneName: 'America/New_York',
          displayLabel: 'GMT-05:00',
          tooltip: 'New York',
        }
      ],
      offsetCalculator: function(timezone, timestamp){
        // e.g. +09:00 => -540, -04:00 => 240
        return moment.tz.zone(timezone).utcOffset(timestamp);
      },
    }
```

2020-12-09 09:55 UTC, jungeun-cho commented on src/js/common/timezone.js
> + *
```js
Compare the start and end times to see if the time zone is changing.
```
이 추가됩니다.

2020-12-09 10:20 UTC, jungeun-cho commented on src/js/common/timezone.js
> +            setByTimezoneOption = false;
네, 기존에 무조건 offset 값으로 계산되었는데,  오프셋이 같으면 이 옵션을 켜줄 필요가 없어서요.

2020-12-09 11:34 UTC, jungeun-cho commented on test/app/common/timezone.spec.js
> +        expect(tz.isNativeOsUsingDSTTimezone()).toBe(false);
삭제합니다.

2020-12-10 07:35 UTC, jungeun-cho commented on src/js/model/schedule.js
> +    var isOffsetChanged = checkOffset.isOffsetChanged;
start와 end 사이에 오프셋이 변경되었는지 체크하여 오프셋 차이가 얼마나는지, dst에서 표준시인지, 표준시에서 dst로 가는지에 대한 정보를 나타냅니다.
isChanged(변경되었는지)가 더좋을것같습니다.

2020-12-10 14:08 UTC, dongsik-yoo commented on src/js/common/timezone.js
> +    timestamp = !util.isUndefined(timestamp) ? timestamp : Date.now();
👍 이거 빼먹을 뻔했네요! 멋져부러!

2020-12-10 14:13 UTC, dongsik-yoo commented
기존의  `timezones`가 들어오는 경우도 스크립트 에러나지 않고 `timezone.zones`쪽으로 타도록 처리되어야 할 것 같은데, 코드에서 못봤네요. `timezones` 옵션을 처리할 수 있어야 메이저 버전이 올라가지 않을 수 있습니다. 확인 부탁 드려요.

2020-12-10 14:33 UTC, jungeun-cho commented
> 기존의 `timezones`가 들어오는 경우도 스크립트 에러나지 않고 `timezone.zones`쪽으로 타도록 처리되어야 할 것 같은데, 코드에서 못봤네요. `timezones` 옵션을 처리할 수 있어야 메이저 버전이 올라가지 않을 수 있습니다. 확인 부탁 드려요.

네, 하위버전 호환가능하도록 기존에 사용된 `timezones`옵션 연동하도록 하겠습니다.:)

2020-12-23 01:57 UTC, dongsik-yoo commented on examples/example13-timezone.html
> +  <title>TOAST UI Calendar Timezone DEMO Wow</title>
Wow는 기쁨의 표시인가요?ㅎㅎ

2020-12-23 01:57 UTC, dongsik-yoo commented on examples/example13-timezone.html
> +  <title>TOAST UI Calendar Timezone DEMO Wow</title>
아니면 요새 wow하고 있다고 티내는 것??ㅎㅎ

2020-12-23 01:59 UTC, dongsik-yoo approved these changes
고생 많으셨습니다!

2020-12-23 02:06 UTC, jungeun-cho commented on examples/example13-timezone.html
> +  <title>TOAST UI Calendar Timezone DEMO Wow</title>
오모나... 지우도록하겠습니다.

2020-12-23 02:29 UTC, merged