feat: milestone panel component
nhn/tui.calendar pull request #775
Opened 2021-04-09 09:42 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

* job
  * add preact babel tsconfig option
  * `milestone` component
    * add milestone panel component
      * add grid component
      * add schedules component

* example
  * open `tui.calendar` project
  * `npm run storybook` in `/apps/calendar`
  * `Panel-milestone` in storybook

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-04-09 09:42 UTC, seonim-ryu commented
Can one of the admins verify this patch?

2021-04-09 09:55 UTC, lja1018 reviewed
현재 이벤트(일정)를 받아 렌더링 하는 부분까지 작업했습니다.
이어서 패널의 높이에 따라 일정을 숨기고 +x를 표시하는 컴포넌트 개발 예정입니다.

2021-04-09 09:55 UTC, lja1018 commented on apps/calendar/tsconfig.json
> +    "jsxFragmentFactory": "Fragment",
> https://preactjs.com/guide/v10/typescript/#typescript-configuration

타입스크립트 관련 설정을 추가했습니다.
`h` 함수에 대해 unused import 라고 뜨는 부분을 뜨지 않게 해주는 설정입니다.

2021-04-09 09:55 UTC, lja1018 commented on apps/calendar/.eslintrc.js
> +    'react/prop-types': 0,
`plugin:react/recommended`에서 on 되어있어 `FunctionComponent<>` 타입을 지정할 때 에러가 발생하여 off 합니다.

2021-04-12 06:57 UTC, jung-han commented on apps/calendar/src/components/panel/grid.tsx
> +const DEFAULT_GRID_STYLE = {
어떤 스타일이 인라인(?) 스타일로 쓰이는 곳과 클래스로 분리되서 사용되는 것 같은데 구분되는 기준이 어떤걸까요?

2021-04-12 06:58 UTC, jung-han commented on apps/calendar/src/components/panel/milestone.tsx
> +import range from 'tui-code-snippet/array/range';
code-snippet 의존은 제거 안하는건가요?

2021-04-12 07:03 UTC, jung-han commented on apps/calendar/src/components/panel/schedules.tsx
> +  const scheduleHeightMap = [0, 0, 0, 0, 0, 0, 0];
`new Array(7).fill(0);`
나 아마 IE에서 지원을 안할거라 이런 형태의 사용이 많아진다면  fill 유틸을 하나 만들어서 사용해도 좋을 것 같습니다.

2021-04-12 07:05 UTC, jung-han commented on apps/calendar/src/css/panel/milestone.css
> +.panel .panel-title,
prefix가 필요해보입니다.

2021-04-12 07:06 UTC, jung-han commented on apps/calendar/src/css/panel/milestone.css
> +  float: left;
음..새로운 캘린더가 어느 정도로 브라우저를 지원하는지는 모르지만 레이아웃을 이제 전체적으로 flex를 사용하도록 바꾸는게 좋지 않을까요?

2021-04-12 07:07 UTC, jung-han commented on apps/calendar/stories/panel.stories.tsx
> +      </Panel>
아무래도 preact를 사용해서 더 좋을 것 같은데..
스토리북을 6.대 사용하는 것으로 알고 있어서
Template 이랑 args를 이용해서 스토리 작성해서 props별로 스토리를 생성하지 않고 테스트할 수 있도록 하는게 좋지 않을까요?

2021-04-12 07:08 UTC, jung-han commented on apps/calendar/src/components/panel/schedules.tsx
> +        const scheduleStyle = getScheduleStyle(event, startDate, scheduleHeightMap);
바로 작성해도 괜찮을 것 같습니다.

2021-04-12 07:12 UTC, jung-han commented on apps/calendar/src/components/panel/schedules.tsx
> +  if (startDay <= endDay) {
이 세 조건이 겹칠 것 같지는 않고 결국

left, width, top을 지정해주는 것과 heightMap을 만들어주는 건데 각각 코드를 분리해서 작성하거나 
left를 가져오는 함수 width를 가져오는 함수 top을 가져오는 함수 각각 분리해서 복잡도를 낮추는건 어떤가요?

2021-04-12 07:12 UTC, jung-han approved these changes
완료입니다~

2021-04-12 08:10 UTC, dotaitch approved these changes
리뷰 완료합니다.

2021-04-12 08:10 UTC, dotaitch commented on apps/calendar/src/components/panel/grid.tsx
> +const WIDTH_PER_DAY = 100 / 12;
`12` 같은 경우는 매직 넘버로 많이 쓰일 것 같은데 상수 처리를 하는 건 어떨까요?

2021-04-12 08:21 UTC, shiren reviewed
수고하셨습니다.

2021-04-12 09:27 UTC, dongsik-yoo reviewed
리뷰 완료합니다. 수고하셨습니다.

2021-04-12 16:28 UTC, jungeun-cho commented on apps/calendar/stories/panel.stories.tsx
> +      </Panel>
@jung-han 
https://storybook.js.org/docs/preact/writing-stories/args
이 내용 말하는것인지요?!

2021-04-12 16:31 UTC, jungeun-cho commented on apps/calendar/src/css/panel/milestone.css
> +.panel .panel-title,
웹팩 설정으로 번들 시 자동적으로 prefix를 추가해줍니다~!

2021-04-13 02:19 UTC, jungeun-cho reviewed
리뷰완료했습니다.
고생많았어요~!

2021-04-13 02:19 UTC, jungeun-cho commented on apps/calendar/src/components/panel/schedules.tsx
> +export interface Task {
Task 타입으로 지정하기 보다는 events.d.ts 파일로 타입정의 부분을 옮겨주세요.
일정에 대한 타입정의는 공통으로 자주 사용될 것입니다.

Event, Schedule, EventItem, CalendarEvent 등 일정에 대한 용어를 정의할 필요가 있겠습니다.

```ts
interface BaseEvent {
  start: TZDate;
  end: TZDate;
  /* ... */
}

interface MilestoneEvent extends BaseEvent {
  type: 'milestone';
};
```

2021-04-13 02:19 UTC, jungeun-cho commented on apps/calendar/src/components/panel/schedules.tsx
> +function getScheduleStyle({ start, end }: Task, minDate: number, scheduleHeightMap: number[]) {
이 함수는 로직을 분리해서 린트룰 해제를 제거하는게 좋겠습니다.

2021-04-13 02:19 UTC, jungeun-cho commented on apps/calendar/src/components/panel/schedules.tsx
> +        startDay === Day.SUN ? toPercent(100) : toPercent(((7 - startDay) * 2 - 1) * WIDTH_PER_DAY),
매직 상수 부탁합니다.

2021-04-13 02:19 UTC, jungeun-cho commented on apps/calendar/src/components/panel/schedules.tsx
> +  const startDate = gridInfoList[0].getDate();
@lja1018 
이부분은 고려 부탁합니다.

2021-04-13 02:19 UTC, jungeun-cho commented on apps/calendar/src/css/panel/milestone.css
> +  float: left;
기존 캘린더 브라우저 지원은 IE9부터 인데요. 브라우저 점유율 확인해보고 지원 버전을 고려하도록하겠습니다.

2021-04-13 02:21 UTC, jungeun-cho requested changes
피드백 반영하고 재리뷰 요청주세요~!

2021-04-19 05:54 UTC, js87zz commented on apps/calendar/src/components/panelgrid/milestone.tsx
> +const PANEL_MILESTONE_CLASS_NAME = cls('panel-milestone');
개인적인 의견인대 이미 클래스네임에서 어떤 스타일 클래스인지 잘 드러나는데 상수로 또 정의할 필요가 있나요? 바로 써도 괜찮을 것 같아서요

2021-04-19 05:56 UTC, js87zz commented on apps/calendar/src/components/panelgrid/panelEvents.tsx
> +  const scheduleTopList = scheduleHeightMap.filter((_, index) => start <= index && index <= end);
`start <= index && index <= end)` 이 조건은 유틸로 만들어도 좋을 것 같네요~!

2021-04-19 05:58 UTC, js87zz approved these changes

2021-04-19 06:39 UTC, dongsik-yoo reviewed
리뷰완료합니다. 수고하셨습니다.

2021-04-19 06:39 UTC, dongsik-yoo commented on apps/calendar/test/app/time/panelEvent.spec.ts
> +      gridInfoList = [12, 13, 14, 15, 16].map((d) => createDate(2021, 4, d));
요런거 테스트할 때 다른 타임존에서도 테스트가 통과하는지 한번씩 확인해볼 필요가 있습니다.

2021-04-19 06:39 UTC, dongsik-yoo commented on apps/calendar/types/events.d.ts
> +export interface MilestoneEvent extends BaseEvent {
다른 모델은 없어도 되나요? 제목이나 바디나 기존  Schedule 객체가 담고 있던 내용들입니다.

2021-04-19 06:39 UTC, dongsik-yoo commented on apps/calendar/types/panel.d.ts
> +export type PanelType = 'daygrid' | 'timegrid';
Panel은 레이아웃 컴포넌트 개념으로 사용되고, 자식에 어떠한 컴포넌트도 올 수 있게끔 되었어요. 그러므로 자식 컴포넌트에 따라 Panel의 타입이 정해질 필요가 있을까요?  PanelName도 마찬가지입니다만 식별자로 문자열이 필요하다면 타입까지 지정하진 않아도 되지 않을까요?

2021-04-19 09:41 UTC, shiren approved these changes
수고하셨습니다.

2021-04-19 09:41 UTC, shiren commented on apps/calendar/src/time/panelEvent.ts
> +export const getPanelEventInfo = ({
이건 함수명이 조금 바뀌어야 할 것 같아요. 내용에 비해 함수명이 너무 포괄적이에요.

2021-04-19 23:41 UTC, jungeun-cho approved these changes
리뷰완료했습니다. 수고하셨어요 👍

2021-04-19 23:41 UTC, jungeun-cho commented on apps/calendar/src/time/datetime.ts
>   */
코멘트 필요없을것같습니다. 이미 함수 정의 시 타입을 명시해놓았습니다.

2021-04-23 01:53 UTC, lja1018 commented on apps/calendar/types/events.d.ts
> +export interface MilestoneEvent extends BaseEvent {
일단 마일스톤 이벤트만 추가했습니다!

2021-04-23 01:54 UTC, lja1018 commented on apps/calendar/types/panel.d.ts
> +export type PanelType = 'daygrid' | 'timegrid';
음.. 일단 기존에 정의된 타입의 위치만 옮긴거라서요.. 다른 PR에서 수정하겠습니다.

2021-04-23 02:20 UTC, merged