feat: add expand/collapse button
nhn/tui.calendar pull request #777
Opened 2021-04-19 12:16 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [ ] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

* job
  * change to FC (layout.tsx, panel.tsx, panelResizer.tsx)
  * add expand/collapse button

* example
  * open tui.calendar project
  * npm run storybook in /apps/calendar
  * Panel-milestone in storybook

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-04-19 12:17 UTC, seonim-ryu commented
Can one of the admins verify this patch?

2021-04-20 06:54 UTC, dongsik-yoo commented
펼치기 했을 때 빈 버튼은 보이지 않아야 합니다.
![image](https://user-images.githubusercontent.com/26706716/115350983-b83a8d00-a1f0-11eb-9189-2c96174fa6f8.png)

2021-04-20 08:18 UTC, dongsik-yoo reviewed
리뷰 완료합니다. 수고하셨습니다.
린트 에러와 테스트 파일에 타입에러 있습니다.

2021-04-20 08:18 UTC, dongsik-yoo commented on apps/calendar/src/components/panelgrid/panelEvents.tsx
> +  useEffect(() => {
useEffect 내부에서 사용되는 함수들은 유틸리티 함수로 뽑아내면 코드 세로 길이가 짧아져서 보기가 좀 더 쉽지 않을까요?

2021-04-20 08:18 UTC, dongsik-yoo commented on apps/calendar/src/components/panelgrid/panelGrid.tsx
> +      type: UPDATE_PANEL_HEIGHT_TO_MAX,
Panel 높이가 높아지더라도 최대치(`maxExpandableHeight`)까지만 커지고 세로 스크롤이 되어야 하는데요, 기능 테스트 되었나요?

2021-04-20 08:18 UTC, dongsik-yoo commented on apps/calendar/src/time/datetime.ts
> +export function isEventWithinRange({ start, end }: BaseEvent, startDate: number, endDate: number) {
개인적으론 datetime은 Event 타입은 사용하지 않고 TZDate만 쓰도록 하는 것이 어떨까 합니다. 호출하는 쪽에서 TZDate를 넘겨주면 되니까요. 모듈의 성격과 타입이 섞이지 않도록 하는게 관리 측면에서도 좋지 않을까요?

2021-04-20 08:18 UTC, dongsik-yoo commented on apps/calendar/src/util/array.ts
> +export function isSameArray<T>(array1: Array<T>, array2: Array<T>): boolean {
렌더링할 때마다 불리게 될텐데 레퍼런스 비교만으로는 안되는 건가요? 루프가 좀 많아 보여서요. 사용처를 보니 길이가 중요한 요소로 보이는데요, 의견이니 참고만 해주세요.

2021-04-21 06:39 UTC, jungeun-cho commented
> 펼치기 했을 때 빈 버튼은 보이지 않아야 합니다.
> ![image](https://user-images.githubusercontent.com/26706716/115350983-b83a8d00-a1f0-11eb-9189-2c96174fa6f8.png)

접기 아이콘이 깨지는것같네요.

2021-04-22 11:10 UTC, jungeun-cho requested changes
Layout  컴포넌트에서 제공하는 액션은 resizeStart, resizeEnd, resizeHeight, resizeWidth 처럼 레이아웃에 관한 액션만 필요할 것같습니다. 저장된 상태는 기존처럼 하위 패널 컴포넌트들의 사이즈 정보가 되고요.
패널의 사이즈(높이/너비)에 따라 layout 내 하위 패널 컴포넌트들의 사이즈가 변경되니까요.

---

기존 Layout 스토리 깨지는것도 확인부탁합니다. 정상적으로 나와야해요.

2021-04-22 11:10 UTC, jungeun-cho commented on apps/calendar/src/components/panelgrid/milestone.tsx
> +  }, [dispatch]);
INIT_STATE 할 필요가 있나요? 사이즈가 변경되면 UPDATE_PANEL_HEIGHT로 패널의 높이를 변경해주면되지 않을까요?
PANEL에 높이에 따라 마일스톤 높이가 정해지면 될 것 같아서요.
일정이 많아서 더 보여주어야하면 PANEL의 높이를 변경해주고요. 패널 그리드 열고/닫기 할때도 패널의 높이가 변경되면서 Layout에 하위 패널 컨포넌트들에 대한 높이값이 재계산되고요.

---

일정 높이값은 저장하지 않아도 될것같습니다.

2021-04-23 07:03 UTC, lja1018 commented on apps/calendar/src/util/array.ts
> +export function isSameArray<T>(array1: Array<T>, array2: Array<T>): boolean {
레퍼런스 비교로 수정했습니다!

2021-04-23 07:07 UTC, lja1018 commented on apps/calendar/stories/panel.stories.tsx
>  const Template: Story = (args) => (
스토리북 관련 디펜던시들 버전 업데이트 했습니다!

2021-04-23 07:08 UTC, lja1018 commented on apps/calendar/src/util/array.ts
> +export function isSameArray<T>(array1: Array<T>, array2: Array<T>): boolean {
레퍼런스 비교로 수정하여 제거했습니다.

2021-04-23 07:54 UTC, lja1018 commented on apps/calendar/src/components/panelgrid/milestone.tsx
> +        top = getTop(Day.SUN, endDay, map);
현재 일정 컴포넌트를 작업하면서 grid 정보에 맞게 top을 계산하도록 적용하였습니다. 다른 PR에서 제거될 부분입니다!

2021-04-27 06:23 UTC, lja1018 commented
@dongsik-yoo 
남은 부분은 다음 작업에서 대부분 제거될 부분이라 다른 PR에서 작업하겠습니다!

2021-05-10 02:37 UTC, merged