feat : store structure
nhn/tui.calendar pull request #788
Opened 2021-04-27 10:56 UTC by jungeun-cho

### Please check if the PR fulfills these requirements
- [ ] It's submitted to right branch according to our branching model
- [ ] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description
* [x]  The type of state and actions should be inferred well.

**Interface**
* [x] Depending on the parameter passed when using `useStore` to retrieve the value in the store, the resulting value is different.
* 1) 
```ts
const AppContainer = () => {
  const { state, actions } = useStore();
  const { todos, counter } = state;
  const { 
    todos: todoActions,
    counter: counterActions
  } = actions;
            
   /* ... */
};
```
* 2) If the string module name is passed, the state and actions of the module are directly returned.
```ts
const TodoListContainer = () => {
  const { state, actions } = useStore('todos');
  const { input, todos } = state; // No need to access state.todos
  const { toggleCheck, changeInput, insert, remove } = actions; // No need to access actions.todos

  /* ... */
};
```
* 3) If you pass the module name as an array, it returns the state and actions for the selected module.
```js
 const TodoListContainer = () => {
   const { state, actions } = useStore(['todos', 'counter']);
   const { counter, todos } = state;
   /* ... */
 };
```

* [x] For components that use only actions, use `useActions`
```js
const CounterButtons: FunctionComponent = () => {
  const { increment, decrement } = useActions('counter');

  /*...*/
};
```

### Future considerations
* Component re-rendering improvement for each module used

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-04-28 05:31 UTC, jung-han commented on apps/calendar/src/components/hooks/router.ts
> +export function useCreateRouter({ initialView, components }: Props): Router {
❗️\ `use`에 `create`가 붙어서 네이밍이 동사 + 동사 형태가 되서 어색한 이름인 것 같습니다.

2021-04-28 05:32 UTC, jung-han commented on apps/calendar/src/components/hooks/store.ts
> +// define calendar actions
주석 없어도 될 것 같습니다

2021-04-28 05:34 UTC, jung-han commented on apps/calendar/src/components/toolbar/Toolbar.tsx
> +const Button: FunctionComponent<ButtonProps> = ({ name, onClick, value, className }) => {
버튼은 별도 컴포넌트로 분리해서 다른곳에서 재사용하기 힘든가요?_?

2021-04-28 05:35 UTC, jung-han commented on apps/calendar/src/components/toolbar/Toolbar.tsx
> +    <Fragment>
`<>, </>`도 될 것 같습니다.

2021-04-28 05:36 UTC, js87zz commented on apps/calendar/src/components/hooks/router.ts
> +  const goto = (newViewName: string) => setViewName(newViewName);
개인적인 의견인대..뭔가 `goTo~~`로 표현이 이어서 나와야될 것 같아요ㅎㅎ

2021-04-28 05:38 UTC, jung-han commented on apps/calendar/src/components/toolbar/Toolbar.tsx
> +  };
음..선호도에 따라 다르겠지만 저는 props를 그냥 명시적으로 컴포넌트에 넣어주는 게 더 좋을 것 같습니다.

2021-04-28 05:38 UTC, jung-han commented on apps/calendar/src/components/toolbar/Toolbar.tsx
> +      return `${cls('toolbar-button')} ${currentViewName === viewName ? cls('active') : ''}`;
화살표 함수로 바로 리턴할 수 있을 것 같습니다.

2021-04-28 05:39 UTC, jung-han commented on apps/calendar/src/components/toolbar/Toolbar.tsx
> +    return acc;
`return router ? [...acc, ({ ...})] : acc;` 으로 줄여서 작성할 수 있을 것 같습니다

2021-04-28 05:41 UTC, jung-han commented on apps/calendar/src/components/view/Main.tsx
> +import StoreProvider from '@src/components/provider/storeProvider';
그냥 Provider라고 하는게 더 자연스러울 것 같습니다

2021-04-28 05:42 UTC, jung-han commented on apps/calendar/src/modules/events.ts
> +type Events = {
이 타입은 InitialState가 되어야 하는 것 같습니다~

2021-04-28 05:47 UTC, jung-han commented on apps/calendar/src/modules/options.ts
> +const optionsData = {
options라고 해도 될 것 같습니다.

2021-04-28 05:48 UTC, jung-han commented on apps/calendar/src/modules/options.ts
> +  state: ({ options }: InitStoreData) => ({ options: deepMergedCopy({}, options) } as Option),
deepMergedCopy대신 스프레드로 작성해도 괜찮지 않을까요!

2021-04-28 05:52 UTC, js87zz commented on apps/calendar/src/components/hooks/store.ts
> +export function useCreateStore(store: Store<CalendarState>) {
❗️\실제 동작과 네이밍이 안맞는 것 같아요. 사실 store는 이미 만들어진거고, store와 state를 연결하는 역할이고 실제로 반환값도 state를 반환하고 있어서, 명확한 네이밍이 되면 좋을 것 같습니다

2021-04-28 05:55 UTC, jung-han commented on apps/calendar/test/app/components/hooks/router.spec.tsx
> +    }
이 코드는 없어야 하지 않나요?

2021-04-28 05:56 UTC, js87zz commented on apps/calendar/src/components/hooks/store.ts
> +    state: useMemo(() => getState(state, names), [state, names]),
❗️\ `state`에 접근하려면 함수 형태로 접근해야 하는건가요? 어떤 의도인가요?

2021-04-28 05:57 UTC, jung-han commented on apps/calendar/src/components/hooks/router.ts
> +  const goto = (newViewName: string) => setViewName(newViewName);
goto 자체가 다른 언어에서 사용되는 예약어라 조금 어색한 느낌이 있긴 하네요..

2021-04-28 05:58 UTC, jung-han commented on apps/calendar/src/components/hooks/store.ts
> +type ActionType<A> = A extends keyof CalendarActions ? CalendarActions[A] : never;
제네릭들도 S, A로 작성하는게 아니라 명확하게 의미를 나타내는 단어로 작성되면 좋을 것 같아요

2021-04-28 05:59 UTC, jung-han commented on apps/calendar/src/components/provider/storeProvider.tsx
> +const StoreProvider: FunctionComponent<Props> = (props) => {
그냥 Provider라고 하는 것은 어떤가요?

2021-04-28 05:59 UTC, jung-han commented on apps/calendar/src/store/store.ts
> +  state = {} as S;
여기도 S대신 Store같은 명확한 제너릭 명이 사용되면 좋을 것 같습니다~

2021-04-28 06:03 UTC, js87zz commented on apps/calendar/src/components/hooks/store.ts
> +    actions: useMemo(() => getActions(calendarActions, names), [names]),
❗️\ actions를 반환하는 이유가 있을까요? 실제 컴포넌트에서는 dispatch 함수만 있으면 될 것 같고, 액션 자체에 직접 접근하는 일은 없을 것 같은데 다른 이유가 있나요?

2021-04-28 06:04 UTC, jung-han commented on apps/calendar/types/option.d.ts
> +type Options = Option; // @TODO: Option 정의 필요
이건 이후에 여기서 정의되는거죠?

2021-04-28 06:06 UTC, jung-han commented on apps/calendar/test/types/mock.d.ts
> +type TodoItem = {
개인 취향차이긴 할 것 같지만...어쩌피 한 파일에서 사용되는 타입들이라면 같이 위치해도 괜찮을 것 같아요~

2021-04-28 06:08 UTC, js87zz commented on apps/calendar/src/components/provider/storeProvider.tsx
> +  return <StoreContext.Provider value={state}>{children}</StoreContext.Provider>;
❗️\store가 아니라 state만 주입하네요. store 자체를 주입해야 하지 않나요?

2021-04-28 06:09 UTC, jung-han commented on apps/calendar/test/module/modules.ts
> +      store.dispatch('counter/increment');
음....이렇게 작성하면 state명과 action명이 작성되는 것 같은데 타입으로 검증이 가능한가요?

2021-04-28 06:11 UTC, jung-han commented on apps/calendar/test/app/util/utils.spec.ts
> +    expect(arr).toEqual([1, 2, 3, 4]);
그냥 값을 넣어서 비교하는 것보다 카피한 배열이 참조가 다르고 값이 같은지만 봐도 좋을 것 같습니다!

2021-04-28 06:13 UTC, jungeun-cho commented
ok to test

2021-04-28 06:13 UTC, jung-han commented on apps/calendar/stories/view.stories.tsx
> +    <div className={cls('layout')} style={{ overflow: 'hidden', height: '100%' }}>
스타일에 작성된 코드도 layout 클래스에 포함시켣도 될 것 같습니다

2021-04-28 06:13 UTC, jung-han commented on apps/calendar/stories/view.stories.tsx
> +    <div className={cls('layout')} style={{ overflow: 'hidden', height: '100%' }}>
아 스토리북 코드군요

2021-04-28 06:14 UTC, js87zz commented on apps/calendar/src/components/toolbar/Toolbar.tsx
> +    [currentViewName]
`useCallback`으로 꼭 감싸야하나요? `currentViewName`이 변경되는 경우 이외에도 리렌더링이 되는 경우가 없다면 감싸지 않아도 될 것 같아서요

2021-04-28 06:16 UTC, js87zz commented on apps/calendar/src/components/toolbar/Toolbar.tsx
> +  };
저도 JSX에 넣는게 구조 파악에 더 용이할 것 같아요

2021-04-28 06:21 UTC, js87zz commented on apps/calendar/src/components/view/Main.tsx
> +  const ToolbarComponent = router.getComponent('toolbar');
이런 패턴은 가독성에 안좋은 것 같아요. 정확히 어떠한 컴포넌트가 렌더링되는지 알기 어려우니까요. 컴포넌트 자체에서 props에 따라 렌더링을 다르게 하는 건 어떤가요? 어차피 context에서 정보는 다 내려줄테니까요.

2021-04-28 06:24 UTC, js87zz commented on apps/calendar/src/store/store.ts
> +  payloadActions: PayloadActions = {};
`payload`프리픽스는 없어도 괜찮을 것 같아요ㅎㅎ

2021-04-28 06:26 UTC, js87zz commented on apps/calendar/src/store/store.ts
> +  setModule(module: StoreModule) {
❗️\ `setModule`의 역할이 state와 action을 설정하는건대 다른 네이밍이 되어야될 것 같아요

2021-04-28 06:28 UTC, js87zz commented on apps/calendar/src/store/store.ts
> +  setModule(module: StoreModule) {
그리고 의존성 주입 방법의 메서드로 모듈을 주입하는 이유가 있을까요? `setModule`이란 메서드가 외부로 제공되는건가 해서요

2021-04-28 06:30 UTC, js87zz commented on apps/calendar/src/components/hooks/store.ts
> +  store.setStateUpdater(setCalendarState);
❗️\ 나중에 여기서 `setCalendarState`로 업데이트를 하는게 아니라 별도의 observer 모듈을 만들어서 관리하면 필요한 컴포넌트만 렌더링할 수 있지 않을까 싶네요.

2021-04-28 06:32 UTC, js87zz commented on apps/calendar/src/store/store.ts
> +  getValue(names?: ModuleKeys | ModuleKeys[]) {
이 메서드가 꼭 필요한 메서드인가요~?

2021-04-28 06:34 UTC, js87zz commented on apps/calendar/src/util/storeHelper.ts
> +export function getState(state: Record<string, any>, names?: ModuleKeys | ModuleKeys[]) {
❗️\ 이 함수는 store 클래스에 있어야 하지 않나요? 관련 코드들이 분산되어 있어서 오히려 응집도가 떨어지는 것 같아요. 아마 context에 state만 주입해서 이렇게 분리된것 같은데 store자체를 주입하면 클래스로 이동해도 문제 없을 것 같아요

2021-04-28 06:36 UTC, js87zz commented on apps/calendar/test/app/components/hooks/router.spec.tsx
> +    const { result } = setup();
이 코드가 다 실행되는데 `beforeEach`에서 실행하면 되지 않을까요?

2021-04-28 06:40 UTC, js87zz commented on apps/calendar/test/module/modules.ts
> +      store.dispatch('counter/increment');
❗️\이게 제대로 추론되지 않으면 굉장히 위험할 것 같네요. 실제로 그냥 string으로 추론되고 있어서 요거는 타입을 정형화 시켜야될 것 같네요

2021-04-28 06:43 UTC, js87zz requested changes
리뷰 완료입니다. store를 사용하는 부분이 더 개선되면 좋을 것 같아요. (hook에서 제공하는 정보라던가 컨텍스트에 주입하는 정보 등)
관련된 사항은 코멘트 남겼으니 확인 부탁드려요!

2021-04-28 07:10 UTC, lja1018 approved these changes
리뷰 완료합니다.

2021-04-28 07:10 UTC, lja1018 commented on apps/calendar/src/util/utils.ts
> +  keys.forEach((prop) => {
`prop` 대신 `key`는 어떠신가요??

2021-04-28 08:50 UTC, shiren approved these changes
수고하셨습니다.

2021-04-28 08:50 UTC, shiren commented on apps/calendar/src/components/view/Main.tsx
> +  const ToolbarComponent = router.getComponent('toolbar');
결국 그 컴포넌트 내부에서 이런 코드가 있어야하는건 동일하지만 이 방법은 내부 숨기는게 좋을 것 같아요.
type값에 따라 내부컴포넌트를 선택하는 컴포넌트요. 이렇게하면 잘못된 상황 대응에 좋을 것 같아요.

2021-04-28 09:23 UTC, dongsik-yoo reviewed
리뷰 완료합니다. 수고하셨어요.

2021-04-28 09:23 UTC, dongsik-yoo commented on apps/calendar/src/modules/events.ts
> +const initialState: Events = { events: [] };
타입 이름이 State가 되는게 어울리겠네요.

2021-04-28 09:23 UTC, dongsik-yoo commented on apps/calendar/src/store/store.ts
> +    };
Promise로 비동기처리 하려면 필요하긴 하겠네요.

2021-04-28 09:23 UTC, dongsik-yoo commented on apps/calendar/src/util/utils.ts
> +export function forEach<T extends object, K extends Extract<keyof T, string>, V extends T[K]>(
code-snippet은 안 쓰기로 했나요?

2021-04-28 10:04 UTC, jungeun-cho commented on apps/calendar/src/components/hooks/router.ts
> +export function useCreateRouter({ initialView, components }: Props): Router {
음.. 커스텀 훅 네이밍은 `use`로 시작되게 되어있어요 (린트룰에도 잡히구요~..)

2021-04-28 10:10 UTC, jungeun-cho commented on apps/calendar/src/components/hooks/router.ts
> +  const goto = (newViewName: string) => setViewName(newViewName);
`go`로 변경합니다.

2021-04-28 10:34 UTC, jungeun-cho commented on apps/calendar/src/components/hooks/store.ts
> +}
타입스크립트 함수 오버로드에요~! 인자타입과 반환타입 시그니쳐를 정할수 있습니다.

2021-04-28 10:40 UTC, jungeun-cho commented on apps/calendar/src/components/hooks/store.ts
> +    actions: useMemo(() => getActions(calendarActions, names), [names]),
여기서 반환된 액션은 `(payload: any) => void` 액션이에요
`dispatch({type: actionName, payload})`를 사용하지 않고 actionName으로 호출해서 사용합니다. 이러한 인터페이스는 사전 협의된 내용이고 actionName을 직접 호출하는게 더 직관적이라고 판단했어요.

2021-04-28 10:47 UTC, jung-han commented on apps/calendar/src/components/hooks/router.ts
> +export function useCreateRouter({ initialView, components }: Props): Router {
넵넵ㅎㅎ 그래서 보통 훅을 생성할때 use(명사형태의 사용하는 정보) 이렇게 생성해서 말씀드린거였어요. useQuery, useInputState, useMutation 이런식으로 사용하는 게 규칙인거 같아서요. 뒤 정보가 함수에서 전달하려는 정보를 나타내야할 것 같습니다.

2021-04-28 11:06 UTC, jungeun-cho commented on apps/calendar/src/components/toolbar/Toolbar.tsx
> +  };
@dongsik-yoo 말씀하신 상황에선 타입 추론이 잘되지 않습니다.

컴포넌트에 props를 명시적으로 나열하도록 수정합니다.

2021-04-28 11:22 UTC, jungeun-cho commented on apps/calendar/src/store/store.ts
> +  getValue(names?: ModuleKeys | ModuleKeys[]) {
앗 지우지 않았어요.

2021-04-28 11:25 UTC, jungeun-cho commented on apps/calendar/src/util/utils.ts
> +export function forEach<T extends object, K extends Extract<keyof T, string>, V extends T[K]>(
네 코드 스니펫에 있는 사용하는 코드만 가져와서 사용하도록 했습니다.
기존에 작성하셨던 코드 스니펫에서 불러와서 사용하는것도 옮길 예정입니다.

2021-04-28 12:13 UTC, jungeun-cho commented on apps/calendar/types/option.d.ts
> +type Options = Option; // @TODO: Option 정의 필요
네 이후에 정의됩니다.

2021-04-29 02:09 UTC, js87zz commented on apps/calendar/src/components/hooks/store.ts
> +    actions: useMemo(() => getActions(calendarActions, names), [names]),
액션을 실행하는 단일 함수(dispatch)를 노출시키냐 동작이 정의된 객체(action)를 노출시켜 호출하느냐 차이인 것 같은대요. 동작이 정의된 action객체들은 오히려 캡슐화하여 완전히 감추는게 더 좋을 것 같은데..어떠신가요? 어차피 타입으로 인해 어떤 액션을 호출하는지는 충분히 직관적일 것 같아서요

2021-04-29 14:54 UTC, jungeun-cho commented on apps/calendar/src/components/hooks/store.ts
> +    state: useMemo(() => getState(state, names), [state, names]),
객체 형태로 접근 가능합니다.
```js
const { state } = useStore(); // state.todos, state.counter 등 state에 들어있는 모듈들의 모든 상태를 가져옵니다.
const {.state } = useStore('todos'); // todos 모듈에 있는 state값을 가져옵니다.
```

2021-04-29 15:06 UTC, jungeun-cho commented on apps/calendar/src/components/hooks/store.ts
> +export function useCreateStore(store: Store<CalendarState>) {
`useCalendarState`로 변경합니다.

2021-04-29 15:06 UTC, jungeun-cho commented on apps/calendar/src/components/hooks/router.ts
> +export function useCreateRouter({ initialView, components }: Props): Router {
useCalendarState로 변경합니다.

2021-04-29 15:10 UTC, jungeun-cho commented on apps/calendar/src/components/provider/storeProvider.tsx
> +  return <StoreContext.Provider value={state}>{children}</StoreContext.Provider>;
현재 context에는 state만 담아 사용합니다. 실제 리렌더링이 필요한 곳은 state만 관련이 있고 액션만 사용하는 곳에서 리렌더링하지 않도록 하기 위함입니다.

2021-04-29 15:19 UTC, jungeun-cho commented on apps/calendar/test/app/components/hooks/router.spec.tsx
> +    const { result } = setup();
act() 함수와 함께 사용 시 같은 스코프 내에 존재해야합니다.

2021-04-29 15:33 UTC, jungeun-cho commented on apps/calendar/src/store/store.ts
> +  setModule(module: StoreModule) {
뷰 컴포넌트마다 사용하는 모듈이 다를 수 있는데요. 공통적으로 사용하는 모듈은 내부적으로 지정되어있을 것이며 뷰 컴포넌트에서 사용하는 모듈에 대해서는 주입받을 수 있도록 할 예정입니다.

모듈에 대한 state, action을 설정하므로 setModule이라고 해도 문제없다고 생각합니다. 혹시 더 좋은 네이밍이 있을까요?

2021-04-30 00:45 UTC, jungeun-cho commented on apps/calendar/src/modules/events.ts
> +type Events = {
EventsState로 변경합니다.

2021-04-30 00:46 UTC, jungeun-cho commented on apps/calendar/src/modules/events.ts
> +const initialState: Events = { events: [] };
EventsState로 타입명을 변경합니다.

2021-04-30 01:21 UTC, jungeun-cho commented on apps/calendar/src/util/storeHelper.ts
> +export function getState(state: Record<string, any>, names?: ModuleKeys | ModuleKeys[]) {
actions은 모듈 스코프에서 관리하고 state만 컨텍스트에서 관리하는데요. 분리한 이유는 actions만 사용하는 곳에서 리렌더링되지 않도록 하기 위함입니다. `useActions`도 그때문에 사용되구요. 
만약 store를 넘기게된다면 현재로선 모듈 스코프에서 정의된 calendarActions랑 두 개를 관리하게 됩니다.
만약 store로 변경된다면  actions만 사용하는 곳에서 리렌더링 방지까지 할 수 있도록 함께 수정되어야할 것같습니다.

2021-04-30 02:43 UTC, jungeun-cho commented on apps/calendar/test/module/modules.ts
> +      store.dispatch('counter/increment');
dispatch 메소드에서 내부적으로 유효한 actionType인지 체크하고있는데요. dispatch에 받을수있는 액션타입도 정의해놓는게 좋을것같습니다.
추가해놓을께요~!

2021-04-30 05:51 UTC, js87zz commented on apps/calendar/src/store/store.ts
> +  setModule(module: StoreModule) {
그럼 스토어가 루트 스토어가 있고 하위에 모듈 단위의 스토어가 있는 걸로 이해되는데 이 둘을 네이밍으로 구분할 수 있으면 될 것 같아요.
rootStore, moduleStore 정도면 어떨까요?

2021-04-30 05:53 UTC, js87zz commented on apps/calendar/src/util/storeHelper.ts
> +export function getState(state: Record<string, any>, names?: ModuleKeys | ModuleKeys[]) {
넵 나중에 렌더링 문제만 최적화되면 store 자체 가지고 actions나 state를 다 꺼내쓸 수 있게 하면 코드 파악할 때나 사용할 때 더 좋을 것 같아요~

2021-04-30 05:56 UTC, js87zz approved these changes

2021-04-30 06:04 UTC, lja1018 approved these changes
리뷰완료합니다.

2021-04-30 07:05 UTC, merged