feat: improve event assignment
nhn/tui.calendar pull request #790
Opened 2021-05-03 12:01 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

* job
  * optimize milestone event
  * apply expand/collapse button to new milestone event
  * remove state, action associated with height map
  * add tests for panelEvent
* example
  * open tui.calendar project
  * npm run storybook in /apps/calendar
  * Panel-'events milestone' in storybook

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-05-03 12:02 UTC, seonim-ryu commented
Can one of the admins verify this patch?

2021-05-04 05:45 UTC, js87zz commented on apps/calendar/src/components/layout.tsx
> +export const PanelStore = createContext<{ state: LayoutState; dispatch: Dispatch }>({
이걸 컴포넌트에서 생성하는 이유가 있나요? 별도 훅으로 빠지는게 맞지 않나 싶어서요

2021-05-04 05:50 UTC, js87zz commented on apps/calendar/src/components/panelgrid/milestone.tsx
> +  const { state, dispatch } = useContext(PanelStore);
매번 넘겨서 가져오는게 아니라 세트로 하나 만들어 두면 좋을 것 같아요

```js
const { state, dispatch } = usePanelContext();
```

2021-05-04 05:58 UTC, js87zz commented on apps/calendar/src/components/panelgrid/panelEvents.tsx
> +    const renderedViewModels = viewModels
내부 코드를 보니까 뷰모델이라는 이름이 안맞는것 같아요. 컴포넌트에서 뷰모델이 등장하는데 실제 역할은 뷰모델이 아니라서 오히여 전반적인 구조나 코드에 대한 가독성이 더 떨어지는 것 같아요. 단순한 프록시 클래스 정도로 밖에 안보이는데 구조를 좀 더 명확히 정리해야할 것 같아요

2021-05-04 06:02 UTC, js87zz commented on apps/calendar/src/components/panelgrid/panelEvents.tsx
> +  return <div className={cls('panel-event-wrapper')}>{renderEvents()}</div>;
이벤트보다 다른 좋은 네이밍은 없나요? 이벤트를 렌더링한다는거 자체가 잘 와닿지 않아서요

2021-05-04 06:05 UTC, js87zz commented on apps/calendar/src/components/panelgrid/panelgrid.tsx
> +  const renderExceedCount = (index: number) => {
전반적으로 이러한 렌더 함수가 많아서 가독성이 떨어지는 것 같아요. 함수형 컴포넌트 형태로 분리해서 표현하는게 구조를 보기 훨씬 좋을 것 같습니다.

2021-05-04 06:06 UTC, js87zz commented on apps/calendar/src/time/panelEvent.ts
> +const isBetweenEvent = (gridInfoList: GridInfoList) => {
반환값이 함수라 네이밍과 안맞는것 같아요~!

2021-05-04 06:08 UTC, js87zz commented on apps/calendar/src/time/panelEvent.ts
> +const isBetweenEvent = (gridInfoList: GridInfoList) => {
개인적으로는 함수 자체의 역할을 분리하는게 더 좋을 것 같습니다.

2021-05-04 06:12 UTC, js87zz commented on apps/calendar/stories/panel.stories.tsx
> +  { start: mon, end: tue },
중복된 데이터는 의도된건가요~?

2021-05-04 06:15 UTC, js87zz requested changes
리뷰 완료입니다! 근데 이전에 작업한 스토어 구조는 적용되지 않은건가요? 뭔가 구현 방식이 좀 다른 느낌이 들어서요

2021-05-04 06:16 UTC, jungeun-cho requested changes
❗/ Panel 컴포넌트 minheight, height 속성 확인바랍니다.
    * layout 스토리에서 정상적으로 속성값으로 렌더링 되어야 합니다. 

❗/ npm run check-types 확인부탁합니다.
    * next브랜치가 아니라 액션이 돌지 않네요.


❗/ 초과갯수로 펼때 layout에 속성에 height만큼은 높이가 늘어나고 렌더링될 일정이 있으면 스크롤로 표시되어야합니다.

---

수고했어요.

2021-05-04 06:16 UTC, jungeun-cho commented on apps/calendar/src/time/panelEvent.ts
> +    totalWidth: 100,
panelgrid.tsx 파일에 TOTAL_WIDTH 공용 상수로 사용할 수 있습니다.

2021-05-04 08:32 UTC, lja1018 commented on apps/calendar/src/components/layout.tsx
> +export const PanelStore = createContext<{ state: LayoutState; dispatch: Dispatch }>({
스토어 구조가 머지되면 맞춰서 변경할 부분입니다!

2021-05-04 09:18 UTC, lja1018 commented on apps/calendar/stories/panel.stories.tsx
> +  { start: mon, end: tue },
넵!

2021-05-06 01:50 UTC, lja1018 commented on apps/calendar/test/app/controller/layout.spec.ts
> +          name: 'milestone',
`string`으로 수정했습니다!

2021-05-10 01:30 UTC, lja1018 commented on apps/calendar/src/components/panelgrid/panelEvents.tsx
> +    const renderedViewModels = viewModels
논의 후 다른 브랜치에서 작업하겠습니다!

2021-05-10 05:41 UTC, jung-han commented on apps/calendar/test/app/time/panelEvent.spec.ts
> +    const expected = [viewModels[1]];
불필요하게 할당해서 사용된 것 같습니다. 바로 사용하거나 의미있는 변수명을 사용해서 할당하는 것이 좋을 것 같습니다.

2021-05-10 05:43 UTC, jung-han commented on apps/calendar/test/app/controller/week.spec.ts
> +      }) as Record<string, Record<string, ScheduleMatrix<ScheduleViewModel>>>;
`Record<string, Record<string, ScheduleMatrix<ScheduleViewModel>>> `
가 반복되서 사용되는 타입이라면 선언후에 사용해도 괜찮을 것 같네요 ㅎㅎ

2021-05-10 05:59 UTC, jung-han commented on apps/calendar/src/components/panel.tsx
> +  const styleInfo =
뭔가 `Info`라는 접미사가 만능처럼 사용이 되어가는 것 같은데.. 최대한 Info라는 단어는 사용을 안하고 적절한 단어를 사용하는게 좋을 것 같습니다

2021-05-10 06:05 UTC, jung-han commented on apps/calendar/src/components/panelgrid/panelgrid.tsx
> +      onClick={() => clickHandler(index)}
핸들러를 외부에 할당해서 작성하는것은 어떤가요?

2021-05-10 06:07 UTC, js87zz commented on apps/calendar/src/components/panelgrid/panelgrid.tsx
> +          />
아 이거 보니까 기억이나네요ㅎㅎ 훨씬 깔끔해졌네요 👍

2021-05-10 06:08 UTC, jung-han commented on apps/calendar/src/components/panelgrid/panelgrid.tsx
> +        panelHeight: (maxTop + 1) * EVENT_HEIGHT,
1을 더해주는 이유가 있을까요?

2021-05-10 06:09 UTC, jung-han commented on apps/calendar/src/components/panelgrid/panelgrid.tsx
> +            clickHandler={onClickCollapseButton}
onClick으로 받아도 괜찮지 않을까요?

2021-05-10 06:10 UTC, js87zz commented on apps/calendar/src/components/panelgrid/panelgrid.tsx
> +  const maxTop = viewModels.reduce((acc, viewModel) => Math.max(acc, viewModel.top), 0);
`const maxTop = Math.max(0, ...viewModel.map(({ top }) => top))`는 어떤가요~?

2021-05-10 06:12 UTC, js87zz commented on apps/calendar/src/controller/panel.ts
> +  name: string;
패널 타입이 고정으로 정해진게 아니었나요?

2021-05-10 06:14 UTC, js87zz commented on apps/calendar/src/css/panel/milestone.css
> +  margin-right: -14px;
축약해서 사용해도 될 것 같습니다~!

2021-05-10 06:15 UTC, jung-han commented on apps/calendar/src/components/panelgrid/panelgrid.tsx
> +import { FunctionComponent, h } from 'preact';
FC로 줄여서 작성할수 잇지않나요?

2021-05-10 06:16 UTC, js87zz commented on apps/calendar/src/time/panelEvent.ts
> +  gridInfoList.forEach((gridInfo, index) => {
gridInfo가 뭔가 좌표값을 나타내는 것 같은데 네이밍을 더 명확하게 변경하면 어떨까요? 지금은 뭔가 객체 데이터처럼 느껴져서요

2021-05-10 06:17 UTC, js87zz commented on apps/calendar/src/time/panelEvent.ts
> +  viewModel.exceedRight = exceedRight;
프로퍼티를 일일이 바꾸는 것 보단 메서드로 캡슐화하는게 더 좋아보여요~

2021-05-10 06:19 UTC, jung-han commented on apps/calendar/src/components/panelgrid/panelgrid.tsx
> +            isClicked={isClickedExceedCount}
제가 약간 헷갈려서 그런데..이 index와 clickedIndex, isClicked 는 각각 독립적인 의미를 갖는건가요?_?

2021-05-10 06:22 UTC, js87zz commented on apps/calendar/src/components/panelgrid/panelgrid.tsx
> +            isClicked={isClickedExceedCount}
저도 이 부분은 네이밍이 좀 더 명확해졌으면 좋겠어요~

2021-05-10 06:22 UTC, jung-han approved these changes
완료입니다~

2021-05-10 07:56 UTC, jungeun-cho commented on apps/calendar/src/components/events/dayEvent.tsx
> +const EVENT_HEIGHT = 20;
다른 컴포넌트에서도 사용됩니다. 상수 정의한부분 공통으로 사용해요~

2021-05-10 08:05 UTC, jungeun-cho commented on apps/calendar/src/css/panel/milestone.css
> +  overflow-y: scroll;
이 스타일 시트 린트 확인해주세요~

2021-05-10 08:10 UTC, jungeun-cho commented on apps/calendar/src/time/panelEvent.ts
> +import { isWeekend, toStartOfDay } from '@src/time/datetime';
이 파일 TC 작성부탁합니다~

2021-05-10 08:14 UTC, jungeun-cho commented on apps/calendar/src/time/panelEvent.ts
> +  const { widthList } = getGridStyleInfo({
인자를 객체형태로 넘길필요가 없어보여요. 3개라서 flat하게 펼쳐서 보내는게어떻할까요

2021-05-10 08:42 UTC, jungeun-cho approved these changes
수고했습니다.
❗️/ 스토리에 패널 maxHeight지정해서 스크롤 생기는 스토리도 추가되면 좋을것같아요.
❗️/ 일정 배치 메소드 TC가 누락되었어요~ 추가 부탁합니다.

추가로 toolbar.tsx파일명 변경(Toolbar.tsx => toolbar.tsx)하고  view.stories에서 사용하지 않는 타입 삭제해서 커밋해놓았습니다.

2021-05-10 10:40 UTC, lja1018 commented on apps/calendar/src/components/panelgrid/panelgrid.tsx
> +        panelHeight: (maxTop + 1) * EVENT_HEIGHT,
가장 윗층의 이벤트가 top 0부터 시작해서 1을 더해서 곱했습니다!

2021-05-10 10:42 UTC, lja1018 commented on apps/calendar/src/controller/panel.ts
> +  name: string;
고정으로 생각해서 타입을 정했었는데 들어갈 수 있는 것을 정해놓지 않은 컨테이너의 형식이라 string으로 변경했습니다!

2021-05-10 10:54 UTC, lja1018 commented on apps/calendar/src/components/panelgrid/panelgrid.tsx
> +import { FunctionComponent, h } from 'preact';
`FunctionalComponent`말곤 없었습니다!

2021-05-10 11:02 UTC, lja1018 commented on apps/calendar/src/components/panelgrid/panelgrid.tsx
> +            isClicked={isClickedExceedCount}
변경했습니다!

2021-05-11 01:40 UTC, lja1018 commented on apps/calendar/src/time/panelEvent.ts
> +  viewModel.exceedRight = exceedRight;
별도 브랜치에서 작업하겠습니다!

2021-05-11 01:44 UTC, merged