feat: panel daynames component
nhn/tui.calendar pull request #803
Opened 2021-05-13 06:13 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description
* add panel daynames component & story

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-05-13 06:17 UTC, seonim-ryu commented
Can one of the admins verify this patch?

2021-05-14 05:36 UTC, jung-han commented
![image](https://user-images.githubusercontent.com/35371660/118226291-a97a8980-b4c1-11eb-841c-879e6ba988a8.png)
아마 PR올릴때마다 이게 계속 나올텐데 jenkins 설정에서 관리자로 등록하거나 해당 브랜치를 젠킨스에서 제거하는게 좋지 않을까요?

2021-05-14 05:47 UTC, jung-han commented on apps/calendar/src/modules/options.ts
> +    narrowWeekend: false,
뭐 개인적인 의견이지만..저번 리뷰때도 남겼지만 narrowWeekend는 주말이란게 좁다는 느낌이여서.. 결국 좁아야 되는 대상이 나타나는 옵션명이 들어가면 좋을 것 같네요 ㅎㅎ

2021-05-14 05:48 UTC, jung-han commented on apps/calendar/src/modules/options.ts
> +function getInitialWeekOptions(optionsData: Options = {}): CalendarWeekOption {
이것도 저번 리뷰때 남기기는 했는데 optionsData에서 options와 data는 따로 의미가 가야하지 않나 라는 개인적인 의견이 있습니다 ㅎㅎ

2021-05-14 05:49 UTC, jung-han commented on apps/calendar/src/modules/options.ts
> +function getInitialWeekOptions(optionsData: Options = {}): CalendarWeekOption {
이 함수는 getInitialWeekOption이 되어야 겠네요

2021-05-14 05:51 UTC, jung-han approved these changes
완료입니다~

2021-05-14 06:58 UTC, jungeun-cho commented on apps/calendar/src/components/panelgrid/dayNames.tsx
> +import { FunctionComponent, h } from 'preact';
daygrid/dayNames.tsx에서
`MonthDayNames`를 DayNames로 변경하여 해당 내용을 통합할 수 있을 것같아요.
두개를 따로 분리할 필요가없고요. 
timezoneWidth와 사용하는 옵션(week. month)옵션을 넘겨주어서요~ 공용으로 사용가능할것같습니다.

2021-05-14 07:00 UTC, jungeun-cho commented on apps/calendar/src/css/panel/dayNames.css
> +.week-dayname {
daynames 스타일도 하나로 통합할 수 있을것같아요.
month-dayname, week-dayname따로 구분짓지 않고 `.dayname`으로요.

2021-05-14 07:01 UTC, jungeun-cho commented on apps/calendar/src/css/panel/dayNames.css
> +.week-dayname {
daygrid/dayNames.css에 작성할 수 있을것같아요.

2021-05-14 07:02 UTC, jungeun-cho commented on apps/calendar/src/css/panel/dayNames.css
> +.week-dayname-leftmargin {
클래스명에는 leftmargin인데 `position: relative`를 설정해주고있습니다.
의미가 연관되어있으면 좋겠습니다.

2021-05-14 07:02 UTC, jungeun-cho commented on apps/calendar/src/modules/options.ts
> +    narrowWeekend: false,
옵션명은 따로 정리해서 논의하기로했어요~!

2021-05-14 07:04 UTC, jungeun-cho commented on apps/calendar/src/modules/options.ts
> +function getInitialWeekOptions(optionsData: Options = {}): CalendarWeekOption {
`initializeWeekOption`어때요?

2021-05-14 07:04 UTC, jungeun-cho commented on apps/calendar/src/modules/options.ts
> +    week: getInitialWeekOptions(optionsData),
`month: initializeMonthOption()` 어때요?

2021-05-14 07:05 UTC, jungeun-cho commented on apps/calendar/src/modules/options.ts
> +function getInitialWeekOptions(optionsData: Options = {}): CalendarWeekOption {
options가 스토어 모듈 이름이라서 구분해준걸꺼에요~!

2021-05-14 07:06 UTC, jungeun-cho commented on apps/calendar/stories/panel.stories.tsx
> +dayNames3day.storyName = '3 days DayNames';
panelGrid/dayNames가 dayGrid/dayNames로 통합된다면 이 스토리는 필요없어질것입니다.

2021-05-14 07:07 UTC, jungeun-cho requested changes
리뷰완료했습니다.
`dayNames.tsx`컴포넌트 통합해서 사용해주세요. 불필요한 중복 컴포넌트라고 생각합니다.
컴포넌트를 사용하는 곳에서 `week`옵션과 `timezoneWidth` 속성을 넘기는 방식으로 수정하는게 좋겠습니다.

2021-05-14 08:17 UTC, js87zz approved these changes
리뷰 완료입니다

2021-05-24 06:37 UTC, js87zz approved these changes
2차 리뷰 이견없습니다.

2021-05-24 07:08 UTC, jungeun-cho commented on apps/calendar/src/components/daygrid/dayNames.tsx
> +  const marginLeft = toPx(timezones.length * timezoneWidth);
이 컴포넌트는 타임존 정보가 필요없을 것같습니다. 
만약 marginLeft를 조절해주어야한다면 이 컴포넌트를 감싸는 wrapper해서 스타일 조절을 해주어야할 것같습니다.

템플릿구조도 item-wrapper가 따로 필요없을 것같구요.

2021-05-24 07:09 UTC, jungeun-cho commented on apps/calendar/.eslintrc.js
> +    '@typescript-eslint/no-useless-constructor': ['error'],
이거 왜 추가한거에요?~

2021-05-24 07:11 UTC, jungeun-cho commented on apps/calendar/src/components/daygrid/dayNames.tsx
> +  timezoneWidth?: number;
이 컴포넌트에서 `timezoneWidth`정보는 필요없을것같습니다.

2021-05-24 07:13 UTC, jungeun-cho commented on apps/calendar/src/components/daygrid/dayNames.tsx
> +      <div className={cls('dayname-item-wrapper')} style={{ marginLeft }}>
marginLeft조절은 이 컴포넌트를 감싸는 외부에서 지정해주어야할것같습니다.
주간뷰그릴때요~! 추가로 border-right, border-left를 표시해주어야한다면 prop로 표시할 border정보를 받든, theme.week.dayname으로 border 정보를 받을 수 있겠구요.

2021-05-24 07:15 UTC, jungeun-cho reviewed
리뷰완료했습니다.

2021-05-24 07:21 UTC, jungeun-cho commented on apps/calendar/src/components/panelgrid/dayNames.tsx
> +import { FunctionComponent, h } from 'preact';
이파일은 이제 필요없는것이죠?

2021-05-24 07:22 UTC, lja1018 commented on apps/calendar/src/components/panelgrid/dayNames.tsx
> +import { FunctionComponent, h } from 'preact';
넵 안그래도 발견해서 반영하면서 지우려고했습니다!

2021-05-24 08:05 UTC, lja1018 commented on apps/calendar/.eslintrc.js
> +    '@typescript-eslint/no-useless-constructor': ['error'],
메신저에서 말씀드린데로 해결해서 롤백합니다.

2021-05-24 08:32 UTC, jungeun-cho commented on apps/calendar/src/components/daygrid/dayNames.tsx
> +  marginLeft?: number;
dayNames스토리에 marginLeft 속성 추가한 스토리도 추가되면좋을것같아요.

2021-05-24 08:32 UTC, jungeun-cho approved these changes
수고하셨습니다.

2021-05-24 08:45 UTC, merged