feat: week view
nhn/tui.calendar pull request #826
Opened 2021-06-10 01:28 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

* add weekView component
* example
![스크린샷 2021-06-10 오전 10 28 13](https://user-images.githubusercontent.com/28647773/121450372-9383ba00-c9d6-11eb-8c1a-f566cd1d01db.png)

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-06-10 05:40 UTC, dotaitch approved these changes
리뷰 완료합니다.

2021-06-10 05:40 UTC, dotaitch commented on apps/calendar/src/components/panelgrid/panelgrid.tsx
> +  // @TODO: 테마에서 값 가져와서 설정
이런 주석은 남아있어도 되는 건가요?

2021-06-10 05:40 UTC, dotaitch commented on apps/calendar/src/components/panelgrid/panelgrid.tsx
> +  // @TODO: 테마에서 값 가져와서 설정
남아야 한다면 영어로 주석달아야 하지 않나요??

2021-06-10 05:56 UTC, jungeun-cho commented on apps/calendar/src/util/gridHelper.ts
> +};
메서드 명이 model를 반환하는데 set~으로 시작하고있어요. 
top값을 구해준다고 명시하는것이 좋겠습니다.

2021-06-10 05:57 UTC, jungeun-cho commented on apps/calendar/src/util/gridHelper.ts
> +  return eventModels;
`flatMap`을 사용하여 바로 반환하는게 어때요?

2021-06-10 05:58 UTC, jungeun-cho commented on apps/calendar/src/components/panelgrid/dayGridEvents.tsx
> +  setDayGridEventModels(eventModels);
flattenMatrix와 top값을 설정해주는 부분을 해주는 메소드인 `getDayGridEventModels`로 분리하고 반환된 이벤트 모델을 바로 사용하도록 합니다.

2021-06-10 06:21 UTC, js87zz commented on apps/calendar/src/components/panelgrid/panelgrid.tsx
> +    const eventModelsInCell = eventModels.filter(isInGrid(cell));
`eventModel`이 정확히 어떠한 역할을 하는건가요? 변수명만으로 의미 전달이 더 명확히 전달되면 좋을 것 같아요

2021-06-10 06:22 UTC, js87zz commented on apps/calendar/src/components/view/week.tsx
> +    } as ColumnInfo;
리턴문없이 가능하겠네요

2021-06-10 06:22 UTC, js87zz commented on apps/calendar/src/components/view/week.tsx
> +  }); // @TODO: 이번주 기준으로 계산(prev, next 사용 시 날짜 계산 필요)
주석도 영문으로 작성해야곘네요~

2021-06-10 06:27 UTC, js87zz commented on apps/calendar/src/components/view/week.tsx
> +  } = useStore(['template', 'theme', 'options', 'dataStore', 'layout']);
이렇게 인자를 넘기는 것보다 모든 state를 가져오는건 API를 하나 만들어서 사용하는 게 어떨까요? 어차피 구조분해 하는 과정에서 어떤 state를 쓰는지는 알 수 있을 것 같아서요

2021-06-10 06:28 UTC, jungeun-cho commented on apps/calendar/src/components/view/week.tsx
> +import range from 'tui-code-snippet/array/range';
utils.ts 파일에 정의되어있어요.

2021-06-10 06:29 UTC, jungeun-cho commented on apps/calendar/src/components/view/week.tsx
> +function getDayNames(options: OptionData) {
넘겨받은 파라미터를 사용하지 않습니다. 지워주세요~

2021-06-10 06:30 UTC, jungeun-cho commented on apps/calendar/src/components/view/week.tsx
> +  const cells = range(0, 7).map((day) => {
무조건 7일로 만든느것이아니라, workweek이나 narrowWeekend옵션도 적용되서 렌더링되어야합니다. 확인부탁합니다.

2021-06-10 06:32 UTC, js87zz commented on apps/calendar/src/components/view/week.tsx
> +    layout.layout?.height - layout.milestone?.height - layout.task?.height - layout.allday?.height;
layout안에 또 layout 프로퍼티가 있는건가요? 그리고 이렇게 옵셔널로 이어 쓰면 숫자가 아닌 값도 나올텐데 문제 없나요?

2021-06-10 06:33 UTC, js87zz commented on apps/calendar/src/controller/panel.ts
> +export const DEFAULT_PANEL_HEIGHT = 72;
개인적으로 여기저기서 많이 쓰이는 상수는 별도 파일로 구성해도 좋을 것 같아요.

2021-06-10 06:37 UTC, js87zz commented on apps/calendar/src/util/gridHelper.ts
> +  });
이런 반복문 코드가 많다면 반복문을 실행하는 함수를 하나 만들어두고 순회하면서 수행될 코드를 iteratee로 넘겨서 사용해도 좋을 것 같아요.

2021-06-10 06:39 UTC, js87zz commented on apps/calendar/src/util/gridHelper.ts
> +  return models;
`map`메서드 쓰는게 낫지 않을까요?
```js
return models.map((model) => {
  model.top += 1;
  return model;
});
```

2021-06-10 06:42 UTC, js87zz commented on apps/calendar/src/util/gridHelper.ts
> +  ] as Panel[];
단언으로 강제변환하지 않고 `const panels: Panel[]`로 써도 되지 않나요~?

2021-06-10 06:43 UTC, js87zz commented on apps/calendar/test/app/week.spec.ts
> +    expect(week.render() instanceof Week).toBe(true);
`toBeInstanceOf `매처를 쓰는게 더 좋겠네요~!

2021-06-10 06:46 UTC, js87zz approved these changes
리뷰 완료입니다! 반목문을 순회하는 코드가 좀 있는데 공통으로 분리할 수 있는 부분은 분리해서 가독성을 좀 높히면 좋겠어요.

2021-06-10 07:26 UTC, jungeun-cho commented on apps/calendar/src/components/view/week.tsx
> +  } = useStore(['template', 'theme', 'options', 'dataStore', 'layout']);
`useStore()`사용하면 모든 상태를 가져올수있습니다.ㅎㅎ

2021-06-10 07:47 UTC, jungeun-cho requested changes
수고했습니다. 아래 내용 확인부탁합니다~!
---

- 월간뷰 creation guide가 나오지 않고있어요. 확인부탁합니다.
- 일정이 깨지고있는데요. 타임그리드 matrix 계산하는쪽 디버깅부탁합니다.
    - v1이랑 비교해보세요! 
<img width="244" alt="스크린샷 2021-06-10 16 30 51" src="https://user-images.githubusercontent.com/43128697/121485658-5d146200-ca0b-11eb-9a35-0fc1052366b9.png">
- 스토리북에 workweek, narrowWeekend옵션 적용한 스토리도 추가해주세요.

2021-06-11 06:53 UTC, lja1018 commented on apps/calendar/src/components/view/week.tsx
> +    } as ColumnInfo;
객체라서 return을 명시해줬습니다!

2021-06-11 06:53 UTC, lja1018 commented on apps/calendar/src/components/view/week.tsx
> +  }); // @TODO: 이번주 기준으로 계산(prev, next 사용 시 날짜 계산 필요)
개발 브랜치라서 한글로 적어뒀는데 영문으로 변경하겠습니다.

2021-06-11 06:53 UTC, lja1018 commented on apps/calendar/src/controller/panel.ts
> +export const DEFAULT_PANEL_HEIGHT = 72;
고려해보겠습니다!

2021-06-11 06:53 UTC, lja1018 commented on apps/calendar/src/components/panelgrid/panelgrid.tsx
> +    const eventModelsInCell = eventModels.filter(isInGrid(cell));
이전의 `scheduleViewModel`을 `eventModel`로 바꿨습니다!  아직 전체적으로 바꾸진 않았고 일단 사용하는 `scheduleViewModel`들은 `eventModel`로 사용하고있습니다. 다른 브랜치에서 한번에 바꿀 예정입니다.

2021-06-11 08:06 UTC, lja1018 commented on apps/calendar/src/components/view/week.tsx
> +    layout.layout?.height - layout.milestone?.height - layout.task?.height - layout.allday?.height;
넵 `layout` 관련 값(높이 등)을 저장하기 위한 스토어 모듈안에 각 `layout`, `milestone` 등 패널의 정보들이 담겨있어서 `layout.layout` 같은 형태가 됬습니다.. 옵셔널은 기본값을 처리해서 해결하겠습니다!

2021-06-11 09:35 UTC, lja1018 commented on apps/calendar/src/components/view/week.tsx
> +    layout.layout?.height - layout.milestone?.height - layout.task?.height - layout.allday?.height;
`grid.XXX`형태로 수정하겠습니다~!

2021-06-14 07:07 UTC, js87zz commented on apps/calendar/src/components/view/day.tsx
> +      <Panel name="time" height={grid.layout?.height - grid.milestone?.height}>
`layout?`이 없는 경우에는 계산 결과가 숫자가 아닐텐데 상관없나요? 만약 둘다 항상 값이 있다면 `?`이 아니라 `!`로 되어야겠네요~

2021-06-14 07:08 UTC, js87zz commented on apps/calendar/src/components/view/week.tsx
> +  // @TODO: 이번주 기준으로 계산(prev, next 사용 시 날짜 계산 필요)
여기도 영문주석으로 바껴야겠네요~!

2021-06-14 07:11 UTC, js87zz commented on apps/calendar/src/modules/index.ts
> +export { default as grid } from '@src/modules/grid';
처음부터 named export로 쓰는게 낫지 않나요?

2021-06-14 07:13 UTC, lja1018 commented on apps/calendar/src/components/view/day.tsx
> +      <Panel name="time" height={grid.layout?.height - grid.milestone?.height}>
위에 `timePanelHeight`를 계산해두고 사용하지 않았네요.. 수정하겠습니다!

2021-06-14 07:13 UTC, js87zz commented on apps/calendar/src/components/view/week.tsx
> +  } = grid;
자주 반복되면 따로 유틸로 분리해도 좋을 것 같습니다~이게 전부이면 그냥 이대호 두면 될 것 같구요ㅎㅎ

2021-06-14 07:14 UTC, js87zz commented on apps/calendar/src/components/view/week.tsx
> +  } = grid;
높이 가져오는 코드가 자주 반복되면 따로 유틸로 분리해도 좋을 것 같습니다~이게 전부이면 그냥 이대로 두면 될 것 같구요ㅎㅎ

2021-06-14 07:14 UTC, js87zz approved these changes
리뷰 완료입니다!

2021-06-14 14:18 UTC, dongsik-yoo reviewed
리뷰 완료합니다. 수고하셨습니다.

2021-06-14 14:18 UTC, dongsik-yoo commented on apps/calendar/src/components/view/day.tsx
> +      <Panel name="time" height={grid.layout?.height - grid.milestone?.height}>
Layout 컴포넌트에서 마지막 패널은 자동으로 auto 크기로 높이/너비를 꽉 채울 수 있는 옵션 `autoSize={1}`이 있어요.
layout.stories.tsx 참고하시면 됩니다.

2021-06-14 14:18 UTC, dongsik-yoo commented on apps/calendar/src/components/view/week.tsx
> +  const nowDay = now.getDay();
toStartOfDay를 했기 때문에 renderDay와 nowDay가 동일한데요. 따로 변수로 선언할 필요가 있나요?

2021-06-14 14:18 UTC, dongsik-yoo commented on apps/calendar/src/components/view/week.tsx
> +  } = grid;
위에도 남겼지만 이럴 때 쓰려고 autoSize를 만들어 두었습니다.

2021-06-14 14:18 UTC, dongsik-yoo commented on apps/calendar/src/components/view/week.tsx
> +          marginLeft={120}
왼쪽 마진은 나중에 테마할 때 처리되는거죠?

2021-06-14 14:18 UTC, dongsik-yoo commented on apps/calendar/src/components/view/week.tsx
> +    <Layout height={layoutHeight}>
v1의 인터페이스 중에서 toggleTaskView와 toggleScheduleView 기능이 있어요. 패널들은 숨길 수 있는 기능인데요. 생성자 옵션(`taskView`, `scheduleView`)를 통해서도 제어 가능합니다.
이에 따라 패널들이 보이고 안 보이고 할 수 있어야 합니다.

2021-06-14 14:18 UTC, dongsik-yoo commented on apps/calendar/src/modules/grid.ts
> +    height: 500,
기본값이 있어서 물어 보는 건데요. 기존에는 캘린더 생성자에서 받은 부모 엘리먼트(컨테이너)에 꽉 채우도록 되어 있어요. 스펙이 변경된 것인지, 기능이 누락된 것인지 확인 부탁드립니다.

2021-06-14 14:18 UTC, dongsik-yoo commented on apps/calendar/src/util/gridHelper.ts
> +function forEachMatrix3d<T>(matrices: Matrix3d<T>, iteratee: (target: T, index?: number) => void) {
와, 좋네요. 전에는 이걸 왜 생각 못했을까요

2021-06-16 03:04 UTC, lja1018 commented on apps/calendar/src/components/view/week.tsx
> +          marginLeft={120}
넵!

2021-06-16 03:05 UTC, lja1018 commented on apps/calendar/src/modules/grid.ts
> +    height: 500,
기능이 누락됬습니다. 고려해서 수정하겠습니다!

2021-06-17 01:13 UTC, lja1018 commented on apps/calendar/src/components/view/day.tsx
> +      <Panel name="time" height={grid.layout?.height - grid.milestone?.height}>
autoSize 적용했습니다!

2021-06-17 01:14 UTC, lja1018 commented on apps/calendar/src/components/view/week.tsx
> +  } = grid;
`autoSize` 적용했습니다!

2021-06-17 02:27 UTC, adhrinae commented
리뷰에서 나왔던 일부분 루프로 치환하는 작업은 Preact의 `children` 타입 정의 문제가 엮여있어서 제가 조사해보고 해결하여 추가로 커밋 얹어서 머지할 예정입니다.

2021-06-17 03:37 UTC, adhrinae commented
## `children` prop의 활용 한계

`src/components/layout.tsx` 파일이 `children` prop을 활용하여 `Panel` 컴포넌트만 children으로 받으려고 시도한 부분이 있었는데, 이 부분 때문에 루프를 적용할 때 에러가 발생했었습니다. 결론은 **"`children` prop을 이용하여 내가 원하는 종류의 컴포넌트만 자손으로 랜더링하게 강제할 수 없다"** 라는 것입니다.

먼저 기존에 작성된 `layout.tsx` 파일의 props 타입 정의는 다음과 같습니다.

<img width="658" alt="iShot2021-06-17 12 17 16" src="https://user-images.githubusercontent.com/14539203/122326156-cd206c00-cf66-11eb-84bd-a00f6959a0da.png">

이렇게 하면 `Panel` 컴포넌트의 props를 받는 컴포넌트만 랜더링될 것이라 기대하지만 실제로는 그렇지 않습니다.

```js
// 이러한 임의의 컴포넌트를 `Layout` 아래에 랜더링 시키면 에러가 날 것으로 기대함
const SomethingElse = () => <div />;
```

<img width="308" alt="iShot2021-06-17 12 18 13" src="https://user-images.githubusercontent.com/14539203/122326384-2ee0d600-cf67-11eb-82b6-acef4f991a8c.png">

그런데 오히려 반대로 내가 원하는 `Panel` 로만 구성된 자손을 루프로 생성시키면 에러가 표시됩니다. 예제는 타입이 뭔가 맞지 않는 것처럼 보이지만 대체로 다 비슷합니다. 특히 `VNode` 에 타입을 지정할 때 `type`, `props`, `key` 가 required 필드이기 때문에 일반적인 용도의 타입 제한에 사용하는데는 제약이 따른다는 것을 알 수 있습니다.

<img width="796" alt="iShot2021-06-17 12 16 53" src="https://user-images.githubusercontent.com/14539203/122326527-6780af80-cf67-11eb-86ee-8662e3bbdec7.png">
<img width="763" alt="iShot2021-06-17 12 16 27" src="https://user-images.githubusercontent.com/14539203/122327342-aa8f5280-cf68-11eb-8a5c-9fee441440f7.png">

원하는대로 동작하지 않는 이유는 JSX 표현식의 결과가 일반적인 `JSX.Element` 로 귀결되기 때문입니다. [(참고)](https://github.com/typescript-cheatsheets/react/issues/271#issuecomment-677644493)
그래서 지정한 타입과 오히려 맞지 않아 에러가 발생합니다.

결과적으로 특정 컴포넌트만 자손으로 받았는지 확인하고 싶다면, 부모 컴포넌트인 `Layout` 이 별도의 타입 가드 함수를 구현하여 사전 검사를 하는 수밖에 없습니다. 하지만 이 정도까지 할 필요성은 없다고 생각합니다.

c.c @lja1018

2021-06-17 05:36 UTC, js87zz commented
@adhrinae 
지나가는 길에 의견을 드리자면.. 아래 타입 지정 자체가 의미가 없을 것 같습니다. panel 타입만 받을 수 있도록 추론되는 것도 아니고 함수 컴포넌트 타입 자체가 지정되는 거라 그냥 일반 children 타입을 그대로 쓰는게 어떨까 싶네요ㅎㅎ
```ts

interface Props {
  children: VNode<typeof Panel> | VNode<typeof Panel>[];
   // ...
}
```

2021-06-17 05:40 UTC, adhrinae commented
@js87zz 네 맞습니다. 기존 코드가 이렇게 되어있길래 '원래 이렇게 안 될텐데 요즘은 되나?' 하면서 좀 더 파고들어가보니 역시 안되더라고요 :(

2021-06-17 07:00 UTC, merged