Feat/event form popup view
nhn/tui.calendar pull request #939
Opened 2021-11-24 06:42 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

* add `eventFormPopup` view
  * only UI(view) has been added
* preview with `calendars`
![스크린샷 2021-11-24 오후 3 38 49](https://user-images.githubusercontent.com/28647773/143187542-b46eac9d-16ee-4883-9a05-4756c645872b.png)
* preview without `calendars`
![스크린샷 2021-11-24 오후 3 39 33](https://user-images.githubusercontent.com/28647773/143187616-f4970a02-06c6-4681-b491-c9bf49784eda.png)

---

Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-11-25 07:59 UTC, adhrinae requested changes
리뷰 완료합니다.
언급했던 테스트 작성하는 부분 보강 한번 시도해주세요.

2021-11-25 07:59 UTC, adhrinae commented on apps/calendar/src/components/popup/calendarSelector.tsx
> +      {calendars && calendars.length && (
이런 분기가 일어나는 부분을 `CalendarSelector` 말고 이 컴포넌트를 랜더링하는 부모쪽에서 할 수 있는 방안으로 해주면 좋겠습니다.
그런데 그렇다 하더라도 이 컴포넌트는 반드시 `calendar.length > 0` 을 보장해주긴 해야하네요.

2021-11-25 07:59 UTC, adhrinae commented on apps/calendar/src/components/popup/dateSelector.tsx
> +      });
v1에 최근에 반영된 부분 참고하여 isAllday 토글 시 잘 변경이 일어나는지, 이전에 사용자가 입력했던 부분이 체크박스 토글 시 잘 유지되는지 등등 로직 보강을 해야겠어요.

https://github.com/nhn/tui.calendar/pull/913

2021-11-25 07:59 UTC, adhrinae commented on apps/calendar/src/components/popup/dateSelector.tsx
> +  const usageStatistics = useStore((state) => state.option.usageStatistics);
요건 별도의 셀렉터 함수로 빼주세요

2021-11-25 07:59 UTC, adhrinae commented on apps/calendar/src/components/popup/eventFormPopup.tsx
> +  const { calendars } = useStore((state) => state.calendar);
이미 셀렉터가 있을거에요

2021-11-25 07:59 UTC, adhrinae commented on apps/calendar/src/components/popup/eventStateSelector.tsx
> +  const [isOpened, setOpened] = useState(false);
이 상태랑, 이 상태를 토글하는 함수의 묶음이 반복되고 있는 것 같은데 재사용 가능한 커스텀 훅으로 분리해서 가져다 쓰도록 만들어도 좋겠네요.

2021-11-25 07:59 UTC, adhrinae commented on apps/calendar/src/components/popup/titleInputBox.tsx
> +      <button className={classNames.privateButton} onClick={() => setPrivate((prev) => !prev)}>
`onClick` 의 인라인 함수를 변수로 끌어올려도 좋겠네요. 랜더링 부분에 뭐가 랜더링 되는지에 집중하여 읽을 수 있으니까요.

2021-11-25 07:59 UTC, adhrinae commented on apps/calendar/src/css/popup/form.css
> +  text-overflow: ellipsis;
`white-space: nowrap` 도 같이 들어가줘야겠네요.

2021-11-26 00:05 UTC, lja1018 commented on apps/calendar/src/components/popup/dateSelector.tsx
> +      });
allday 이벤트일때는 초기에 12~13시로 hour를 설정하는 로직을 추가했습니다.

2021-11-26 06:27 UTC, merged