refactor: layout component
nhn/tui.calendar pull request #957
Opened 2021-12-13 06:26 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- refactoring `layout` component
  - fix rerendering all children components of `layout`
  - extract the height control into the store

https://user-images.githubusercontent.com/28647773/145762885-9358d043-92d3-4b8c-bad5-768a89071f19.mov

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2021-12-14 00:38 UTC, jajugoguma approved these changes
리뷰 완료합니다. 고생하셨습니다!

2021-12-14 00:38 UTC, jajugoguma commented on apps/calendar/src/components/layout.tsx
> +    const childrenArray = toChildArray(componentChildren);
`childArray`나 `childrenArray` 중 하나로 통일하는 것이 좋을 것 같습니다.

2021-12-14 00:38 UTC, jajugoguma commented on apps/calendar/src/components/layout.tsx
>    resizeMode = ResizeMode.RELATIVE,
사용하지 않는 변수는 삭제하는 것이 어떤가요?

2021-12-14 05:45 UTC, adhrinae requested changes
리뷰 완료합니다.
생각보다 변경점들이 공유할만한게 있어서 몇몇 부분은 같이 화면공유 등을 통해 팀단위로 리뷰하는 시간이 있으면 좋을거같네요.

2021-12-14 05:45 UTC, adhrinae commented on apps/calendar/src/components/panel.tsx
> +  const { height } = useStore(panelSelector(name));
지금 이 상태로는 매번 리랜더링마다 `panelSelector` 함수가 새로운 함수를 리턴하는건 변함이 없어요. 차라리 인라인 함수를 `useCallback` 으로 묶어서 `useStore` 에 전달해주세요.

```ts
const { height } = useStore(
	useCallback(state => state.weekViewLayout.dayGridRows[name] ?? {}, [name])
);
```

2021-12-14 05:45 UTC, adhrinae commented on apps/calendar/src/components/panel.tsx
> +  const panelWidth = height ?? props.width ?? DEFAULT_PANEL_HEIGHT;
`??` 을 연속으로 이어 쓸 수 있다는걸 처음 알았네요. 그런데 이 경우라면 그냥 `props` 를 해체하면서 기본값을 할당하고 싶어져요.

2021-12-14 05:45 UTC, adhrinae commented on apps/calendar/src/components/panelResizer.tsx
> +  };
지금 로직대로라면 리랜더링마다 `onDragging`, `onDragEnd` 의 레퍼런스가 바뀌기 때문에 `document.eventListener` 가 올바른 이벤트를 해제하지 못한 채 메모리 누수가 일어날거에요. 매번 새로운 이벤트 리스너가 등록될테니까요.

그런 로직 관리하는데 유리하도록 `useDrag` 를 만든건데, 이 동작을 수행하는데 `useDrag` 를 쓰지 않은 이유가 있나요?
만약 `useDrag` 가 스토어와 결합되는 부분 때문에 퍼포먼스 문제가 우려되어 쓰지 않은거라면 `useDrag` 를 다시 한번 리팩토링하는것도 고려해봐야겠는데요.

2021-12-14 05:45 UTC, adhrinae commented on apps/calendar/src/components/view/day.tsx
> +    <Layout classNames={['day-view']}>
`Layout` 컴포넌트 개편한 김에 `className` 도 따로 배열 신경 안쓰고 받을 수 있게 개선하는게 어떨까요?
`classNames` 말고 일반 컴포넌트처럼 `className` 으로 문자열 받도록요.

2021-12-14 05:45 UTC, adhrinae commented on apps/calendar/src/components/view/week.tsx
> +  const gridRows = DEFAULT_WEEK_PANEL_TYPES.map((key) => {
이 부분은 옵션에 따라 row를 표시하지 말아야 하는 부분도 있을텐데 기본값으로 변경된 이유가 있나요?

2021-12-14 05:45 UTC, adhrinae commented on apps/calendar/src/slices/weekViewLayout.ts
> +  lastPanelType: string | null;
이 부분이 추가되면서 `WeekGridRows` 도 `string` 타입이 추가된거같네요. `Layout` 컴포넌트 때문인 것 같은데 맞나요?

2021-12-14 06:19 UTC, lja1018 commented on apps/calendar/src/components/panel.tsx
> +  const { height } = useStore(panelSelector(name));
나름 생각해서 함수로 뺐는데 생각해보니 새로운 함수가 리턴되는건 똑같네요.
앞으로도 계속 신경쓰다보면 나아질 것 같습니다.

2021-12-14 06:41 UTC, lja1018 commented on apps/calendar/src/components/panelResizer.tsx
> +  };
뭔가 `useDrag`가 이벤트에만 적용 가능하다고 착각한 것 같습니다.
`useDrag` 사용하도록 수정하겠습니다!

2021-12-14 06:42 UTC, lja1018 commented on apps/calendar/src/components/view/day.tsx
> +    <Layout classNames={['day-view']}>
문자열을 받아서 `cls`에 그대로 패스하는 걸 말씀하시는건가요? 요건 게더에서 따로 여쭤보겠습니다!

2021-12-14 06:43 UTC, lja1018 commented on apps/calendar/src/components/view/week.tsx
> +  const gridRows = DEFAULT_WEEK_PANEL_TYPES.map((key) => {
이 부분도 게더에서 답변드리겠습니다.

2021-12-14 06:43 UTC, lja1018 commented on apps/calendar/src/slices/weekViewLayout.ts
> +  lastPanelType: string | null;
넵. 위에서 기본 값으로 변경한 이유와 엮여있습니다. 마찬가지로 게더에서 말씀드리겠습니다.

2021-12-14 06:54 UTC, adhrinae commented on apps/calendar/src/components/view/day.tsx
> +    <Layout classNames={['day-view']}>
네 말그대로 문자열 그대로 받도록 하면 될거같은데요. 다시 보니까 `Layout` 컴포넌트 내부에서 추가로 조합을 해서 `className` 최종 문자열을 만드는 방식으로 되어있었죠 🤔 번거롭네...

2021-12-14 07:18 UTC, lja1018 commented on apps/calendar/src/components/view/day.tsx
> +    <Layout classNames={['day-view']}>
네. `Layout`에서 `.join`으로 이어 붙이고 있어서 `cls`로 가독성있게 변경해봤습니다. 문자열을 받으면 조합하기 까다로워질 것 같아서요.

2021-12-15 07:30 UTC, adhrinae approved these changes

2021-12-20 01:14 UTC, adhrinae commented on apps/calendar/src/helpers/view.ts
> +  }
이정도면 `if/else` 문을 쓰는것보다 `default~` 변수 할당하는 부분에서 삼항연산자로 한번에 선언한 다음 배열에 푸시해도 되지 않을까요? 그리고 타입을 조금 더 정확하게 확인해서 할당하는게 좋겠네요.

```ts
const taskPanel = taskView === true ? 
	['milestone, 'task'] : 
		Array.isArray(taskView) ? 
			taskView : 
			[] :
	[];
```

2021-12-20 06:24 UTC, lja1018 commented on apps/calendar/src/helpers/view.ts
> +  }
일단 삼항연산자를 중첩해서(2번) 사용할 수 없어서 이렇게 작성했습니다.
타입 같은 경우엔 이 옵션이 `Boolean` 또는 `Array` 을 받기 때문에 이정도 확인만 하면 되지 않을까요?

2021-12-20 09:07 UTC, adhrinae commented on apps/calendar/src/helpers/view.ts
> +  }
네 타입스크립트 컴파일러가 정확한 타입 추론을 해주고있다면 괜찮을거같네요.
제가 코멘트를 남기게 된 원인이 100~101번 라인인데, 어차피 `default~` 가 쓰이는 부분은 `isBoolean` 통과한 이후니까 굳이 저렇게 선언할 필요가 없겠다는 생각이 들었어요.
아예 함수 바깥 스코프에 상수처럼 선언한다던지 해서 `isBoolean` 일때는 바로 해당 값을 `displayPanel` 에 넣어주고, 아니라면 `taskView` 를 넣어주는 식으로 하면 되지 않을까요?

2021-12-21 00:54 UTC, lja1018 commented on apps/calendar/src/helpers/view.ts
> +  }
게더에서 얘기 나눈데로 수정했습니다~!

2021-12-21 00:54 UTC, merged