feat: display detail popup
nhn/tui.calendar pull request #981
Opened 2022-01-06 09:04 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- add floating layer container provider to `CalendarConatiner` component
- remove unused `dayEvent`, `floatingLayer` component
- display detail popup when event is clicked(not drag)
- display form popup properly
- apply `createPortal` to popups

#### example

- display detail popup

https://user-images.githubusercontent.com/28647773/148357382-b27e2d53-4a07-46fa-8c4e-6309e9ca635f.mov

- display form popup properly

https://user-images.githubusercontent.com/28647773/148357501-a4dad24b-c447-48d6-9c1b-2d5a59a0d300.mov

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-01-07 01:51 UTC, adhrinae requested changes
리뷰 완료합니다.

2022-01-07 01:51 UTC, adhrinae commented on apps/calendar/src/components/popup/eventDetailPopup.tsx
> +function adjustPopupPosition(eventRect: Rect, layoutRect: Rect, popupRect: Rect) {
이 함수는 위치를 '조정한다' 라기보단 계산한다는 의미가 더 맞겠네요.
가져온 값을 가지고 설정하는 일은 다른데서 하니까요.

2022-01-07 01:51 UTC, adhrinae commented on apps/calendar/src/components/popup/eventDetailPopup.tsx
> +function adjustPopupArrowPosition(eventRect: Rect, layoutRect: Rect, popupRect: Rect) {
`adjustPopupPosition` 에 남긴 코멘트와 비슷합니다.

2022-01-07 01:51 UTC, adhrinae commented on apps/calendar/src/components/popup/eventDetailPopup.tsx
> +      setArrowDirection(direction);
어차피 한 번에 설정되어야 하는 상태의 묶음이라면 그냥 객체 통으로 써도 될거같다 싶긴 하지만... 어차피 batch update라 리랜더링은 한번만 일어나니 괜찮겠지요.

2022-01-07 01:51 UTC, adhrinae commented on apps/calendar/src/components/popup/eventDetailPopup.tsx
> +  }
참고로 이런 조건이 붙어버린 관계로 `eventDetailPopup.stories.tsx` 파일이 지금은 동작하지 않네요.

2022-01-07 01:51 UTC, adhrinae commented on apps/calendar/src/components/popup/eventFormPopup.tsx
> +  } = useStore(useCallback((state) => (state.popup.param as EventFormPopupParam) ?? {}, []));
`PopupParam` 에 따라 리턴해야하는 타입이 바뀌고 있는데 내부 동작 자체는 같더라도 `as` 키워드를 각각 다르게 쓰는 셀렉터를 3개 만들어서 import해서 쓰는건 어떨까 싶어요. 그러면 코드를 딱 봤을때 뭘 의미하는지 더 쉽게 들어오니까요.

```ts
const eventFormPopupParamSelector = (state: CalendarState) => (state.popup.param as EventFormPopupParam) ?? {}
const eventDetailPopupParamSelector = (state: CalendarState) => (state.popup.param as EventDetailPopupParam) ?? {}
// ...
```

2022-01-07 01:51 UTC, adhrinae commented on apps/calendar/src/components/popup/eventFormPopup.tsx
> +      <div role="dialog" className={classNames.popupContainer}>
지금 구조가 되면 `formPopupContainer` 아래에 반드시 `popupContainer` 가 필요해지나요?
아니라면 하나로 합치고 최상단에 있는 녀석이 `role="dialog"` 를 받도록 해줬으면 좋곘는데요.

그리고 모든 팝업이 다 `role="dialog"` 를 가질 수 있도록 해주셔야 하고요.

2022-01-07 01:51 UTC, adhrinae commented on apps/calendar/src/components/popup/eventFormPopup.tsx
> +    zIndex: 1,
여기 있는 수치가 `popupPosition` 에 의해 덮어씌워질 가능성이 없다면 CSS로 빼는게 좋겠지요.

2022-01-07 01:51 UTC, adhrinae commented on apps/calendar/src/components/popup/seeMoreEventsPopup.tsx
> +    <div className={cls('see-more-container')} style={containerStyle}>
이것도 컨테이너 바로 아래에 `see-more` 가 있을 필요가 있는지 마크업 고민을 좀 더 해보는게 좋겠네요.

2022-01-07 01:51 UTC, adhrinae commented on apps/calendar/src/components/popup/seeMoreEventsPopup.tsx
> +  } = useStore(useCallback((state) => (state.popup.param as SeeMorePopupParam) ?? {}, []));
팝업의 셀렉터 코드를 여러개 보다보니, 해당팝업이 자신과 맞는 타입인지 체크하는 로직이 없네요.
지금도 충분히 비슷한 의도로 동작은 하지만 약간 코드의 신뢰성이 떨어진다는 느낌이 들어서요.
`state.popup.type` 도 일치하는지 확인해주고 일치하지 않는다면 빈 객체나 `null` 리턴한 다음 L34에서 체크하는 식으로 하면 되겠어요.

2022-01-07 01:51 UTC, adhrinae commented on apps/calendar/src/hooks/common/drag.ts
> +      }
이거 제가 처음에 잘못된 로직으로 구현했다가 포기하고 지웠던 부분이었는데, 지금이라도 개선되어 들어가서 보기 좋네요. 💯

2022-01-07 01:51 UTC, adhrinae commented on apps/calendar/src/hooks/dayGridCommon/popupWithDayGridSelection.ts
> +      setStartPos({ x: pageX, y: pageY });
스토어 업데이트할 때 `pageX`, `pageY` 도 추가해서 가져다 쓰는게 좋을까요? 나중을 위해서 드래깅중인 `MouseEvent` 도 스토어에 `nativeEvent` 같은 이름으로 담아둘 필요가 있겠네요.

2022-01-07 01:51 UTC, adhrinae commented on apps/calendar/stories/main.stories.tsx
> +      </Layout>
`Main` 은 각각의 뷰 컴포넌트를 담고있고 그 뷰 컴포넌트는 `Layout` 을 다 쓰고 있는데 또 감싸주어야 할 이유가 있나요?

2022-01-07 01:51 UTC, adhrinae commented on apps/calendar/test/app/components/popup/eventFormPopup.spec.tsx
>      const { container } = render(
이 테스트 다시 보니 `container` 가 필요한 이유가 직접 특정 요소가 있는지를 셀렉터로 파악하기 위해서인거로 보이네요.

이 부분은 더 사용자 관점의 테스트가 되도록 만들기 위해 따로 같이 보시죠.

2022-01-07 05:10 UTC, lja1018 commented on apps/calendar/src/calendarContainer.tsx
> +  const [container, containerRefCallback] = useDOMNode<HTMLDivElement>();
`Provider` 자체에서 floating layer까지 렌더링하도록 수정했습니다.

2022-01-07 05:17 UTC, lja1018 commented on apps/calendar/src/components/events/horizontalEvent.tsx
> +}
전에 찾았을 땐 없었던거같은데 한군데 찾았네요. 별도 셀렉터 파일로 뺐습니다!

2022-01-07 05:21 UTC, lja1018 commented on apps/calendar/src/components/events/horizontalEvent.tsx
> +}
다시보니 없는게 맞네요. 아래 리뷰 내용과 합쳐서 별도 분리는 하지 않고 `isDragging`을 꺼내오도록 변경했습니다.

2022-01-07 05:24 UTC, lja1018 commented on apps/calendar/src/components/events/horizontalEvent.tsx
> +  const { show } = useDispatch('popup');
이건 그러면 게더에서 여쭤보겠습니다.

2022-01-07 05:29 UTC, lja1018 commented on apps/calendar/src/components/popup/eventDetailPopup.tsx
> +function adjustPopupPosition(eventRect: Rect, layoutRect: Rect, popupRect: Rect) {
`calculate`로 변경했습니다.

2022-01-07 05:31 UTC, lja1018 commented on apps/calendar/src/components/popup/eventDetailPopup.tsx
> +      setArrowDirection(direction);
스타일 객체와 top값, 문자열 3개의 상태를 묶으려니 모양이 애매해서...
이것도 게더에서 같이 얘기 나눠보겠습니다 ㅋㅋ

2022-01-07 05:43 UTC, lja1018 commented on apps/calendar/src/components/popup/eventDetailPopup.tsx
> +  }
스토리북쪽 점검해서 수정하겠습니다!

2022-01-07 06:27 UTC, lja1018 commented on apps/calendar/src/components/popup/seeMoreEventsPopup.tsx
> +  } = useStore(useCallback((state) => (state.popup.param as SeeMorePopupParam) ?? {}, []));
floating layer가 사라지면서 팝업의 type에 대한 검증이 사라졌네요. 추가했습니다!

2022-01-07 06:37 UTC, lja1018 commented on apps/calendar/stories/main.stories.tsx
> +      </Layout>
팝업들을 `Layout` 컴포넌트에서 렌더링해주다보니 `Main` 컴포넌트를 감싸주지 않으면 팝업이 동작하지 않아서 감쌌습니다.
이것도 게더에서 같이 얘기해보면 좋을 것 같습니다.

2022-01-07 06:38 UTC, lja1018 commented on apps/calendar/test/app/components/popup/eventFormPopup.spec.tsx
>      const { container } = render(
넵. 이전에 얘기했던 부분인데 더 나은 방법을 아직 찾지 못한 상태입니다.

2022-01-07 08:50 UTC, lja1018 commented on apps/calendar/test/app/components/popup/eventFormPopup.spec.tsx
>      const { container } = render(
이야기한대로 찾아봤지만 버튼이나 아이콘을 가져올 수 있는 방법이 마땅치 않아 일부분만 개선했습니다.

2022-01-11 04:49 UTC, adhrinae commented
이건 이제 머지 해도 될거같네요.

2022-01-11 05:04 UTC, merged