feat: add custom event `beforeUpdateEvent`
nhn/tui.calendar pull request #987
Opened 2022-01-12 06:52 UTC by lja1018

### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

- add custom event `beforeUpdateEvent`
- display form popup when edit button is clicked
- remove mergedRef hooks

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

2022-01-12 07:11 UTC, lja1018 commented on apps/calendar/src/components/popup/eventFormPopup.tsx
> +      }
객체가 `TZDate`, `raw` 필드밖에 없어 `TZDate`만 예외처리함.

2022-01-13 03:13 UTC, adhrinae commented
@lja1018 description에 올린 영상이 잘못된 것 같은데 확인 부탁해요.

2022-01-13 05:17 UTC, lja1018 commented
@adhrinae 
넵. 사실 화살표가 찍히는걸 찍은건데 애매하게 됬네요. 본문 내용에 추가하겠습니다.

2022-01-13 06:50 UTC, adhrinae requested changes

2022-01-13 06:50 UTC, adhrinae commented on apps/calendar/src/components/popup/eventDetailPopup.tsx
> +  if (isTopOverLayoutContainer(top, layoutRect, popupRect)) {
`is~OutOf~` 가 더 어울릴 것 같네요.

2022-01-13 06:50 UTC, adhrinae commented on apps/calendar/src/components/popup/eventDetailPopup.tsx
>    const isOverLayoutContainer = popupLeft + popupRect.width > layoutRect.left + layoutRect.width;
`isOutOfLayoutContainer`

2022-01-13 06:50 UTC, adhrinae commented on apps/calendar/src/components/popup/eventDetailPopup.tsx
> +        )}
굳이 별도의 컴포넌트로 분리하지 않아도 되겠습니다.
이 컴포넌트 안에서 한번에 다 처리해보죠.

2022-01-13 07:22 UTC, merged